//! A generated image fed back as input: the bytes one reply produced must
//! reach the next request unchanged, and the model must read them.
//!
//! The image is a solid colour with a checkable answer. The recording then
//! proves byte equality: the base64 payload the generation reply carried is
//! the payload the next request sends.

use base64::{Engine, prelude::BASE64_STANDARD};
use rig::completion::{CompletionModel, CompletionRequest, ToolDefinition};
use rig::image_generation::ImageGenerationModel;
use rig::message::{AssistantContent, ImageMediaType, Message, ToolResultContent, UserContent};
use serde_json::Value;

use crate::support::{ImageContainer, assert_image_bytes};

/// The prompt every generation cell uses.
pub const PROMPT: &str = "A flat square filled edge to edge with one solid, saturated pure red colour. No objects, no text, no texture, no gradient.";

const QUESTION: &str = "What single colour fills this image? Answer with one lowercase word.";

fn media_type(bytes: &[u8]) -> ImageMediaType {
    match assert_image_bytes(bytes) {
        ImageContainer::Png => ImageMediaType::PNG,
        ImageContainer::Jpeg => ImageMediaType::JPEG,
        ImageContainer::Webp => ImageMediaType::WEBP,
        ImageContainer::Gif => ImageMediaType::GIF,
    }
}

fn text(choice: &[AssistantContent]) -> String {
    choice
        .iter()
        .filter_map(|content| match content {
            AssistantContent::Text(text) => Some(text.text.to_ascii_lowercase()),
            _ => None,
        })
        .collect()
}

fn request(
    history: Vec<Message>,
    tools: Vec<ToolDefinition>,
    params: Option<Value>,
) -> CompletionRequest {
    CompletionRequest {
        model: None,
        chat_history: history,
        documents: vec![],
        tools,
        temperature: None,
        max_tokens: Some(1024),
        tool_choice: None,
        additional_params: params,
        output_schema: None,
        record_telemetry_content: false,
    }
}

/// Generate the swatch, `side` pixels square when given, and return its bytes.
pub async fn generate<G>(generator: &G, side: Option<u32>, params: Option<Value>) -> Vec<u8>
where
    G: ImageGenerationModel + Clone,
{
    let mut builder = generator.image_generation_request(PROMPT);
    if let Some(side) = side {
        builder = builder.width(side).height(side);
    }
    if let Some(params) = params {
        builder = builder.additional_params(params);
    }
    let response = builder.send().await.expect("image generation");
    assert_image_bytes(&response.image);
    response.image
}

/// Send the generated bytes to a vision model as user content.
pub async fn as_user_content<M: CompletionModel>(vision: &M, bytes: &[u8], params: Option<Value>) {
    let message = Message::User {
        content: vec![
            UserContent::image_base64(BASE64_STANDARD.encode(bytes), Some(media_type(bytes)), None),
            UserContent::text(QUESTION),
        ],
    };
    let reply = vision
        .completion(request(vec![message], vec![], params))
        .await
        .expect("the vision model reads the generated image");
    assert!(text(&reply.choice).contains("red"), "{:?}", reply.choice);
}

/// Answer a tool call with the generated bytes as an image tool result.
pub async fn as_tool_result<M: CompletionModel>(model: &M, bytes: &[u8], params: Option<Value>) {
    let tool = ToolDefinition {
        name: "render_swatch".to_owned(),
        description: "Render the swatch image the user asks about.".to_owned(),
        parameters: serde_json::json!({ "type": "object", "properties": {}, "required": [] }),
    };
    let prompt = Message::user(format!("Call render_swatch, then answer: {QUESTION}"));
    let first = model
        .completion(request(
            vec![prompt.clone()],
            vec![tool.clone()],
            params.clone(),
        ))
        .await
        .expect("turn one");
    let call = first
        .choice
        .iter()
        .find_map(|content| match content {
            AssistantContent::ToolCall(call) => Some(call.clone()),
            _ => None,
        })
        .expect("the model calls render_swatch");
    let history = vec![
        prompt,
        Message::Assistant {
            id: first.message_id.clone(),
            content: first.choice.clone(),
        },
        Message::User {
            content: vec![UserContent::tool_result_for(
                call.id.clone(),
                call.provider.clone(),
                call.function.name.clone(),
                vec![ToolResultContent::image_base64(
                    BASE64_STANDARD.encode(bytes),
                    Some(media_type(bytes)),
                    None,
                )],
            )],
        },
    ];
    let reply = model
        .completion(request(history, vec![tool], params))
        .await
        .expect("the model reads the image tool result");
    assert!(text(&reply.choice).contains("red"), "{:?}", reply.choice);
}

fn image_payloads(value: &Value, found: &mut Vec<String>) {
    match value {
        Value::Object(object) => {
            for (key, child) in object {
                match (key.as_str(), child) {
                    ("b64_json" | "data", Value::String(text)) if text.len() > 256 => {
                        found.push(text.clone());
                    }
                    ("images", Value::Array(items)) => {
                        found.extend(items.iter().filter_map(Value::as_str).map(str::to_owned));
                    }
                    _ => image_payloads(child, found),
                }
            }
        }
        Value::Array(items) => items.iter().for_each(|item| image_payloads(item, found)),
        _ => {}
    }
}

/// Where the generated bytes must arrive in the later request.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Slot {
    /// A user message's image part.
    UserContent,
    /// The result answering a tool call.
    ToolResult,
}

/// The markers of every object enclosing `needle`: `type` and `role`
/// values and object keys, outermost first.
fn enclosing(value: &Value, needle: &str, trail: &mut Vec<String>, found: &mut Vec<Vec<String>>) {
    match value {
        Value::String(text) if text.contains(needle) => found.push(trail.clone()),
        Value::Object(object) => {
            let depth = trail.len();
            for marker in ["type", "role"] {
                if let Some(value) = object.get(marker).and_then(Value::as_str) {
                    trail.push(value.to_owned());
                }
            }
            for (key, child) in object {
                trail.push(key.clone());
                enclosing(child, needle, trail, found);
                trail.pop();
            }
            trail.truncate(depth);
        }
        Value::Array(items) => items
            .iter()
            .for_each(|item| enclosing(item, needle, trail, found)),
        _ => {}
    }
}

const TOOL_RESULT_MARKERS: &[&str] = &[
    "function_call_output",
    "functionResponse",
    "tool_result",
    "tool",
];

/// The generation reply's image payload is, byte for byte, what a later
/// request sends in `slot`. `provider` names the cassette directory.
pub fn assert_recorded(provider: &str, scenario: &str, slot: Slot) {
    let bodies = crate::cassettes::recorded_interaction_bodies(provider, scenario);
    let generated: Value =
        serde_json::from_str(&bodies[0].1).expect("the generation reply is JSON");
    let mut payloads = Vec::new();
    image_payloads(&generated, &mut payloads);
    let payload = payloads
        .first()
        .expect("the generation reply carries an image payload");
    let bytes = BASE64_STANDARD
        .decode(payload)
        .expect("the payload is base64");
    assert_image_bytes(&bytes);
    let canonical = BASE64_STANDARD.encode(&bytes);
    let mut found = Vec::new();
    for (request, _) in &bodies[1..] {
        if let Ok(request) = serde_json::from_str::<Value>(request) {
            enclosing(&request, &canonical, &mut Vec::new(), &mut found);
        }
    }
    assert!(
        !found.is_empty(),
        "a later request carries the generated bytes unchanged"
    );
    for trail in &found {
        let in_result = trail
            .iter()
            .any(|marker| TOOL_RESULT_MARKERS.contains(&marker.as_str()));
        assert_eq!(
            in_result,
            slot == Slot::ToolResult,
            "the generated bytes travel as {slot:?}: {trail:?}"
        );
    }
}
