[workspace]
git_release_body = """{{ changelog }}"""
git_release_enable = false
git_tag_enable = false
publish = false
release_always = false

[[package]]
name = "rig"
git_release_enable = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
publish = true

[[package]]
name = "rig-bedrock"
publish = true

[[package]]
name = "rig-core"
publish = true

[[package]]
name = "rig-derive"
publish = true

[[package]]
name = "rig-fastembed"
publish = true

[[package]]
name = "rig-gemini-grpc"
publish = true

[[package]]
name = "rig-helixdb"
publish = true

[[package]]
name = "rig-lancedb"
publish = true

[[package]]
name = "rig-memory"
publish = true

[[package]]
name = "rig-milvus"
publish = true

[[package]]
name = "rig-mongodb"
publish = true

[[package]]
name = "rig-neo4j"
publish = true

[[package]]
name = "rig-postgres"
publish = true

[[package]]
name = "rig-qdrant"
publish = true

[[package]]
name = "rig-s3vectors"
publish = true

[[package]]
name = "rig-scylladb"
publish = true

[[package]]
name = "rig-sqlite"
publish = true

[[package]]
name = "rig-surrealdb"
publish = true

[[package]]
name = "rig-vectorize"
publish = true

[[package]]
name = "rig-vertexai"
publish = true

[changelog]
body = """
## [{{ version }}]\
    {%- if release_link -%}\
        ({{ release_link }})\
    {% endif %} \
    - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

    {% for commit in commits %}
        {%- if commit.scope -%}
            - *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}\
                {{ commit.message }}{{ self::username(commit=commit) }}\
                {%- if commit.links %} \
                    ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%})\
                {% endif %}
        {% else -%}
            - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{{ self::username(commit=commit) }}{{ self::pr(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}
{%- if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
    * @{{ contributor.username }}
{%- endfor %}
{% endif -%}
{%- macro username(commit) -%}
    {% if commit.remote.username %} (by @{{ commit.remote.username }}){% endif -%}
{% endmacro -%}
{%- macro pr(commit) -%}
    {% if commit.remote.pr_number %} - #{{ commit.remote.pr_number }}{% endif -%}
{% endmacro -%}
"""
