//! The effect corpus: six golden effect logs, each recorded once by one
//! root-suite test against a cassette transport (a real provider's bytes,
//! replayed over HTTP) with `record_effects()`, committed under
//! `fixtures/*.effects.json`, and replayed here with **no provider, no
//! tool and no memory behind any key** — a replayer answers every dispatch
//! from the record.
//!
//! Both interpreters of the agent program reproduce every golden:
//!
//! - the bus-driven engine (`AgentBuilder::over_bus` … `prompt` /
//!   `stream_prompt`), the program it was recorded with — same preamble,
//!   prompt, tools, hooks, memory, bus policy and run options — hardcoded
//!   here per fixture;
//! - a hand driver of `AgentRun` that steps the run protocol itself and
//!   dispatches each step over the same bus handles.
//!
//! The oracle is the record as data: every replayed dispatch's kind
//! (`serde_json::to_value`), outcome and — for a stream recorded with its
//! events — event sequence must equal the golden's, position by position.
//! The replayer refuses a request that differs from the recorded one, so a
//! divergence in what either interpreter *asks* fails the run at that
//! record, never a passed test with a different trace.
//!
//! A golden is regenerated by its producing root test under
//! `RIG_REGENERATE_GOLDEN=1`, never edited by hand. The producers:
//!
//! | fixture | root test |
//! |---|---|
//! | `anthropic_completion_smoke` | `tests/providers/anthropic/cassette/agent.rs` `completion_smoke_effect_log_is_the_golden_fixture` |
//! | `anthropic_memory_conversation` | `tests/providers/anthropic/cassette/agent.rs` `memory_conversation_effect_log_is_the_golden_fixture` |
//! | `anthropic_streaming_with_events` | `tests/providers/anthropic/cassette/streaming_tools.rs` `streaming_tools_effect_log_is_the_golden_fixture` |
//! | `anthropic_concurrent_tools_serial` | `tests/providers/anthropic/cassette/streaming_tools.rs` `concurrent_tools_serial_effect_log_is_the_golden_fixture` |
//! | `gemini_tool_call_turns` | `tests/providers/gemini/cassette/hook_stress.rs` `tool_call_turns_effect_log_is_the_golden_fixture` |
//! | `mock_invalid_tool_call_recovery` | `tests/core/golden_recovery.rs` `invalid_tool_call_recovery_effect_log_is_the_golden_fixture` |
//! | `anthropic_tool_call_turn` | `tests/providers/anthropic/cassette/effect_corpus.rs` `tool_call_turn_effect_log_is_the_golden_fixture` |
//! | `anthropic_cancelled_stream` | `tests/providers/anthropic/cassette/effect_corpus.rs` `cancelled_stream_effect_log_is_the_golden_fixture` |
//! | `openai_streaming_with_events` | `tests/providers/openai/cassette/effect_corpus.rs` `streaming_with_events_effect_log_is_the_golden_fixture` |
//! | `openai_tool_call_turns` | `tests/providers/openai/cassette/effect_corpus.rs` `tool_call_turns_effect_log_is_the_golden_fixture` |

#![allow(clippy::expect_used, clippy::indexing_slicing, clippy::panic)]

mod corpus;

use corpus::{Hook, Program};

/// The root suite's constants, verbatim (`tests/common/support.rs`,
/// `tests/providers/gemini/cassette/hook_stress.rs`,
/// `tests/core/golden_recovery.rs`).
const BASIC_PREAMBLE: &str = "You are a concise assistant. Answer directly.";
const BASIC_PROMPT: &str = "In one or two sentences, explain what Rust programming language is and why memory safety matters.";
const STREAMING_TOOLS_PREAMBLE: &str =
    "You are a calculator. Use the provided tools before answering arithmetic questions.";
const STREAMING_TOOLS_PROMPT: &str = "Calculate 2 - 5.";
const TWO_TOOL_STREAM_PREAMBLE: &str = "\
You are a precise assistant. When tools are available, you must use them instead of guessing. \
Call both `lookup_harbor_label` and `lookup_orchard_label` before writing any normal text. \
Never call the same tool twice once you already have its result.";
const TWO_TOOL_STREAM_PROMPT: &str = "\
Call `lookup_harbor_label` and `lookup_orchard_label` exactly once each before answering. \
After both tool results are available, stop calling tools and respond in one short sentence that includes both exact tool outputs.";
const CHAIN_PREAMBLE: &str = "You are a calculator assistant. You MUST use the provided tools for \
     every arithmetic operation instead of computing results yourself. Perform the steps in order, \
     using the result of each step as an input to the next. Once you have the final tool result, \
     reply with the final numeric answer in plain text.";
const TOOLS_PREAMBLE: &str = "You are a calculator here to help the user perform arithmetic operations. Use the tools provided to answer the user's question.";
const TOOL_CALL_TURN_PROMPT: &str =
    "Use the add tool to add 17 and 25, then reply with just the number.";
const CANCELLED_STREAM_PREAMBLE: &str = "You are a concise assistant. Answer directly.";
const CANCELLED_STREAM_PROMPT: &str =
    "Write a 600-word essay on the history of the Rust programming language.";
const CHAIN_PROMPT: &str = "First add 20 and 5 with the add tool. Then subtract 4 from that sum with the \
     subtract tool. Report the final number.";

const DEFAULT: Program = Program::DEFAULT;

const COMPLETION_SMOKE: Program = Program {
    fixture: "anthropic_completion_smoke",
    preamble: Some(BASIC_PREAMBLE),
    prompt: BASIC_PROMPT,
    ..DEFAULT
};
const MEMORY_CONVERSATION: Program = Program {
    fixture: "anthropic_memory_conversation",
    preamble: Some(BASIC_PREAMBLE),
    prompt: BASIC_PROMPT,
    conversation: Some("golden-conversation"),
    ..DEFAULT
};
const STREAMING_WITH_EVENTS: Program = Program {
    fixture: "anthropic_streaming_with_events",
    preamble: Some(STREAMING_TOOLS_PREAMBLE),
    prompt: STREAMING_TOOLS_PROMPT,
    default_max_turns: Some(2),
    max_turns: Some(2),
    streamed: true,
    ..DEFAULT
};
const CONCURRENT_TOOLS_SERIAL: Program = Program {
    fixture: "anthropic_concurrent_tools_serial",
    preamble: Some(TWO_TOOL_STREAM_PREAMBLE),
    prompt: TWO_TOOL_STREAM_PROMPT,
    max_turns: Some(8),
    tool_concurrency: Some(2),
    streamed: true,
    ..DEFAULT
};
const TOOL_CALL_TURNS: Program = Program {
    fixture: "gemini_tool_call_turns",
    owner: "stress-agent",
    preamble: Some(CHAIN_PREAMBLE),
    prompt: CHAIN_PROMPT,
    temperature: Some(0.0),
    max_turns: Some(6),
    streamed: true,
    ..DEFAULT
};
const INVALID_TOOL_CALL_RECOVERY: Program = Program {
    fixture: "mock_invalid_tool_call_recovery",
    preamble: Some("Use the add tool."),
    prompt: "What is 2 + 3?",
    max_turns: Some(4),
    hooks: &[Hook::RetryUnknownTool],
    invalid_retries: 1,
    ..DEFAULT
};
const ANTHROPIC_TOOL_CALL_TURN: Program = Program {
    fixture: "anthropic_tool_call_turn",
    preamble: Some(TOOLS_PREAMBLE),
    prompt: TOOL_CALL_TURN_PROMPT,
    temperature: Some(0.0),
    max_turns: Some(3),
    ..DEFAULT
};
const ANTHROPIC_CANCELLED_STREAM: Program = Program {
    fixture: "anthropic_cancelled_stream",
    preamble: Some(CANCELLED_STREAM_PREAMBLE),
    prompt: CANCELLED_STREAM_PROMPT,
    temperature: Some(0.0),
    streamed: true,
    cancel_after_first_delta: true,
    ..DEFAULT
};
const OPENAI_STREAMING_WITH_EVENTS: Program = Program {
    fixture: "openai_streaming_with_events",
    preamble: Some(STREAMING_TOOLS_PREAMBLE),
    prompt: STREAMING_TOOLS_PROMPT,
    temperature: Some(0.0),
    max_turns: Some(3),
    streamed: true,
    ..DEFAULT
};
const OPENAI_TOOL_CALL_TURNS: Program = Program {
    fixture: "openai_tool_call_turns",
    preamble: Some(CHAIN_PREAMBLE),
    prompt: CHAIN_PROMPT,
    temperature: Some(0.0),
    max_turns: Some(6),
    ..DEFAULT
};

both_interpreters! {
    reproduces_completion_smoke: COMPLETION_SMOKE,
    reproduces_memory_conversation: MEMORY_CONVERSATION,
    reproduces_streaming_with_events: STREAMING_WITH_EVENTS,
    reproduces_concurrent_tools_serial: CONCURRENT_TOOLS_SERIAL,
    reproduces_tool_call_turns: TOOL_CALL_TURNS,
    reproduces_invalid_tool_call_recovery: INVALID_TOOL_CALL_RECOVERY,
    reproduces_anthropic_tool_call_turn: ANTHROPIC_TOOL_CALL_TURN,
    reproduces_anthropic_cancelled_stream: ANTHROPIC_CANCELLED_STREAM,
    reproduces_openai_streaming_with_events: OPENAI_STREAMING_WITH_EVENTS,
    reproduces_openai_tool_call_turns: OPENAI_TOOL_CALL_TURNS,
}
