//! The golden effect log: `completion_smoke`, recorded against the real
//! Anthropic cassette by the root suite
//! (`tests/providers/anthropic/cassette/agent.rs`,
//! `completion_smoke_effect_log_is_the_golden_fixture`) into
//! `fixtures/anthropic_completion_smoke.effects.json`. Both interpreters of
//! the agent program — the bus-driven engine and a hand driver of
//! `AgentRun` — must reproduce its records, request and outcome as data,
//! from a replayer alone: the replayer refuses a request that differs from
//! the recorded one, so a divergence in what either interpreter *asks* is a
//! failed run, not a passed test with a different trace.
//!
//! The fixture is regenerated by the root test under
//! `RIG_REGENERATE_GOLDEN=1`, never by hand.

#![allow(clippy::expect_used, clippy::indexing_slicing, clippy::panic)]

use std::time::Duration;

use rig_agent::{
    AgentBuilder,
    run::{AgentRun, AgentRunStep, ModelTurn, RunSpec, prepare_request},
};
use rig_bus::{Bus, ModelHandle};
use rig_core::{
    completion::CompletionRequestBuilder,
    effect::{EffectFamily, EffectRecord, HandlerKey},
};
use rig_effect_log::{EffectLog, EffectLogRecorder, EffectLogReplayer};

/// The root suite's constants, verbatim (`tests/common/support.rs`).
const PREAMBLE: &str = "You are a concise assistant. Answer directly.";
const PROMPT: &str = "In one or two sentences, explain what Rust programming language is and why memory safety matters.";
const OWNER: &str = "golden";

async fn within<T>(future: impl Future<Output = T>) -> T {
    tokio::time::timeout(Duration::from_secs(5), future)
        .await
        .expect("a replay never hangs")
}

fn golden() -> EffectLog {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/anthropic_completion_smoke.effects.json"
    );
    let text = std::fs::read_to_string(path).expect("the golden fixture is committed");
    serde_json::from_str(&text).expect("the golden fixture loads")
}

fn as_data(record: &EffectRecord) -> (serde_json::Value, serde_json::Value) {
    (
        serde_json::to_value(&record.kind).expect("a kind serializes"),
        serde_json::to_value(&record.outcome).expect("an outcome serializes"),
    )
}

fn golden_answer(log: &EffectLog) -> String {
    match &log[0].outcome {
        Ok(rig_core::effect::Outcome::Completion(response)) => response
            .choice
            .iter()
            .filter_map(|content| match content {
                rig_core::message::AssistantContent::Text(text) => Some(text.text.clone()),
                _ => None,
            })
            .collect(),
        other => panic!("the golden record is a completion: {other:?}"),
    }
}

#[tokio::test]
async fn the_golden_log_loads_and_is_one_completion() {
    let log = golden();
    EffectLogReplayer::check_header(&log).expect("a current format");
    assert_eq!(log.len(), 1);
    assert_eq!(log[0].kind.family(), EffectFamily::Completion);
    assert_eq!(log[0].key, HandlerKey::from("golden/model:default"));
    assert!(!golden_answer(&log).is_empty());
}

#[tokio::test]
async fn the_bus_engine_reproduces_the_golden_log_from_a_replayer() {
    let log = golden();
    let (dispatcher, registrar, mut driver) = Bus::channel();
    EffectLogReplayer::register_all(&log, &mut driver).expect("fresh keys");
    let recorder = EffectLogRecorder::new();
    driver.record_to(recorder.clone());
    let task = tokio::spawn(driver);
    let agent = AgentBuilder::over_bus(
        dispatcher.clone(),
        registrar.clone(),
        OWNER,
        log[0].key.clone(),
    )
    .name(OWNER)
    .preamble(PREAMBLE)
    .build();
    agent
        .check_replayable(&log)
        .expect("the same program as the one recorded");
    let response = within(agent.prompt(PROMPT).run())
        .await
        .expect("the replayer answered every request it recognised");
    assert_eq!(response.output, golden_answer(&log));
    drop((agent, dispatcher, registrar));
    within(task).await.expect("driver task");
    let replayed = recorder.take();
    assert_eq!(
        replayed.iter().map(as_data).collect::<Vec<_>>(),
        log.iter().map(as_data).collect::<Vec<_>>(),
        "the engine's effects are the golden records, request and outcome"
    );
}

#[tokio::test]
async fn the_hand_driver_reproduces_the_golden_log_from_a_replayer() {
    let log = golden();
    let (dispatcher, _registrar, mut driver) = Bus::channel();
    EffectLogReplayer::register_all(&log, &mut driver).expect("fresh keys");
    let recorder = EffectLogRecorder::new();
    driver.record_to(recorder.clone());
    let task = tokio::spawn(driver);
    let model: ModelHandle = dispatcher.handle(&log[0].key).expect("the model");
    let spec = RunSpec {
        preamble: Some(PREAMBLE.to_owned()),
        ..RunSpec::new()
    };
    let mut run = AgentRun::from_spec(&spec, PROMPT, None);
    let output = loop {
        match run.next_step().expect("a step") {
            AgentRunStep::CallModel {
                prompt,
                history,
                turn,
            } => {
                let prepared = prepare_request(
                    &spec,
                    &model.capabilities(),
                    &history,
                    Vec::new(),
                    run.output_tool_name(),
                    None,
                )
                .expect("prepared");
                run.advertise_tools(turn, prepared.tools.clone());
                let executable = prepared.executable_tool_names.clone();
                let allowed = prepared.allowed_tool_names.clone();
                let request = prepared
                    .apply(CompletionRequestBuilder::unbound(prompt))
                    .build();
                let response = within(model.complete(request))
                    .await
                    .expect("the replayer recognised the request");
                run.model_response(ModelTurn::new(
                    None,
                    response.choice,
                    response.usage,
                    executable,
                    allowed,
                ))
                .expect("a model turn");
            }
            AgentRunStep::CallTools { .. } => panic!("the golden program calls no tool"),
            AgentRunStep::Done(response) => break response.output,
        }
    };
    assert_eq!(output, golden_answer(&log));
    drop((model, dispatcher));
    within(task).await.expect("driver task");
    let replayed = recorder.take();
    assert_eq!(
        replayed.iter().map(as_data).collect::<Vec<_>>(),
        log.iter().map(as_data).collect::<Vec<_>>(),
        "the hand driver's effects are the golden records, request and outcome"
    );
}
