//! Generated images fed back as input on OpenAI: see `common/image_inputs.rs`.

use rig::providers::openai;
use serde_json::json;

use super::super::support::with_openai_cassette;
use crate::image_inputs;

const GENERATOR: &str = "gpt-image-1-mini";

fn quality() -> Option<serde_json::Value> {
    Some(json!({ "quality": "low" }))
}

/// Responses reads the generated bytes as an image tool result.
#[tokio::test]
async fn generated_image_as_tool_result() {
    const SCENARIO: &str = "image_input_matrix/generated_image_as_tool_result";
    with_openai_cassette(
        "image_input_matrix/generated_image_as_tool_result",
        |client| async move {
            let bytes = image_inputs::generate(
                &client.openai.image_generation(GENERATOR),
                Some(1024),
                quality(),
            )
            .await;
            image_inputs::as_tool_result(
                &client.openai.responses(openai::GPT_5_6),
                &bytes,
                Some(json!({ "reasoning": { "effort": "low" }, "store": false })),
            )
            .await;
        },
    )
    .await;
    image_inputs::assert_recorded("openai", SCENARIO, image_inputs::Slot::ToolResult);
}
