//! The generated agent project: a `Cargo.toml` with one dependency per
//! plugin crate, and a `main.rs` that adds each plugin to the app. Both
//! carry the launcher's version and are written only when their content
//! changes, so cargo rebuilds only what changed and a new launcher version
//! regenerates them.

use std::{
    env, fs,
    path::{Path, PathBuf},
};

use super::{Result, config::Config, paths::Paths};

/// The launcher's version.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The one Bevy version the agent and every plugin build on.
pub const BEVY_VERSION: &str = "0.20.0-rc.2";

/// Where the agent crate comes from.
pub enum Source {
    /// A local rig checkout, by path.
    Local(PathBuf),
    /// crates.io, at the launcher's version.
    Registry,
}

impl Source {
    /// `RIG_SOURCE` when set; else the checkout this launcher was built
    /// from, when it still holds the agent crate (true for
    /// `cargo install --path`); else crates.io.
    pub fn detect() -> Self {
        if let Some(source) = env::var_os("RIG_SOURCE").filter(|source| !source.is_empty()) {
            return Self::Local(PathBuf::from(source));
        }
        let checkout = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        if checkout.join("crates/rig-code/Cargo.toml").is_file() {
            Self::Local(checkout)
        } else {
            Self::Registry
        }
    }
}

/// Write the agent project for `config`. In local-source mode a missing
/// `Cargo.lock` is seeded from the checkout, so the agent builds with the
/// versions the checkout was tested with.
pub fn generate(paths: &Paths, config: &Config) -> Result<()> {
    let source = Source::detect();
    fs::create_dir_all(paths.project.join("src"))?;
    write_if_changed(
        &paths.project.join("Cargo.toml"),
        &manifest(paths, config, &source),
    )?;
    write_if_changed(&paths.project.join("src/main.rs"), &main_rs(paths, config))?;
    let lock = paths.project.join("Cargo.lock");
    if let Source::Local(checkout) = &source
        && !lock.exists()
        && checkout.join("Cargo.lock").is_file()
    {
        fs::copy(checkout.join("Cargo.lock"), lock)?;
    }
    Ok(())
}

fn manifest(paths: &Paths, config: &Config, source: &Source) -> String {
    let agent = match source {
        Source::Local(checkout) => format!(
            "{{ path = {} }}",
            quoted(&checkout.join("crates").join("rig-code"))
        ),
        Source::Registry => format!("\"={VERSION}\""),
    };
    let mut text = format!(
        "# Generated by rig {VERSION} from {}. Edits are overwritten.\n\n\
         [package]\n\
         name = \"rig-code-agent\"\n\
         version = \"0.0.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\n\
         [dependencies]\n\
         rig-code = {agent}\n",
        paths.plugins().display()
    );
    for plugin in &config.plugins {
        let keys = plugin
            .dependency
            .iter()
            .map(|(key, value)| format!("{key} = {value}"))
            .collect::<Vec<_>>()
            .join(", ");
        text.push_str(&format!("{} = {{ {keys} }}\n", plugin.name));
    }
    let mut features = config
        .plugins
        .iter()
        .flat_map(|plugin| &plugin.bevy_features)
        .map(|feature| format!("\"{feature}\""))
        .collect::<Vec<_>>();
    features.sort();
    features.dedup();
    if !features.is_empty() {
        text.push_str(&format!(
            "bevy = {{ version = \"={BEVY_VERSION}\", default-features = false, features = [{}] }}\n",
            features.join(", ")
        ));
    }
    // A plugin written against the published crates then builds against
    // the checkout too, instead of pulling a second copy of them.
    if let Source::Local(checkout) = source {
        text.push_str("\n[patch.crates-io]\n");
        for name in ["rig-code", "rig-core"] {
            let path = quoted(&checkout.join("crates").join(name));
            text.push_str(&format!("{name} = {{ path = {path} }}\n"));
        }
    }
    text.push_str(
        "\n[profile.dev]\n\
         debug = \"line-tables-only\"\n\n\
         [profile.dev.package.\"*\"]\n\
         opt-level = 2\n\n\
         [workspace]\n",
    );
    text
}

fn main_rs(paths: &Paths, config: &Config) -> String {
    let mut text = format!(
        "// Generated by rig {VERSION} from {}. Edits are overwritten.\n\
         fn main() -> rig_code::bevy::app::AppExit {{\n    \
         let mut app = rig_code::bevy::app::App::new();\n    \
         app.add_plugins(rig_code::RigCodePlugins);\n",
        paths.plugins().display()
    );
    for plugin in &config.plugins {
        text.push_str(&format!(
            "    app.add_plugins(<{} as Default>::default());\n",
            plugin.plugin
        ));
    }
    text.push_str("    app.run()\n}\n");
    text
}

/// A TOML basic string holding `path`.
fn quoted(path: &Path) -> String {
    let path = path.display().to_string();
    format!("\"{}\"", path.replace('\\', "\\\\").replace('"', "\\\""))
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if fs::read_to_string(path).is_ok_and(|old| old == content) {
        return Ok(());
    }
    fs::write(path, content)?;
    Ok(())
}
