//! The generated agent project: `Cargo.toml`, `src/main.rs` and
//! `.cargo/config.toml` under `$RIG_HOME/project`. Each file is written only
//! when its contents change, so cargo's fingerprints stay valid, and each
//! names the launcher version, so a new launcher rebuilds the agent.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use super::config::{Config, Source};
use super::home::Home;
use super::{BEVY_VERSION, Result, VERSION};

/// The generated package's name, and so its binary's.
pub const PACKAGE: &str = "rig-code-agent";

/// The lock of the workspace this launcher was built in, packaged with the
/// `rig` crate.
const LOCK: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.lock"));

/// Where the agent project gets the `rig-code` crate from.
pub enum RigSource {
    /// A rig checkout, by path.
    Local(PathBuf),
    /// crates.io, at this launcher's exact version.
    Registry,
}

impl RigSource {
    /// `RIG_SOURCE` when set; else the checkout this launcher was installed
    /// from (`cargo install --path`), when it is still there; else
    /// crates.io. A checkout in cargo's own cache (`cargo install --git`)
    /// does not count: cargo may delete it at any time.
    pub fn detect() -> Result<Self> {
        if let Some(checkout) = std::env::var_os("RIG_SOURCE").filter(|path| !path.is_empty()) {
            let checkout = std::path::absolute(PathBuf::from(checkout))?;
            if !is_checkout(&checkout) {
                return Err(format!(
                    "RIG_SOURCE={} is not a rig checkout: it has no crates/rig-code/Cargo.toml",
                    checkout.display()
                )
                .into());
            }
            return Ok(Self::Local(checkout));
        }
        let installed_from = Path::new(env!("CARGO_MANIFEST_DIR"));
        let cargo_home = std::env::var_os("CARGO_HOME")
            .filter(|path| !path.is_empty())
            .map(PathBuf::from)
            .or_else(|| std::env::home_dir().map(|home| home.join(".cargo")));
        let in_cargo_cache = cargo_home.is_some_and(|cargo| installed_from.starts_with(cargo));
        Ok(if is_checkout(installed_from) && !in_cargo_cache {
            Self::Local(installed_from.to_path_buf())
        } else {
            Self::Registry
        })
    }
}

fn is_checkout(path: &Path) -> bool {
    path.join("crates/rig-code/Cargo.toml").is_file()
}

/// Writes the agent project for `config`. Returns whether any file changed.
pub fn generate(home: &Home, config: &Config, source: &RigSource) -> Result<bool> {
    let project = home.project();
    let mut changed =
        write_if_changed(&project.join("Cargo.toml"), &manifest(home, config, source))?;
    changed |= write_if_changed(&project.join("src/main.rs"), &main_rs(home, config))?;
    changed |= write_if_changed(
        &project.join(".cargo/config.toml"),
        &cargo_config(home, config),
    )?;
    // A lock seeds the versions CI tested: the checkout's, or the one this
    // launcher was built with.
    let lock = project.join("Cargo.lock");
    if !lock.exists() {
        match source {
            RigSource::Local(checkout) => {
                fs::copy(checkout.join("Cargo.lock"), lock)?;
            }
            RigSource::Registry => fs::write(lock, LOCK)?,
        }
    }
    Ok(changed)
}

/// Whether a plugin asks for Bevy features. Only then does the project
/// depend on the `bevy` crate, which carries them and needs a newer Rust
/// than the `bevy_*` crates rig-code uses.
pub fn needs_bevy_umbrella(config: &Config) -> bool {
    config
        .plugins
        .iter()
        .any(|plugin| !plugin.bevy_features.is_empty())
}

fn manifest(home: &Home, config: &Config, source: &RigSource) -> String {
    let features: BTreeSet<&str> = config
        .plugins
        .iter()
        .flat_map(|plugin| plugin.bevy_features.iter().map(String::as_str))
        .collect();
    let features: Vec<String> = features.into_iter().map(quoted).collect();
    let mut text = format!(
        "# Generated by rig {VERSION} from {}. `rig build` and /reload rewrite this file.\n\
         [package]\n\
         name = \"{PACKAGE}\"\n\
         version = \"0.0.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         # Its own workspace, so a RIG_HOME inside another workspace still builds.\n\
         [workspace]\n\
         \n\
         [dependencies]\n",
        home.config().display()
    );
    match source {
        RigSource::Local(checkout) => text.push_str(&format!(
            "rig-code = {{ path = {} }}\n",
            quoted_path(&checkout.join("crates/rig-code"))
        )),
        RigSource::Registry => text.push_str(&format!("rig-code = \"={VERSION}\"\n")),
    }
    if needs_bevy_umbrella(config) {
        text.push_str(&format!(
            "bevy = {{ version = \"={BEVY_VERSION}\", default-features = false, features = [{}] }}\n",
            features.join(", ")
        ));
    }
    let mut listed = BTreeSet::new();
    for package in config
        .plugins
        .iter()
        .filter_map(|plugin| plugin.package.as_ref())
    {
        // A crate with several plugins is one dependency.
        if !listed.insert(package.name.as_str()) {
            continue;
        }
        let source = match &package.source {
            Source::Path(path) => format!("path = {}", quoted_path(path)),
            Source::Git { url, branch, rev } => {
                let mut source = format!("git = {}", quoted(url));
                if let Some(branch) = branch {
                    source.push_str(&format!(", branch = {}", quoted(branch)));
                }
                if let Some(rev) = rev {
                    source.push_str(&format!(", rev = {}", quoted(rev)));
                }
                source
            }
            Source::Version(version) => format!("version = {}", quoted(version)),
        };
        text.push_str(&format!("{} = {{ {source} }}\n", package.name));
    }
    if let RigSource::Local(checkout) = source {
        // A plugin naming the crates.io releases builds against the checkout.
        text.push_str(&format!(
            "\n[patch.crates-io]\nrig-code = {{ path = {} }}\nrig-core = {{ path = {} }}\n",
            quoted_path(&checkout.join("crates/rig-code")),
            quoted_path(&checkout.join("crates/rig-core")),
        ));
    }
    text.push_str(
        "\n[profile.dev]\ndebug = \"line-tables-only\"\n\
         \n[profile.dev.package.\"*\"]\nopt-level = 1\n",
    );
    text
}

fn main_rs(home: &Home, config: &Config) -> String {
    let mut text = format!(
        "// Generated by rig {VERSION} from {}. /reload rewrites this file.\n\
         fn main() -> rig_code::AppExit {{\n    \
             let mut app = rig_code::App::new();\n    \
             app.add_plugins(rig_code::RigCodePlugins);\n    \
             // The loop runner comes before the listed plugins, so a windowing\n    \
             // plugin among them can replace it.\n    \
             app.add_plugins(rig_code::runner());\n",
        home.config().display()
    );
    for plugin in &config.plugins {
        text.push_str(&format!(
            "    app.add_plugins(<{} as Default>::default());\n",
            plugin.type_path
        ));
    }
    text.push_str("    app.run()\n}\n");
    text
}

fn cargo_config(home: &Home, config: &Config) -> String {
    let mut text = format!("# Generated by rig {VERSION}.\n[build]\n");
    if let Some(jobs) = config.jobs {
        text.push_str(&format!("jobs = {jobs}\n"));
    }
    text.push_str(&format!("target-dir = {}\n", quoted_path(&home.target())));
    text
}

/// Writes `contents` to `path` unless it already holds them. Returns
/// whether it wrote.
fn write_if_changed(path: &Path, contents: &str) -> Result<bool> {
    if fs::read_to_string(path).is_ok_and(|current| current == contents) {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(true)
}

fn quoted_path(path: &Path) -> String {
    quoted(&path.to_string_lossy())
}

/// A TOML basic string.
fn quoted(text: &str) -> String {
    let mut quoted = String::from("\"");
    for c in text.chars() {
        match c {
            '"' => quoted.push_str("\\\""),
            '\\' => quoted.push_str("\\\\"),
            c if c.is_control() => quoted.push_str(&format!("\\u{:04X}", u32::from(c))),
            c => quoted.push(c),
        }
    }
    quoted.push('"');
    quoted
}
