use crate::{
    Embed,
    client::{
        self, BearerAuth, HasCompletion, HasEmbeddings, ModelTransport, Provider,
        ProviderClientResult,
    },
    embeddings::EmbeddingsBuilder,
    http_client::{self, HttpClientExt},
    wasm_compat::*,
};

use super::{CompletionModel, EmbeddingModel, ImageEmbeddingModel};
use serde::Deserialize;

// ================================================================
// Main Cohere Client
// ================================================================

#[derive(Debug, Default, Clone, Copy)]
pub struct Cohere;

type CohereApiKey = BearerAuth;

pub type Client<H = crate::http_client::BoxedHttpClient> = client::Client<Cohere, H>;
pub type ClientBuilder<H = crate::markers::Missing> = client::ClientBuilder<Cohere, H>;

impl Provider for Cohere {
    const NAME: &'static str = "cohere";
    const BASE_URL: &'static str = "https://api.cohere.ai";
    const VERIFY_PATH: &'static str = "/models";
    type ApiKey = CohereApiKey;
    type Config = ();
    type EnvInput = CohereApiKey;

    fn build(_: (), _: &CohereApiKey) -> http_client::Result<Self> {
        Ok(Cohere)
    }

    fn from_env<H: HttpClientExt>(http: H) -> ProviderClientResult<Client<H>> {
        Client::from_env_api_key("COHERE_API_KEY", None, http)
    }

    fn from_val<H: HttpClientExt>(input: CohereApiKey, http: H) -> ProviderClientResult<Client<H>> {
        Client::new_with(input, http)
    }
}

impl HasCompletion for Cohere {
    type Model<H>
        = CompletionModel<H>
    where
        H: ModelTransport;

    fn completion_model<H: ModelTransport>(client: &Client<H>, model: String) -> Self::Model<H> {
        CompletionModel::new(client.clone(), model)
    }
}

impl HasEmbeddings for Cohere {
    type Model<H>
        = EmbeddingModel<H>
    where
        H: ModelTransport;

    fn embedding_model<H: ModelTransport>(
        client: &Client<H>,
        model: String,
        ndims: Option<usize>,
    ) -> Self::Model<H> {
        EmbeddingModel::make(client, model, ndims)
    }
}

#[derive(Debug)]
pub struct ApiErrorResponse {
    /// Provider error message; tolerant of `{"message": "..."}`,
    /// `{"error": "..."}`, nested `{"error": {"message": ...}}`, and bodies
    /// carrying both keys. Used for logging only — the raw body is preserved
    /// on the returned error.
    pub message: String,
}

impl<'de> Deserialize<'de> for ApiErrorResponse {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Ok(Self {
            message: crate::providers::internal::envelope::error_message(deserializer)?,
        })
    }
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum ApiResponse<T> {
    Ok(T),
    Err(ApiErrorResponse),
}

impl<T> Client<T>
where
    T: HttpClientExt + Clone + WasmCompatSend + WasmCompatSync + 'static,
{
    pub fn embeddings<D: Embed>(
        &self,
        model: impl Into<String>,
        input_type: &str,
    ) -> EmbeddingsBuilder<EmbeddingModel<T>, D> {
        EmbeddingsBuilder::new(self.embedding_model(model, input_type))
    }

    /// Note: default embedding dimension of 0 will be used if model is not known.
    /// If this is the case, it's better to use function `embedding_model_with_ndims`
    pub fn embedding_model(&self, model: impl Into<String>, input_type: &str) -> EmbeddingModel<T> {
        let model = model.into();
        let ndims = super::model_dimensions_from_identifier(&model).unwrap_or_default();

        EmbeddingModel::new(self.clone(), model, input_type, ndims)
    }

    /// Create a Cohere `embed-english-v3.0` model for embedding PNG, JPEG,
    /// WebP, or GIF bytes.
    ///
    /// Images must be at least 2×2 pixels and no larger than 5 MB.
    /// Cohere accepts one image per request, so
    /// [`crate::embeddings::ImageEmbeddingModel::embed_images`] sends batches
    /// as ordered individual requests.
    pub fn image_embedding_model(&self) -> ImageEmbeddingModel<T> {
        ImageEmbeddingModel::new(self.clone())
    }

    /// Create an embedding model with the given name and the number of dimensions in the embedding generated by the model.
    pub fn embedding_model_with_ndims(
        &self,
        model: impl Into<String>,
        input_type: &str,
        ndims: usize,
    ) -> EmbeddingModel<T> {
        EmbeddingModel::new(self.clone(), model, input_type, ndims)
    }
}
#[cfg(test)]
mod tests;
