//! Types that replace the AWS Bedrock Runtime SDK's `ConverseOutput` type.
//! This is required so that we can impl Serialize and Deserialize.
//!
//! Rig's normalized [`CompletionResponse`](rig_core::completion::CompletionResponse)
//! reads only part of the Converse response, but this type is what
//! `raw_completion` hands back — the escape hatch whose whole purpose is that
//! nothing the provider sent has been thrown away. Model-specific extras
//! (`additional_model_response_fields`) are carried as plain
//! [`serde_json::Value`].
//!
//! The guardrail trace, performance configuration and service tier keep the
//! SDK's own types rather than gaining hand-written mirrors: they are deeply
//! nested (a guardrail assessment alone is a dozen types), and a mirror that
//! drifts from the SDK would reintroduce exactly the silent loss this exists
//! to prevent. Those three are `#[serde(skip)]` because the SDK types are not
//! `Serialize`, so a serialized `InternalConverseOutput` — a cassette fixture,
//! a persisted response — omits them while an in-process caller reads them in
//! full.
use std::fmt;

use aws_sdk_bedrockruntime::types as aws_bedrock;
use serde::{Deserialize, Serialize};

use super::errors::TypeConversionError;
use super::json::AwsDocument;

/// Our own implementation of the AWS Bedrock runtime "converse" operation output.
/// The reason why we need to implement this is that we need to impl Deserialize/Serialize on top of this.
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct InternalConverseOutput {
    /// <p>The result from the call to <code>Converse</code>.</p>
    pub output: Option<ConverseOutput>,
    /// <p>The reason why the model stopped generating output.</p>
    pub stop_reason: StopReason,
    /// <p>The total number of tokens used in the call to <code>Converse</code>. The total includes the tokens input to the model and the tokens generated by the model.</p>
    pub usage: Option<TokenUsage>,
    /// <p>Metrics for the call to <code>Converse</code>.</p>
    pub metrics: Option<ConverseMetrics>,
    /// <p>Additional fields in the response that are unique to the model.</p>
    pub additional_model_response_fields: Option<serde_json::Value>,
    /// The AWS request id, taken from the response's `x-amzn-RequestId`
    /// header. Always present on a successful call, and the identifier AWS
    /// support asks for.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// <p>A trace object that contains information about the Guardrail behavior.</p>
    ///
    /// Populated when the request carried a guardrail configuration with
    /// tracing enabled (see
    /// [`CompletionModel::with_guardrail`](crate::completion::CompletionModel::with_guardrail));
    /// it is the only place Bedrock explains *why* a turn stopped with
    /// [`StopReason::GuardrailIntervened`].
    #[serde(skip)]
    pub trace: Option<aws_bedrock::ConverseTrace>,
    /// <p>Model performance settings for the request.</p>
    #[serde(skip)]
    pub performance_config: Option<aws_bedrock::PerformanceConfiguration>,
    /// <p>The processing tier used to serve the request.</p>
    #[serde(skip)]
    pub service_tier: Option<aws_bedrock::ServiceTier>,
}

impl InternalConverseOutput {
    pub fn usage(&self) -> Option<&TokenUsage> {
        self.usage.as_ref()
    }

    /// Bedrock's guardrail trace for this turn, when one was requested.
    pub fn trace(&self) -> Option<&aws_bedrock::ConverseTrace> {
        self.trace.as_ref()
    }

    /// The AWS request id for this call.
    pub fn request_id(&self) -> Option<&str> {
        self.request_id.as_deref()
    }
}

impl TryFrom<aws_sdk_bedrockruntime::operation::converse::ConverseOutput>
    for InternalConverseOutput
{
    type Error = TypeConversionError;

    fn try_from(
        value: aws_sdk_bedrockruntime::operation::converse::ConverseOutput,
    ) -> Result<Self, Self::Error> {
        // The request id is only reachable through the trait, and only before
        // the struct is destructured.
        let request_id =
            aws_sdk_bedrockruntime::operation::RequestId::request_id(&value).map(str::to_string);

        // `ConverseOutput` is `#[non_exhaustive]` and hides `_request_id`, so
        // the rest pattern is mandatory and cannot be traded for a
        // compile-time guard: every field the SDK adds arrives here silently.
        // That is how the guardrail trace, performance config and service tier
        // came to be dropped, so the list below is checked against the SDK
        // type when the dependency moves, and `converse_output_carries_every_
        // sdk_field` pins the ones known today.
        let aws_sdk_bedrockruntime::operation::converse::ConverseOutput {
            output,
            stop_reason,
            usage,
            metrics,
            additional_model_response_fields,
            trace,
            performance_config,
            service_tier,
            ..
        } = value;

        Ok(Self {
            output: output.map(|x| x.try_into()).transpose()?,
            stop_reason: stop_reason.try_into()?,
            usage: usage.map(|x| x.try_into()).transpose()?,
            metrics: metrics.map(|x| x.try_into()).transpose()?,
            additional_model_response_fields: additional_model_response_fields
                .map(|doc| AwsDocument(doc).into()),
            request_id,
            trace,
            performance_config,
            service_tier,
        })
    }
}

/// Opaque struct used as inner data for the `Unknown` variant defined in enums in
/// the crate.
///
/// This is not intended to be used directly.
#[derive(Clone, Eq, Ord, PartialEq, PartialOrd, Debug, Hash, Serialize, Deserialize)]
pub struct UnknownVariantValue(pub(crate) String);

impl fmt::Display for UnknownVariantValue {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum StopReason {
    ContentFiltered,
    EndTurn,
    GuardrailIntervened,
    MaxTokens,
    StopSequence,
    ToolUse,
    Unknown(UnknownVariantValue),
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct TokenUsage {
    pub input_tokens: i32,
    pub output_tokens: i32,
    pub total_tokens: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_write_input_tokens: Option<i32>,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct ConverseMetrics {
    pub latency_ms: i64,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ConverseOutput {
    Message(Message),
    Unknown,
}

impl ConverseOutput {
    pub fn as_message(&self) -> Result<&Message, TypeConversionError> {
        match self {
            Self::Message(message) => Ok(message),
            invalid => Err(TypeConversionError::new(
                format!("Tried to get ConverseOutput as message but is invalid: {invalid:?}")
                    .as_ref(),
            )),
        }
    }
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Message {
    pub role: ConversationRole,
    pub content: Vec<ContentBlock>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ConversationRole {
    Assistant,
    User,
    Unknown(UnknownVariantValue),
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ContentBlock {
    CachePoint(CachePointBlock),
    CitationsContent(CitationsContentBlock),
    Document(DocumentBlock),
    GuardContent(GuardrailConverseContentBlock),
    Image(ImageBlock),
    ReasoningContent(ReasoningContentBlock),
    Text(String),
    ToolResult(ToolResultBlock),
    ToolUse(ToolUseBlock),
    Video(VideoBlock),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct CachePointBlock {
    #[serde(rename = "type")]
    pub kind: CachePointType,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum CachePointType {
    Default,
    Unknown(UnknownVariantValue),
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct CitationsContentBlock {
    pub content: Option<Vec<CitationGeneratedContent>>,
    pub citations: Option<Vec<Citation>>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum CitationGeneratedContent {
    Text(String),
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Citation {
    pub title: Option<String>,
    pub source_content: Option<Vec<CitationSourceContent>>,
    pub location: Option<CitationLocation>,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum CitationSourceContent {
    Text(String),
    Unknown,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum CitationLocation {
    DocumentChar(DocumentCharLocation),
    DocumentChunk(DocumentChunkLocation),
    DocumentPage(DocumentPageLocation),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct DocumentCharLocation {
    pub document_index: Option<i32>,
    pub start: Option<i32>,
    pub end: Option<i32>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct DocumentChunkLocation {
    pub document_index: Option<i32>,
    pub start: Option<i32>,
    pub end: Option<i32>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct DocumentPageLocation {
    pub document_index: Option<i32>,
    pub start: Option<i32>,
    pub end: Option<i32>,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct DocumentBlock {
    pub format: DocumentFormat,
    pub name: String,
    pub source: Option<DocumentSource>,
    pub context: Option<String>,
    pub citations: Option<CitationsConfig>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum DocumentFormat {
    Csv,
    Doc,
    Docx,
    Html,
    Md,
    Pdf,
    Txt,
    Xls,
    Xlsx,
    Unknown(UnknownVariantValue),
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum DocumentSource {
    Bytes(Blob),
    Content(Vec<DocumentContentBlock>),
    S3Location(S3Location),
    Text(String),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum DocumentContentBlock {
    Text(String),
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct S3Location {
    pub uri: String,
    pub bucket_owner: Option<String>,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct Blob {
    pub inner: Vec<u8>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct CitationsConfig {
    pub enabled: bool,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum GuardrailConverseContentBlock {
    Image(GuardrailConverseImageBlock),
    Text(GuardrailConverseTextBlock),
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct GuardrailConverseImageBlock {
    pub format: GuardrailConverseImageFormat,
    pub source: Option<GuardrailConverseImageSource>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum GuardrailConverseImageFormat {
    Jpeg,
    Png,
    Unknown(UnknownVariantValue),
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum GuardrailConverseImageSource {
    Bytes(Blob),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct GuardrailConverseTextBlock {
    pub text: String,
    pub qualifiers: Option<Vec<GuardrailConverseContentQualifier>>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum GuardrailConverseContentQualifier {
    GroundingSource,
    GuardContent,
    Query,
    Unknown(UnknownVariantValue),
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct ImageBlock {
    pub format: ImageFormat,
    pub source: Option<ImageSource>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ImageFormat {
    Gif,
    Jpeg,
    Png,
    Webp,
    Unknown(UnknownVariantValue),
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ImageSource {
    Bytes(Blob),
    S3Location(S3Location),
    #[non_exhaustive]
    Unknown,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ReasoningContentBlock {
    ReasoningText(ReasoningTextBlock),
    RedactedContent(Blob),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct ReasoningTextBlock {
    pub text: String,
    pub signature: Option<String>,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct ToolResultBlock {
    pub tool_use_id: String,
    pub content: Vec<ToolResultContentBlock>,
    pub status: Option<ToolResultStatus>,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ToolResultContentBlock {
    Document(DocumentBlock),
    Image(ImageBlock),
    Json(serde_json::Value),
    Text(String),
    Video(VideoBlock),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct VideoBlock {
    pub format: VideoFormat,
    pub source: Option<VideoSource>,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum VideoFormat {
    Flv,
    Mkv,
    Mov,
    Mp4,
    Mpeg,
    Mpg,
    ThreeGp,
    Webm,
    Wmv,
    Unknown(UnknownVariantValue),
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum VideoSource {
    Bytes(Blob),
    S3Location(S3Location),
    #[non_exhaustive]
    Unknown,
}
#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub struct ToolUseBlock {
    pub tool_use_id: String,
    pub name: String,
    pub input: serde_json::Value,
}

#[derive(Clone, PartialEq, Debug, Serialize, Deserialize)]
pub enum ToolResultStatus {
    /// Renamed due to linting
    #[serde(rename = "Error")]
    IsError,
    Success,
    Unknown(UnknownVariantValue),
}

// TryFrom<T> implementations
//
// The AWS SDK's "string enums" (unit variants only) and unions (one payload
// per variant) mirror mechanically, so the impls are macro-generated. The
// error strings match the historical hand-written impls exactly:
// `Unknown variant for TYPE: {invalid:?}`.

/// Mirror a unit-variant AWS enum: emits owned + borrowed `TryFrom<aws>`
/// impls. Unlisted variants (including this crate's `Unknown`) fall through to
/// a `TypeConversionError`.
macro_rules! mirror_enum {
    ($ours:ident, $aws:ty { $($aws_variant:ident => $ours_variant:ident),+ $(,)? }) => {
        impl TryFrom<$aws> for $ours {
            type Error = TypeConversionError;
            fn try_from(value: $aws) -> Result<Self, Self::Error> {
                <$ours>::try_from(&value)
            }
        }
        impl TryFrom<&$aws> for $ours {
            type Error = TypeConversionError;
            fn try_from(value: &$aws) -> Result<Self, Self::Error> {
                type Aws = $aws;
                match value {
                    $(Aws::$aws_variant => Ok($ours::$ours_variant),)+
                    invalid => Err(TypeConversionError::new(&format!(
                        concat!("Unknown variant for ", stringify!($ours), ": {:?}"),
                        invalid
                    ))),
                }
            }
        }
    };
}

/// Mirror an AWS union (every listed variant carries a single payload that
/// converts via `TryInto`): emits the owned `TryFrom<aws>` impl.
macro_rules! mirror_union {
    ($ours:ident, $aws:ty { $($aws_variant:ident => $ours_variant:ident),+ $(,)? }) => {
        impl TryFrom<$aws> for $ours {
            type Error = TypeConversionError;
            fn try_from(value: $aws) -> Result<Self, Self::Error> {
                type Aws = $aws;
                match value {
                    $(Aws::$aws_variant(value) => Ok($ours::$ours_variant(value.try_into()?)),)+
                    invalid => Err(TypeConversionError::new(&format!(
                        concat!("Unknown variant for ", stringify!($ours), ": {:?}"),
                        invalid
                    ))),
                }
            }
        }
    };
}

mirror_enum!(StopReason, aws_bedrock::StopReason {
    ContentFiltered => ContentFiltered,
    EndTurn => EndTurn,
    GuardrailIntervened => GuardrailIntervened,
    MaxTokens => MaxTokens,
    StopSequence => StopSequence,
    ToolUse => ToolUse,
});
mirror_enum!(ConversationRole, aws_bedrock::ConversationRole {
    Assistant => Assistant,
    User => User,
});
mirror_enum!(CachePointType, aws_bedrock::CachePointType {
    Default => Default,
});
mirror_enum!(DocumentFormat, aws_bedrock::DocumentFormat {
    Csv => Csv,
    Doc => Doc,
    Docx => Docx,
    Html => Html,
    Md => Md,
    Pdf => Pdf,
    Txt => Txt,
    Xls => Xls,
    Xlsx => Xlsx,
});
mirror_enum!(ImageFormat, aws_bedrock::ImageFormat {
    Gif => Gif,
    Jpeg => Jpeg,
    Png => Png,
    Webp => Webp,
});
mirror_enum!(VideoFormat, aws_bedrock::VideoFormat {
    Flv => Flv,
    Mkv => Mkv,
    Mov => Mov,
    Mp4 => Mp4,
    Mpeg => Mpeg,
    Mpg => Mpg,
    ThreeGp => ThreeGp,
    Webm => Webm,
    Wmv => Wmv,
});
mirror_enum!(ToolResultStatus, aws_bedrock::ToolResultStatus {
    Error => IsError,
    Success => Success,
});
mirror_enum!(GuardrailConverseImageFormat, aws_bedrock::GuardrailConverseImageFormat {
    Jpeg => Jpeg,
    Png => Png,
});
mirror_enum!(GuardrailConverseContentQualifier, aws_bedrock::GuardrailConverseContentQualifier {
    GroundingSource => GroundingSource,
    GuardContent => GuardContent,
    Query => Query,
});

mirror_union!(ConverseOutput, aws_bedrock::ConverseOutput {
    Message => Message,
});
mirror_union!(ContentBlock, aws_bedrock::ContentBlock {
    CachePoint => CachePoint,
    CitationsContent => CitationsContent,
    Document => Document,
    GuardContent => GuardContent,
    Image => Image,
    ReasoningContent => ReasoningContent,
    Text => Text,
    ToolResult => ToolResult,
    ToolUse => ToolUse,
    Video => Video,
});
mirror_union!(CitationGeneratedContent, aws_bedrock::CitationGeneratedContent {
    Text => Text,
});
mirror_union!(CitationSourceContent, aws_bedrock::CitationSourceContent {
    Text => Text,
});
mirror_union!(CitationLocation, aws_bedrock::CitationLocation {
    DocumentChar => DocumentChar,
    DocumentChunk => DocumentChunk,
    DocumentPage => DocumentPage,
});
mirror_union!(DocumentContentBlock, aws_bedrock::DocumentContentBlock {
    Text => Text,
});
mirror_union!(GuardrailConverseContentBlock, aws_bedrock::GuardrailConverseContentBlock {
    Image => Image,
    Text => Text,
});
mirror_union!(GuardrailConverseImageSource, aws_bedrock::GuardrailConverseImageSource {
    Bytes => Bytes,
});
mirror_union!(ImageSource, aws_bedrock::ImageSource {
    Bytes => Bytes,
    S3Location => S3Location,
});
mirror_union!(VideoSource, aws_bedrock::VideoSource {
    Bytes => Bytes,
    S3Location => S3Location,
});
mirror_union!(ReasoningContentBlock, aws_bedrock::ReasoningContentBlock {
    ReasoningText => ReasoningText,
    RedactedContent => RedactedContent,
});

// `DocumentSource::Content` carries a `Vec` payload and
// `ToolResultContentBlock::Json` bridges Smithy `Document` into
// `serde_json::Value`, so those two unions stay hand-written.

impl TryFrom<aws_bedrock::DocumentSource> for DocumentSource {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::DocumentSource) -> Result<Self, Self::Error> {
        match value {
            aws_bedrock::DocumentSource::Bytes(value) => {
                Ok(DocumentSource::Bytes(value.try_into()?))
            }
            aws_bedrock::DocumentSource::Content(value) => Ok(DocumentSource::Content(
                value
                    .into_iter()
                    .map(TryInto::try_into)
                    .collect::<Result<_, Self::Error>>()?,
            )),
            aws_bedrock::DocumentSource::S3Location(value) => {
                Ok(DocumentSource::S3Location(value.try_into()?))
            }
            aws_bedrock::DocumentSource::Text(value) => Ok(DocumentSource::Text(value)),
            invalid => Err(TypeConversionError::new(&format!(
                "Unknown variant for DocumentSource: {invalid:?}"
            ))),
        }
    }
}

impl TryFrom<aws_bedrock::ToolResultContentBlock> for ToolResultContentBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::ToolResultContentBlock) -> Result<Self, Self::Error> {
        match value {
            aws_bedrock::ToolResultContentBlock::Document(value) => {
                Ok(ToolResultContentBlock::Document(value.try_into()?))
            }
            aws_bedrock::ToolResultContentBlock::Image(value) => {
                Ok(ToolResultContentBlock::Image(value.try_into()?))
            }
            aws_bedrock::ToolResultContentBlock::Json(value) => {
                Ok(ToolResultContentBlock::Json(AwsDocument(value).into()))
            }
            aws_bedrock::ToolResultContentBlock::Text(value) => {
                Ok(ToolResultContentBlock::Text(value))
            }
            aws_bedrock::ToolResultContentBlock::Video(value) => {
                Ok(ToolResultContentBlock::Video(value.try_into()?))
            }
            invalid => Err(TypeConversionError::new(&format!(
                "Unknown variant for ToolResultContentBlock: {invalid:?}"
            ))),
        }
    }
}

// Struct conversions.

impl TryFrom<aws_bedrock::TokenUsage> for TokenUsage {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::TokenUsage) -> Result<Self, Self::Error> {
        Ok(TokenUsage {
            input_tokens: value.input_tokens,
            output_tokens: value.output_tokens,
            total_tokens: value.total_tokens,
            cache_read_input_tokens: value.cache_read_input_tokens,
            cache_write_input_tokens: value.cache_write_input_tokens,
        })
    }
}

impl TryFrom<aws_bedrock::ConverseMetrics> for ConverseMetrics {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::ConverseMetrics) -> Result<Self, Self::Error> {
        Ok(ConverseMetrics {
            latency_ms: value.latency_ms,
        })
    }
}

impl TryFrom<aws_bedrock::Message> for Message {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::Message) -> Result<Self, Self::Error> {
        Ok(Message {
            role: value.role.try_into()?,
            content: value
                .content
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, Self::Error>>()?,
        })
    }
}

impl TryFrom<aws_bedrock::CachePointBlock> for CachePointBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::CachePointBlock) -> Result<Self, Self::Error> {
        Ok(CachePointBlock {
            kind: value.r#type.try_into()?,
        })
    }
}

impl TryFrom<aws_bedrock::CitationsContentBlock> for CitationsContentBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::CitationsContentBlock) -> Result<Self, Self::Error> {
        Ok(CitationsContentBlock {
            content: Some(
                value
                    .content
                    .unwrap_or_default()
                    .into_iter()
                    .map(TryInto::try_into)
                    .collect::<Result<_, Self::Error>>()?,
            ),
            citations: Some(
                value
                    .citations
                    .unwrap_or_default()
                    .into_iter()
                    .map(TryInto::try_into)
                    .collect::<Result<_, Self::Error>>()?,
            ),
        })
    }
}

impl TryFrom<aws_bedrock::Citation> for Citation {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::Citation) -> Result<Self, Self::Error> {
        Ok(Citation {
            title: value.title,
            source_content: Some(
                value
                    .source_content
                    .unwrap_or_default()
                    .into_iter()
                    .map(TryInto::try_into)
                    .collect::<Result<_, Self::Error>>()?,
            ),
            location: value.location.map(TryInto::try_into).transpose()?,
        })
    }
}

/// The three citation-location structs are field-identical; mirror them with
/// one macro.
macro_rules! mirror_location {
    ($($name:ident),+ $(,)?) => {$(
        impl TryFrom<aws_bedrock::$name> for $name {
            type Error = TypeConversionError;
            fn try_from(value: aws_bedrock::$name) -> Result<Self, Self::Error> {
                Ok($name {
                    document_index: value.document_index,
                    start: value.start,
                    end: value.end,
                })
            }
        }
    )+};
}
mirror_location!(
    DocumentCharLocation,
    DocumentChunkLocation,
    DocumentPageLocation
);

impl TryFrom<aws_bedrock::DocumentBlock> for DocumentBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::DocumentBlock) -> Result<Self, Self::Error> {
        Ok(DocumentBlock {
            format: value.format.try_into()?,
            name: value.name,
            source: value.source.map(TryInto::try_into).transpose()?,
            context: value.context,
            citations: value.citations.map(TryInto::try_into).transpose()?,
        })
    }
}

impl TryFrom<aws_bedrock::S3Location> for S3Location {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::S3Location) -> Result<Self, Self::Error> {
        Ok(S3Location {
            uri: value.uri,
            bucket_owner: value.bucket_owner,
        })
    }
}

impl TryFrom<aws_sdk_bedrockruntime::primitives::Blob> for Blob {
    type Error = TypeConversionError;
    fn try_from(value: aws_sdk_bedrockruntime::primitives::Blob) -> Result<Self, Self::Error> {
        Ok(Blob {
            inner: value.into_inner(),
        })
    }
}

impl TryFrom<aws_bedrock::CitationsConfig> for CitationsConfig {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::CitationsConfig) -> Result<Self, Self::Error> {
        Ok(CitationsConfig {
            enabled: value.enabled,
        })
    }
}

impl TryFrom<aws_bedrock::GuardrailConverseImageBlock> for GuardrailConverseImageBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::GuardrailConverseImageBlock) -> Result<Self, Self::Error> {
        Ok(GuardrailConverseImageBlock {
            format: value.format.try_into()?,
            source: value.source.map(TryInto::try_into).transpose()?,
        })
    }
}

impl TryFrom<aws_bedrock::GuardrailConverseTextBlock> for GuardrailConverseTextBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::GuardrailConverseTextBlock) -> Result<Self, Self::Error> {
        Ok(GuardrailConverseTextBlock {
            text: value.text,
            qualifiers: Some(
                value
                    .qualifiers
                    .unwrap_or_default()
                    .into_iter()
                    .map(|v| (&v).try_into())
                    .collect::<Result<_, Self::Error>>()?,
            ),
        })
    }
}

impl TryFrom<aws_bedrock::ImageBlock> for ImageBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::ImageBlock) -> Result<Self, Self::Error> {
        Ok(ImageBlock {
            format: value.format.try_into()?,
            source: value.source.map(TryInto::try_into).transpose()?,
        })
    }
}

impl TryFrom<aws_bedrock::ReasoningTextBlock> for ReasoningTextBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::ReasoningTextBlock) -> Result<Self, Self::Error> {
        Ok(ReasoningTextBlock {
            text: value.text,
            signature: value.signature,
        })
    }
}

impl TryFrom<aws_bedrock::ToolResultBlock> for ToolResultBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::ToolResultBlock) -> Result<Self, Self::Error> {
        Ok(ToolResultBlock {
            tool_use_id: value.tool_use_id,
            content: value
                .content
                .into_iter()
                .map(TryInto::try_into)
                .collect::<Result<_, Self::Error>>()?,
            status: value.status.map(|v| (&v).try_into()).transpose()?,
        })
    }
}

impl TryFrom<aws_bedrock::VideoBlock> for VideoBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::VideoBlock) -> Result<Self, Self::Error> {
        Ok(VideoBlock {
            format: value.format.try_into()?,
            source: value.source.map(TryInto::try_into).transpose()?,
        })
    }
}

impl TryFrom<aws_bedrock::ToolUseBlock> for ToolUseBlock {
    type Error = TypeConversionError;
    fn try_from(value: aws_bedrock::ToolUseBlock) -> Result<Self, Self::Error> {
        Ok(ToolUseBlock {
            tool_use_id: value.tool_use_id,
            name: value.name,
            input: AwsDocument(value.input).into(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// The escape hatch's contract is that nothing the provider sent was
    /// dropped, and the SDK's output type is `#[non_exhaustive]`, so the
    /// conversion's rest pattern hides every field added upstream. This pins
    /// the ones known today — `trace`, `performance_config` and `service_tier`
    /// were all silently discarded before.
    #[test]
    fn converse_output_carries_every_sdk_field() {
        let sdk_output = aws_sdk_bedrockruntime::operation::converse::ConverseOutput::builder()
            .stop_reason(aws_bedrock::StopReason::GuardrailIntervened)
            .output(aws_bedrock::ConverseOutput::Message(
                aws_bedrock::Message::builder()
                    .role(aws_bedrock::ConversationRole::Assistant)
                    .content(aws_bedrock::ContentBlock::Text("blocked".into()))
                    .build()
                    .unwrap(),
            ))
            .usage(
                aws_bedrock::TokenUsage::builder()
                    .input_tokens(1)
                    .output_tokens(2)
                    .total_tokens(3)
                    .build()
                    .unwrap(),
            )
            .metrics(
                aws_bedrock::ConverseMetrics::builder()
                    .latency_ms(4)
                    .build()
                    .unwrap(),
            )
            .trace(
                aws_bedrock::ConverseTrace::builder()
                    .guardrail(aws_bedrock::GuardrailTraceAssessment::builder().build())
                    .build(),
            )
            .performance_config(
                aws_bedrock::PerformanceConfiguration::builder()
                    .latency(aws_bedrock::PerformanceConfigLatency::Standard)
                    .build(),
            )
            .service_tier(
                aws_bedrock::ServiceTier::builder()
                    .r#type(aws_bedrock::ServiceTierType::Default)
                    .build()
                    .unwrap(),
            )
            .build()
            .unwrap();

        let mirrored = InternalConverseOutput::try_from(sdk_output).unwrap();

        assert!(mirrored.output.is_some());
        assert_eq!(mirrored.stop_reason, StopReason::GuardrailIntervened);
        assert!(mirrored.usage.is_some());
        assert!(mirrored.metrics.is_some());
        assert!(
            mirrored.trace().is_some(),
            "the guardrail trace must survive the conversion"
        );
        assert!(
            mirrored.performance_config.is_some(),
            "the performance configuration must survive the conversion"
        );
        assert!(
            mirrored.service_tier.is_some(),
            "the service tier must survive the conversion"
        );
    }

    /// The SDK types behind `trace`, `performance_config` and `service_tier`
    /// are not `Serialize`, so they are `#[serde(skip)]`: serializing must
    /// still succeed and must not invent values on the way back.
    #[test]
    fn skipped_provider_fields_round_trip_as_absent() {
        let output = InternalConverseOutput {
            output: None,
            stop_reason: StopReason::EndTurn,
            usage: None,
            metrics: None,
            additional_model_response_fields: None,
            request_id: Some("req-1".to_string()),
            trace: None,
            performance_config: None,
            service_tier: None,
        };

        let json = serde_json::to_string(&output).unwrap();
        let restored: InternalConverseOutput = serde_json::from_str(&json).unwrap();

        assert_eq!(restored.request_id(), Some("req-1"));
        assert!(restored.trace().is_none());
        assert!(restored.performance_config.is_none());
        assert!(restored.service_tier.is_none());
    }

    #[test]
    fn mirror_enum_converts_known_variants() {
        assert_eq!(
            StopReason::try_from(aws_bedrock::StopReason::EndTurn).unwrap(),
            StopReason::EndTurn
        );
        // Borrowed impl.
        assert_eq!(
            StopReason::try_from(&aws_bedrock::StopReason::ToolUse).unwrap(),
            StopReason::ToolUse
        );
        // A renamed pairing (aws `Error` -> ours `IsError`).
        assert_eq!(
            ToolResultStatus::try_from(aws_bedrock::ToolResultStatus::Error).unwrap(),
            ToolResultStatus::IsError
        );
    }

    #[test]
    fn mirror_enum_unknown_variant_preserves_error_string() {
        let unknown = aws_bedrock::StopReason::from("weird_stop");
        let err = StopReason::try_from(unknown.clone()).unwrap_err();
        assert_eq!(
            err.to_string(),
            format!("Unknown variant for StopReason: {unknown:?}")
        );

        let err =
            ConversationRole::try_from(aws_bedrock::ConversationRole::from("nope")).unwrap_err();
        assert!(
            err.to_string()
                .starts_with("Unknown variant for ConversationRole:")
        );
    }

    #[test]
    fn additional_model_response_fields_survive_as_json() {
        let doc: AwsDocument = json!({"reasoning_effort": "low", "depth": 3}).into();
        let output = aws_sdk_bedrockruntime::operation::converse::ConverseOutput::builder()
            .stop_reason(aws_bedrock::StopReason::EndTurn)
            .additional_model_response_fields(doc.0)
            .build()
            .unwrap();

        let internal = InternalConverseOutput::try_from(output).unwrap();
        assert_eq!(
            internal.additional_model_response_fields,
            Some(json!({"reasoning_effort": "low", "depth": 3}))
        );

        // The whole normalized output stays serializable and the extras
        // survive a serde round trip.
        let value = serde_json::to_value(&internal).unwrap();
        assert_eq!(
            value.get("additional_model_response_fields"),
            Some(&json!({"reasoning_effort": "low", "depth": 3}))
        );
        let back: InternalConverseOutput = serde_json::from_value(value).unwrap();
        assert_eq!(back, internal);
    }

    #[test]
    fn tool_use_input_decodes_into_json_value() {
        let aws_block = aws_bedrock::ToolUseBlock::builder()
            .tool_use_id("call_1")
            .name("add")
            .input(AwsDocument::from(json!({"x": 1, "y": 2})).0)
            .build()
            .unwrap();

        let ours = ToolUseBlock::try_from(aws_block).unwrap();
        assert_eq!(ours.tool_use_id, "call_1");
        assert_eq!(ours.name, "add");
        assert_eq!(ours.input, json!({"x": 1, "y": 2}));
    }
}
