//! Handlers that replay recorded effect requests, outcomes, and stream items.
//!
//! ```
//! use rig_cassette::effect_log::{EffectLog, EffectLogReplayer};
//! let handlers = EffectLogReplayer::for_log(&EffectLog::default())?;
//! assert!(handlers.is_empty());
//! # Ok::<(), rig_core::error::ErrorReport>(())
//! ```

use std::{
    collections::{BTreeMap, VecDeque},
    sync::{Arc, Mutex, PoisonError},
};

use rig_core::{
    completion::{ModelRef, ProviderCapabilities},
    effect::{
        EffectFamily, EffectId, EffectKind, EffectRecord, EmbedModality, FamilyDescriptor,
        HandlerDescriptor, HandlerKey,
    },
    error::{ErrorKind, ErrorReport},
};

use rig_core::serve::{Dispatch, Reply, Serve};

use super::log::canonical_tool_args;
use super::{EffectLog, stable_hash};

/// Selects request comparison by payload or [`stable_hash`].
/// Payload diagnostics name the first differing field path; hash diagnostics
/// include both hashes. Records retain the full request in either mode.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RequestCheck {
    /// Compare the payloads as data.
    #[default]
    Payload,
    /// Compare their stable hashes.
    Hash,
}

/// A shared signal for refusals generated by replayers, separate from error
/// outcomes stored in the log. A delivery scheduler can stop waiting for an
/// impossible trace without mistaking a recorded divergence for a new refusal.
#[derive(Clone, Default)]
pub struct ReplayRefusals(Arc<Mutex<Option<ErrorReport>>>);

impl ReplayRefusals {
    /// Take the first pending refusal, if a replayer rejected a dispatch.
    pub fn take(&self) -> Option<ErrorReport> {
        self.0.lock().unwrap_or_else(PoisonError::into_inner).take()
    }

    fn report(&self, report: &ErrorReport) {
        self.0
            .lock()
            .unwrap_or_else(PoisonError::into_inner)
            .get_or_insert_with(|| report.clone());
    }
}

/// Replays one handler key's recorded dispatches, checking incoming requests
/// and returning divergence errors for missing or mismatched records.
///
/// [`for_key`](Self::for_key) consumes records in order for runtimes that mint
/// new IDs. [`for_key_by_id`](Self::for_key_by_id) consumes records by their
/// recorded IDs regardless of arrival order.
pub struct EffectLogReplayer {
    key: HandlerKey,
    family: EffectFamily,
    descriptor: HandlerDescriptor,
    records: Mutex<Records>,
    stream_errors: BTreeMap<EffectId, Vec<super::RecordedStreamError>>,
    check: RequestCheck,
    refusals: Option<ReplayRefusals>,
}

/// The records a replayer answers from, in its mode.
enum Records {
    /// In recorded order, front first.
    ByPosition(VecDeque<EffectRecord>),
    /// By the dispatch's id.
    ById(BTreeMap<EffectId, EffectRecord>),
}

impl Records {
    fn len(&self) -> usize {
        match self {
            Self::ByPosition(records) => records.len(),
            Self::ById(records) => records.len(),
        }
    }
}

impl EffectLogReplayer {
    /// Build an ordered replayer for `key`, validating the log header.
    /// Required keys without records return divergence on dispatch. Returns an
    /// error if the key is unknown or lacks enough metadata to describe it.
    pub fn for_key(log: &EffectLog, key: &HandlerKey) -> Result<Self, ErrorReport> {
        let records = Self::records_of(log, key);
        let by_position: VecDeque<EffectRecord> = records.into();
        let first = by_position.front().cloned();
        Self::describing(log, key, first, Records::ByPosition(by_position))
    }

    /// A replayer for `key` answering by id: see the type's docs. Described
    /// as [`for_key`](Self::for_key) describes.
    pub fn for_key_by_id(log: &EffectLog, key: &HandlerKey) -> Result<Self, ErrorReport> {
        let records = Self::records_of(log, key);
        let first = records.first().cloned();
        let by_id: BTreeMap<EffectId, EffectRecord> = records
            .into_iter()
            .map(|record| (record.id, record))
            .collect();
        Self::describing(log, key, first, Records::ById(by_id))
    }

    /// `key`'s records in the recorder's observed serve order. An ID may be
    /// reserved by a dispatch future long before that future is polled.
    fn records_of(log: &EffectLog, key: &HandlerKey) -> Vec<EffectRecord> {
        log.iter()
            .filter(|record| &record.key == key)
            .cloned()
            .collect()
    }

    fn describing(
        log: &EffectLog,
        key: &HandlerKey,
        first: Option<EffectRecord>,
        records: Records,
    ) -> Result<Self, ErrorReport> {
        Self::check_header(log)?;
        // A replayer supplies recorded data beneath the application's layers.
        // Preserve the recorded family (including model identity/capabilities),
        // but let the caller reapply executable middleware.
        let (family, described) = if let Some(installed) = log
            .header
            .handlers
            .iter()
            .find(|installed| &installed.key == key)
        {
            (installed.family.family(), installed.family.clone())
        } else if let Some(first) = first {
            (first.kind.family(), describe(key, &first.kind, log))
        } else {
            let family = std::iter::once(&log.header.required)
                .chain(log.header.programs.values().map(|program| &program.required))
                .find_map(|row| row.get(key)).copied().ok_or_else(|| {
                    ErrorReport::new(ErrorKind::HandlerUnavailable, format!(
                        "`{key}` has no records in the log, no entry in its handler table and no place in its required row: nothing describes it"
                    ))
                })?;
            (family, describe_required(key, family, log)?)
        };
        let descriptor = HandlerDescriptor {
            key: key.clone(),
            family: described,
            layers: Vec::new(),
        };
        Ok(Self {
            key: key.clone(),
            family,
            descriptor,
            records: Mutex::new(records),
            stream_errors: log
                .header
                .stream_errors
                .iter()
                .filter(|(id, _)| {
                    log.records
                        .iter()
                        .any(|record| record.id == **id && &record.key == key)
                })
                .map(|(id, errors)| (*id, errors.clone()))
                .collect(),
            check: RequestCheck::Payload,
            refusals: None,
        })
    }

    /// The same replayer comparing requests as `check` says.
    #[must_use = "the setting applies to the returned value"]
    pub fn checking(mut self, check: RequestCheck) -> Self {
        self.check = check;
        self
    }

    /// Also signal newly generated request/publication refusals to a delivery
    /// scheduler. Recorded error outcomes never signal a refusal.
    #[must_use = "the setting applies to the returned value"]
    pub fn reporting_refusals(mut self, refusals: ReplayRefusals) -> Self {
        self.refusals = Some(refusals);
        self
    }

    fn refuse(&self, report: ErrorReport) -> ErrorReport {
        if let Some(refusals) = &self.refusals {
            refusals.report(&report);
        }
        report
    }

    /// The mode this replayer compares requests in.
    pub const fn check(&self) -> RequestCheck {
        self.check
    }

    /// Build replayers in record first-appearance order, followed by missing keys
    /// from the required and scoped program rows. Returns an error for invalid
    /// headers or keys that cannot be described.
    pub fn for_log(log: &EffectLog) -> Result<Vec<Self>, ErrorReport> {
        Self::check_header(log)?;
        Self::keys_of(log)
            .iter()
            .map(|key| Self::for_key(log, key))
            .collect()
    }

    /// [`for_log`](Self::for_log) with every replayer answering by id.
    pub fn for_log_by_id(log: &EffectLog) -> Result<Vec<Self>, ErrorReport> {
        Self::check_header(log)?;
        Self::keys_of(log)
            .iter()
            .map(|key| Self::for_key_by_id(log, key))
            .collect()
    }

    fn keys_of(log: &EffectLog) -> Vec<HandlerKey> {
        let mut keys: Vec<HandlerKey> = Vec::new();
        for record in log {
            if !keys.contains(&record.key) {
                keys.push(record.key.clone());
            }
        }
        for key in std::iter::once(&log.header.required)
            .chain(
                log.header
                    .programs
                    .values()
                    .map(|program| &program.required),
            )
            .flat_map(|row| row.keys())
        {
            if !keys.contains(key) {
                keys.push(key.clone());
            }
        }
        keys
    }

    /// Validate stream error positions, consistent key families and descriptors,
    /// and descriptor coverage for scoped programs. Returns an error for invalid
    /// or conflicting metadata.
    pub fn check_header(log: &EffectLog) -> Result<(), ErrorReport> {
        for (id, errors) in &log.header.stream_errors {
            let events = log
                .records
                .iter()
                .find(|record| record.id == *id && record.kind.streams())
                .and_then(|record| record.events.as_ref())
                .ok_or_else(|| {
                    ErrorReport::new(
                        ErrorKind::Divergence,
                        format!("stream errors for {id} require a kept stream record"),
                    )
                })?;
            let total = events.len().checked_add(errors.len()).ok_or_else(|| {
                ErrorReport::new(ErrorKind::Divergence, "stream item count overflow")
            })?;
            if errors.iter().any(|error| error.item >= total)
                || errors
                    .windows(2)
                    .any(|pair| matches!(pair, [first, second] if first.item >= second.item))
            {
                return Err(ErrorReport::new(
                    ErrorKind::Divergence,
                    format!("invalid stream error positions for {id}"),
                ));
            }
        }
        let mut families = BTreeMap::new();
        let rows = std::iter::once(&log.header.signature)
            .chain(std::iter::once(&log.header.required))
            .chain(
                log.header
                    .programs
                    .values()
                    .map(|program| &program.required),
            );
        let entries = rows
            .flat_map(|row| row.into_iter().map(|(key, family)| (key, *family)))
            .chain(
                log.header
                    .handlers
                    .iter()
                    .map(|descriptor| (&descriptor.key, descriptor.family.family())),
            )
            .chain(
                log.records
                    .iter()
                    .map(|record| (&record.key, record.kind.family())),
            );
        for (key, family) in entries {
            if let Some(previous) = families.insert(key, family)
                && previous != family
            {
                return Err(ErrorReport::new(
                    ErrorKind::Internal,
                    format!(
                        "replay refused: conflicting families for `{key}`: {previous} and {family}"
                    ),
                ));
            }
        }
        let mut descriptors = BTreeMap::new();
        for descriptor in &log.header.handlers {
            if let Some(previous) = descriptors.insert(&descriptor.key, descriptor)
                && previous != descriptor
            {
                return Err(ErrorReport::new(
                    ErrorKind::Internal,
                    format!(
                        "replay refused: conflicting descriptors for `{}`",
                        descriptor.key
                    ),
                ));
            }
        }
        for (scope, program) in &log.header.programs {
            for key in program.required.keys() {
                if !descriptors.contains_key(key) {
                    return Err(ErrorReport::new(
                        ErrorKind::HandlerUnavailable,
                        format!(
                            "replay refused: scope `{scope}` requires `{key}` but its recorded descriptor is missing"
                        ),
                    ));
                }
            }
        }
        Ok(())
    }

    /// The key this replayer serves.
    pub fn key(&self) -> &HandlerKey {
        &self.key
    }

    /// Records not yet replayed.
    pub fn remaining(&self) -> usize {
        self.records
            .lock()
            .unwrap_or_else(PoisonError::into_inner)
            .len()
    }
}

/// [`divergence`] under `check`: by payload, or by the stable hashes of
/// the two payloads, reported as the pair.
fn divergence_under(
    check: RequestCheck,
    recorded: &EffectKind,
    got: &EffectKind,
) -> Option<String> {
    let (recorded, got) = (&with_canonical_args(recorded), &with_canonical_args(got));
    match check {
        RequestCheck::Payload => divergence(recorded, got),
        RequestCheck::Hash => {
            let (Ok(recorded), Ok(got)) = (stable_hash(recorded), stable_hash(got)) else {
                return Some("the payload could not be hashed".to_owned());
            };
            (recorded != got)
                .then(|| format!("hash {recorded:#018x} was recorded, {got:#018x} arrived"))
        }
    }
}

/// The effect with a tool call's arguments in canonical key order, so a
/// replay does not diverge on key order alone.
fn with_canonical_args(kind: &EffectKind) -> EffectKind {
    let mut kind = kind.clone();
    if let EffectKind::ToolCall { args, .. } = &mut kind {
        *args = canonical_tool_args(args);
    }
    kind
}

/// Return a diagnostic for a request mismatch or serialization failure, or
/// `None` when the serialized requests match.
fn divergence(recorded: &EffectKind, got: &EffectKind) -> Option<String> {
    if recorded.family() != got.family() {
        return Some(format!(
            "family {:?} was recorded, {:?} arrived",
            recorded.family(),
            got.family()
        ));
    }
    if let (
        EffectKind::ToolCall {
            name: recorded_name,
            args: recorded_args,
            ..
        },
        EffectKind::ToolCall { name, args, .. },
    ) = (recorded, got)
    {
        if recorded_name != name {
            return Some(format!(
                "tool `{recorded_name}` was recorded, `{name}` arrived"
            ));
        }
        if recorded_args != args {
            return Some(format!(
                "arguments differ for `{name}`: recorded `{recorded_args}`, arrived `{args}`"
            ));
        }
        // Compare remaining serialized fields too; live tool context travels
        // beside the sink and is intentionally excluded.
    }
    let (Ok(recorded), Ok(got)) = (serde_json::to_value(recorded), serde_json::to_value(got))
    else {
        return Some("the payload could not be compared".to_owned());
    };
    if recorded == got {
        return None;
    }
    Some(first_difference(&recorded, &got, "payload"))
}

/// The path of the first differing field between two serialized payloads.
fn first_difference(recorded: &serde_json::Value, got: &serde_json::Value, path: &str) -> String {
    match (recorded, got) {
        (serde_json::Value::Object(recorded), serde_json::Value::Object(got)) => {
            let mut keys: Vec<&String> = recorded.keys().chain(got.keys()).collect();
            keys.sort();
            keys.dedup();
            for key in keys {
                match (recorded.get(key), got.get(key)) {
                    (Some(a), Some(b)) if a == b => {}
                    (Some(a), Some(b)) => return first_difference(a, b, &format!("{path}.{key}")),
                    (Some(_), None) => {
                        return format!("{path}.{key} was recorded but did not arrive");
                    }
                    (None, Some(_)) => return format!("{path}.{key} arrived but was not recorded"),
                    (None, None) => {}
                }
            }
            format!("{path} differs")
        }
        (serde_json::Value::Array(recorded), serde_json::Value::Array(got)) => {
            if recorded.len() != got.len() {
                return format!(
                    "{path} has {} recorded elements, {} arrived",
                    recorded.len(),
                    got.len()
                );
            }
            for (index, (a, b)) in recorded.iter().zip(got).enumerate() {
                if a != b {
                    return first_difference(a, b, &format!("{path}[{index}]"));
                }
            }
            format!("{path} differs")
        }
        _ => format!("{path} differs: recorded `{recorded}`, arrived `{got}`"),
    }
}

/// Return a recorded or inferred descriptor for an undispatched required key.
/// Returns an error when the family needs unavailable metadata or a tool has no
/// advertised definition.
fn describe_required(
    key: &HandlerKey,
    family: EffectFamily,
    log: &EffectLog,
) -> Result<FamilyDescriptor, ErrorReport> {
    if let Some(installed) = log
        .header
        .handlers
        .iter()
        .find(|descriptor| &descriptor.key == key && descriptor.family.family() == family)
    {
        return Ok(installed.family.clone());
    }
    let gap = |what: &str| {
        ErrorReport::new(
            ErrorKind::HandlerUnavailable,
            format!(
                "the required key `{key}` ({family}) cannot be described: {what}; the log's handler table has no entry for it"
            ),
        )
    };
    match family {
        EffectFamily::Tool => {
            let parts = key.parts();
            let name = match parts.kind.as_deref() {
                Some("tool") => parts.label.as_ref(),
                _ => return Err(gap("the key does not name a tool")),
            };
            let advertised = advertised_tool(name, log)
                .ok_or_else(|| gap("no recorded request advertises the tool"))?;
            Ok(FamilyDescriptor::Tool {
                name: advertised.name,
                description: advertised.description,
                parameters: advertised.parameters,
                embedding: None,
            })
        }
        EffectFamily::Completion => Ok(FamilyDescriptor::Completion {
            model: ModelRef::new(format!("replay:{key}")),
            capabilities: ProviderCapabilities::default(),
        }),
        EffectFamily::Memory => Ok(FamilyDescriptor::Memory {}),
        EffectFamily::Retrieve => Ok(FamilyDescriptor::Retrieve {}),
        // These families require modality, document limits, or custom labels
        // absent from the effect row.
        EffectFamily::Embed | EffectFamily::Rerank | EffectFamily::Custom => Err(gap(
            "a descriptor of this family is not derivable from the row",
        )),
    }
}

/// The definition of the tool `name` as some completion request in `log`
/// advertised it.
fn advertised_tool(name: &str, log: &EffectLog) -> Option<rig_core::completion::ToolDefinition> {
    log.iter().find_map(|record| match &record.kind {
        EffectKind::Completion { request, .. } => {
            request.tools.iter().find(|tool| tool.name == name).cloned()
        }
        _ => None,
    })
}

fn describe(key: &HandlerKey, kind: &EffectKind, log: &EffectLog) -> FamilyDescriptor {
    match kind {
        EffectKind::Completion { .. } => FamilyDescriptor::Completion {
            model: ModelRef::new(format!("replay:{key}")),
            capabilities: ProviderCapabilities::default(),
        },
        EffectKind::ToolCall { name, .. } => match advertised_tool(name, log) {
            Some(tool) => FamilyDescriptor::Tool {
                name: tool.name,
                description: tool.description,
                parameters: tool.parameters,
                embedding: None,
            },
            None => FamilyDescriptor::Tool {
                name: name.clone(),
                description: format!("replayed from the effect log under `{key}`"),
                parameters: serde_json::json!({"type": "object"}),
                embedding: None,
            },
        },
        EffectKind::Embed { inputs } => FamilyDescriptor::Embed {
            model: format!("replay:{key}"),
            dims: None,
            max_documents: usize::MAX,
            modality: match inputs {
                rig_core::effect::EmbedInputs::Texts(_) => EmbedModality::Text,
                rig_core::effect::EmbedInputs::Images(_) => EmbedModality::Image,
            },
        },
        EffectKind::Rerank { .. } => FamilyDescriptor::Rerank {
            model: format!("replay:{key}"),
            max_documents: usize::MAX,
        },
        EffectKind::Memory { .. } => FamilyDescriptor::Memory {},
        EffectKind::Retrieve { .. } => FamilyDescriptor::Retrieve {},
        EffectKind::Custom { .. } => FamilyDescriptor::Custom {
            kind: kind.name().to_owned(),
        },
    }
}

impl Serve for EffectLogReplayer {
    /// A replayer answers whatever its log holds.
    type Family = rig_core::effect::family::Dynamic;

    fn descriptor(&self) -> HandlerDescriptor {
        self.descriptor.clone()
    }

    async fn serve(&self, kind: EffectKind, dispatch: Dispatch) -> Reply {
        let (next, missing) = {
            let mut records = self.records.lock().unwrap_or_else(PoisonError::into_inner);
            match &mut *records {
                Records::ByPosition(records) => (
                    records.pop_front(),
                    format!(
                        "replay divergence: `{}` received a `{}` dispatch after its log ran out",
                        self.key,
                        kind.name()
                    ),
                ),
                Records::ById(records) => (
                    records.remove(&dispatch.id()),
                    format!(
                        "replay divergence: `{}` received a `{}` dispatch as {}, and the log has no record of that id",
                        self.key,
                        kind.name(),
                        dispatch.id()
                    ),
                ),
            }
        };
        {
            let outcome = match next {
                None => Err(self.refuse(ErrorReport::new(ErrorKind::Divergence, missing))),
                Some(record) => match divergence_under(self.check, &record.kind, &kind) {
                    Some(what) => Err(self.refuse(ErrorReport::new(
                        ErrorKind::Divergence,
                        format!(
                            "replay divergence: `{}` recorded {} ({}) but received {}: {what}",
                            self.key,
                            record.kind.name(),
                            record.id,
                            kind.name()
                        ),
                    ))),
                    None => {
                        if let Some(output) = record.tool_output {
                            let Some(published) =
                                dispatch.scope::<rig_core::tool::PublishedContext>()
                            else {
                                return Reply::Outcome(Err(self.refuse(ErrorReport::new(
                                    ErrorKind::Divergence,
                                    "replay requires a tool-result publication slot",
                                ))));
                            };
                            let context = dispatch
                                .scope::<rig_core::tool::ToolContext>()
                                .map(|context| context.for_dispatch())
                                .unwrap_or_default();
                            published.publish(context.with_result_context(output));
                        }
                        // Preserve original item positions, including items after a terminal.
                        // Append only failures not reproduced by kept items or EOF.
                        if let (Some(events), true) = (record.events, dispatch.is_stream()) {
                            let errors = self
                                .stream_errors
                                .get(&record.id)
                                .cloned()
                                .unwrap_or_default();
                            let mut tap = rig_core::serve::StreamTap::new();
                            let folded = events
                                .iter()
                                .any(|event| tap.observe(&Ok(event.clone())).is_some());
                            let fallback = match record.outcome {
                                Err(error)
                                    if errors.is_empty()
                                        && !folded
                                        && error != rig_core::serve::stream_truncated() =>
                                {
                                    Some(error)
                                }
                                Ok(_) | Err(_) => None,
                            };
                            let total = events.len() + errors.len();
                            let mut errors = errors.into_iter().peekable();
                            let mut events = events.into_iter();
                            let items = (0..total)
                                .filter_map(move |position| {
                                    if errors.peek().is_some_and(|error| error.item == position) {
                                        errors.next().map(|error| Err(error.error))
                                    } else {
                                        events.next().map(Ok)
                                    }
                                })
                                .chain(fallback.map(Err));
                            return Reply::Stream(Box::pin(futures::stream::iter(items)));
                        }
                        record.outcome
                    }
                },
            };
            debug_assert_eq!(self.family, self.descriptor.family.family());
            Reply::Outcome(outcome)
        }
    }
}
