//! Together AI API client and Rig integration
//!
//! # Example
//! ```
//! use rig::providers::together_ai;
//!
//! let client = together_ai::Client::new("YOUR_API_KEY");
//!
//! let together_embedding_model = client.embedding_model(together_ai::EMBEDDING_V1);
//! ```

pub mod client;
pub mod completion;
pub mod embedding;
pub mod streaming;

pub use client::Client;
pub use completion::{
    ALPACA_7B, CHRONOS_HERMES_13B, CODE_LLAMA_7B_INSTRUCT_TOGETHER, CODE_LLAMA_13B_INSTRUCT,
    CODE_LLAMA_13B_INSTRUCT_TOGETHER, CODE_LLAMA_34B_INSTRUCT, CODE_LLAMA_34B_INSTRUCT_TOGETHER,
    CODE_LLAMA_70B_INSTRUCT, DBRX_INSTRUCT, DEEPSEEK_CODER_33B_INSTRUCT, DEEPSEEK_LLM_67B_CHAT,
    DOLPHIN_2_5_MIXTRAL_8X7B, GEMMA_2_9B_IT, GEMMA_2_27B_IT, GEMMA_2B_IT, GEMMA_7B_IT, GUANACO_7B,
    GUANACO_13B, GUANACO_33B, GUANACO_65B, HERMES_2_THETA_LLAMA_3_70B, KOALA_7B, KOALA_13B,
    LLAMA_2_7B_CHAT, LLAMA_2_7B_CHAT_TOGETHER, LLAMA_2_13B_CHAT, LLAMA_2_13B_CHAT_TOGETHER,
    LLAMA_2_70B_CHAT_TOGETHER, LLAMA_3_1_8B_INSTRUCT_REFERENCE, LLAMA_3_1_8B_INSTRUCT_TURBO,
    LLAMA_3_1_70B_INSTRUCT_REFERENCE, LLAMA_3_1_70B_INSTRUCT_TURBO,
    LLAMA_3_1_405B_INSTRUCT_LITE_PRO, LLAMA_3_1_405B_INSTRUCT_TURBO, LLAMA_3_2_3B_INSTRUCT_TURBO,
    LLAMA_3_2_11B_VISION_INSTRUCT_TURBO, LLAMA_3_2_90B_VISION_INSTRUCT_TURBO, LLAMA_3_8B_CHAT_HF,
    LLAMA_3_8B_CHAT_HF_INT4, LLAMA_3_8B_CHAT_HF_INT8, LLAMA_3_8B_INSTRUCT,
    LLAMA_3_8B_INSTRUCT_LITE, LLAMA_3_8B_INSTRUCT_TURBO, LLAMA_3_70B_CHAT_HF, LLAMA_3_70B_INSTRUCT,
    LLAMA_3_70B_INSTRUCT_GRADIENT_1048K, LLAMA_3_70B_INSTRUCT_LITE, LLAMA_3_70B_INSTRUCT_TURBO,
    LLAMA_VISION_FREE, LLAVA_NEXT_MISTRAL_7B, MISTRAL_7B_INSTRUCT_V0_1, MISTRAL_7B_INSTRUCT_V0_2,
    MISTRAL_7B_INSTRUCT_V0_3, MIXTRAL_8X7B_INSTRUCT_V0_1, MIXTRAL_8X22B_INSTRUCT_V0_1, ML318BR,
    MYTHOMAX_L2_13B, MYTHOMAX_L2_13B_LITE, NOUS_CAPYBARA_V1_9, NOUS_HERMES_2_MISTRAL_DPO,
    NOUS_HERMES_2_MIXTRAL_8X7B_DPO, NOUS_HERMES_2_MIXTRAL_8X7B_SFT, NOUS_HERMES_LLAMA2_7B,
    NOUS_HERMES_LLAMA2_13B, NOUS_HERMES_LLAMA2_70B, OLMO_7B_INSTRUCT, OPENCHAT_3_5,
    OPENHERMES_2_5_MISTRAL_7B, OPENHERMES_2_MISTRAL_7B, OPENORCA_MISTRAL_7B_8K,
    PLATYPUS2_70B_INSTRUCT, QWEN_2_1_5B_INSTRUCT, QWEN_2_7B_INSTRUCT, QWEN_2_72B_INSTRUCT,
    QWEN1_5_0_5B_CHAT, QWEN1_5_1_8B_CHAT, QWEN1_5_4B_CHAT, QWEN1_5_7B_CHAT, QWEN1_5_14B_CHAT,
    QWEN1_5_32B_CHAT, QWEN1_5_72B_CHAT, QWEN1_5_110B_CHAT, QWEN2_5_7B_INSTRUCT_TURBO,
    QWEN2_5_72B_INSTRUCT_TURBO, REMM_SLERP_L2_13B, SNORKEL_MISTRAL_PAIRRM_DPO,
    SNOWFLAKE_ARCTIC_INSTRUCT, SOLAR_10_7B_INSTRUCT_V1, SOLAR_10_7B_INSTRUCT_V1_INT4, TOPPY_M_7B,
    VICUNA_7B_V1_3, VICUNA_7B_V1_5, VICUNA_13B_V1_3, VICUNA_13B_V1_5, VICUNA_13B_V1_5_16K,
    WIZARDLM_2_8X22B, WIZARDLM_13B_V1_2, YI_34B_CHAT, ZEPHYR_7B_BETA,
};
pub use embedding::{
    BERT_BASE_UNCASED, BGE_BASE_EN_V1_5, BGE_LARGE_EN_V1_5, M2_BERT_2K_RETRIEVAL_ENCODER_V1,
    M2_BERT_80M_2K_RETRIEVAL, M2_BERT_80M_8K_RETRIEVAL, M2_BERT_80M_32K_RETRIEVAL, SENTENCE_BERT,
    UAE_LARGE_V1,
};
