//! Module defining tool related structs and traits.
//!
//! The [Tool] trait defines a simple interface for creating tools that can be used
//! by [Agents](crate::agent::Agent).
//!
//! The [ToolEmbedding] trait extends the [Tool] trait to allow for tools that can be
//! stored in a vector store and RAGged.
//!
//! The [ToolSet] struct is a collection of tools that can be used by an [Agent](crate::agent::Agent)
//! and optionally RAGged.
//!
//! # Structured tool results
//!
//! A tool call resolves to a structured [`ToolExecutionResult`] — model-visible
//! output, a machine-readable [`ToolOutcome`] (success, a classified
//! [`ToolFailure`], skipped, or denied), and [`ToolResultExtensions`] metadata
//! that is never sent to the model. This is what flows to the
//! [`StepEvent::ToolResult`](crate::agent::StepEvent::ToolResult) hook so a
//! policy can steer on *why* a tool failed without parsing strings. A tool
//! classifies its own error type via [`Tool::classify_error`] and can return
//! richer outcomes/metadata via [`Tool::call_structured`] and [`ToolReturn`].

mod extensions;
mod result;
pub mod server;

pub use extensions::{MissingExtension, ToolCallExtensions, ToolResultExtensions};
pub use result::{
    ToolExecutionResult, ToolFailure, ToolFailureKind, ToolOutcome, ToolReturn, ToolReturnOutcome,
};
use std::collections::HashMap;
use std::fmt;
use std::sync::Arc;

use futures::Future;
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};

use crate::{
    completion::{self, ToolDefinition},
    embeddings::{embed::EmbedError, tool::ToolSchema},
    wasm_compat::{WasmBoxedFuture, WasmCompatSend, WasmCompatSync},
};

#[derive(Debug, thiserror::Error)]
pub enum ToolError {
    #[cfg(not(target_family = "wasm"))]
    /// Error returned by the tool
    ToolCallError(#[from] Box<dyn std::error::Error + Send + Sync>),

    #[cfg(target_family = "wasm")]
    /// Error returned by the tool
    ToolCallError(#[from] Box<dyn std::error::Error>),
    /// Error caused by a de/serialization fail
    JsonError(#[from] serde_json::Error),
}

impl fmt::Display for ToolError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ToolError::ToolCallError(e) => {
                let error_str = e.to_string();
                // This is required due to being able to use agents as tools
                // which means it is possible to get recursive tool call errors
                if error_str.starts_with("ToolCallError: ") {
                    write!(f, "{}", error_str)
                } else {
                    write!(f, "ToolCallError: {}", error_str)
                }
            }
            ToolError::JsonError(e) => write!(f, "JsonError: {e}"),
        }
    }
}

/// Trait that represents a simple LLM tool.
///
/// Tool authors provide flat metadata (`NAME`, [`description`](Self::description),
/// and [`parameters`](Self::parameters)). Provider-facing [`ToolDefinition`]s are
/// generated by Rig when tools are registered in an agent request.
///
/// # Example
/// ```
/// use rig_core::tool::{Tool, ToolSet};
///
/// #[derive(serde::Deserialize)]
/// struct AddArgs {
///     x: i32,
///     y: i32,
/// }
///
/// #[derive(Debug, thiserror::Error)]
/// #[error("Math error")]
/// struct MathError;
///
/// #[derive(serde::Deserialize, serde::Serialize)]
/// struct Adder;
///
/// impl Tool for Adder {
///     const NAME: &'static str = "add";
///
///     type Error = MathError;
///     type Args = AddArgs;
///     type Output = i32;
///
///     fn description(&self) -> String {
///         "Add x and y together".to_string()
///     }
///
///     fn parameters(&self) -> serde_json::Value {
///         serde_json::json!({
///             "type": "object",
///             "properties": {
///                 "x": {
///                     "type": "number",
///                     "description": "The first number to add"
///                 },
///                 "y": {
///                     "type": "number",
///                     "description": "The second number to add"
///                 }
///             }
///         })
///     }
///
///     async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
///         let result = args.x + args.y;
///         Ok(result)
///     }
/// }
/// ```
///
/// `Tool::NAME` is the only typed tool-name source; tools do not expose a
/// runtime name getter:
///
/// ```compile_fail
/// # use rig_core::tool::Tool;
/// # #[derive(Debug, thiserror::Error)] #[error("err")] struct E;
/// # struct Noop;
/// # impl Tool for Noop {
/// #   const NAME: &'static str = "noop";
/// #   type Error = E;
/// #   type Args = ();
/// #   type Output = ();
/// #   fn description(&self) -> String { String::new() }
/// #   fn parameters(&self) -> serde_json::Value { serde_json::json!({}) }
/// #   async fn call(&self, _args: Self::Args) -> Result<Self::Output, Self::Error> { Ok(()) }
/// # }
/// let _ = Noop.name();
/// ```
pub trait Tool: Sized + WasmCompatSend + WasmCompatSync {
    /// The name of the tool. This name should be unique within a single
    /// [`ToolSet`] or other registration scope that dispatches tools by name.
    const NAME: &'static str;

    /// The error type of the tool.
    type Error: std::error::Error + WasmCompatSend + WasmCompatSync + 'static;
    /// The arguments type of the tool.
    type Args: for<'a> Deserialize<'a> + WasmCompatSend + WasmCompatSync;
    /// The output type of the tool.
    type Output: Serialize;

    /// Model-facing description of what the tool does.
    fn description(&self) -> String;

    /// JSON Schema for the tool arguments.
    fn parameters(&self) -> serde_json::Value;

    /// The tool execution method.
    /// Both the arguments and return value are a String since these values are meant to
    /// be the output and input of LLM models (respectively)
    fn call(
        &self,
        args: Self::Args,
    ) -> impl Future<Output = Result<Self::Output, Self::Error>> + WasmCompatSend;

    /// Tool execution with per-call runtime extensions.
    ///
    /// Override this to access runtime values (auth, session IDs, etc.)
    /// injected by the caller via [`ToolCallExtensions`]. The default ignores
    /// the extensions and delegates to [`Tool::call`].
    ///
    /// **Override contract:** the default [`Tool::call_structured`] delegates
    /// here, so overriding this method is how you read extensions for the common
    /// case — the agent loop drives [`call_structured`](Self::call_structured),
    /// which reaches your override (with an empty [`ToolCallExtensions`] when no
    /// caller supplied one). Under dynamic dispatch this then becomes the single
    /// execution entry point (`call`'s body is unreachable that way; a direct
    /// `Tool::call` still runs it), so put your logic here and treat a missing
    /// value as the no-extensions case (e.g. [`ToolCallExtensions::get`]
    /// returning `None`). If you *also* override
    /// [`call_structured`](Self::call_structured), that override supersedes this
    /// method on the agent's structured path — put your logic there instead.
    fn call_with_extensions(
        &self,
        args: Self::Args,
        _extensions: &ToolCallExtensions,
    ) -> impl Future<Output = Result<Self::Output, Self::Error>> + WasmCompatSend {
        self.call(args)
    }

    /// Classify an error returned by this tool into a structured [`ToolFailure`].
    ///
    /// This is how a tool's own error type reaches a hook, policy, or telemetry
    /// pipeline as a machine-readable [`ToolFailureKind`] — with no string
    /// parsing. The default classifies every error as
    /// [`ToolFailureKind::Other`] with the error's `Display` as the message;
    /// override it to map your error variants onto the standard kinds (timeout,
    /// not-found, rate-limited, …) and attach a `code` / `http_status` /
    /// `retryable` hint:
    ///
    /// ```rust,ignore
    /// fn classify_error(&self, error: &Self::Error) -> ToolFailure {
    ///     match error {
    ///         MyError::Timeout => ToolFailure::timeout(error.to_string()),
    ///         MyError::Http { status: 404, .. } => {
    ///             ToolFailure::not_found(error.to_string()).with_http_status(404)
    ///         }
    ///         other => ToolFailure::other(other.to_string()),
    ///     }
    /// }
    /// ```
    fn classify_error(&self, error: &Self::Error) -> ToolFailure {
        ToolFailure::other(error.to_string())
    }

    /// Execute the tool, returning a structured [`ToolReturn`] instead of a bare
    /// output.
    ///
    /// The richest tool-execution entry point. The default calls
    /// [`call_with_extensions`](Self::call_with_extensions) and wraps the output
    /// as a plain [`ToolReturn::success`] with no metadata, so a tool that only
    /// implements [`call`](Self::call) needs nothing extra. Override it to:
    ///
    /// - attach result metadata to a success
    ///   (`ToolReturn::success(out).with_extension(..)`);
    /// - report a handled failure that still shows output to the model
    ///   ([`ToolReturn::failed`]);
    /// - mark the call [`denied`](ToolReturn::denied) — the tool refused it (a
    ///   framework hook `Flow::Skip` is what yields a *skipped* outcome, not the tool).
    ///
    /// **Override contract:** this is the single entry point under *structured
    /// dynamic dispatch* — the agent loop routes every tool call here through
    /// Rig's erased runtime adapter. If you override it, the `call` /
    /// `call_with_extensions` bodies are unreachable on that structured path (a
    /// direct call still runs them), so put your logic here. A returned
    /// `Err(Self::Error)` is still classified via
    /// [`classify_error`](Self::classify_error).
    fn call_structured(
        &self,
        args: Self::Args,
        extensions: &ToolCallExtensions,
    ) -> impl Future<Output = Result<ToolReturn<Self::Output>, Self::Error>> + WasmCompatSend {
        async move {
            self.call_with_extensions(args, extensions)
                .await
                .map(ToolReturn::success)
        }
    }
}

/// Trait that represents an LLM tool that can be stored in a vector store and RAGged
pub trait ToolEmbedding: Tool {
    /// Error returned when reconstructing a dynamic tool from stored context.
    type InitError: std::error::Error + WasmCompatSend + WasmCompatSync + 'static;

    /// Type of the tool' context. This context will be saved and loaded from the
    /// vector store when ragging the tool.
    /// This context can be used to store the tool's static configuration and local
    /// context.
    type Context: for<'a> Deserialize<'a> + Serialize;

    /// Type of the tool's state. This state will be passed to the tool when initializing it.
    /// This state can be used to pass runtime arguments to the tool such as clients,
    /// API keys and other configuration.
    type State: WasmCompatSend;

    /// A method returning the documents that will be used as embeddings for the tool.
    /// This allows for a tool to be retrieved from multiple embedding "directions".
    /// If the tool will not be RAGged, this method should return an empty vector.
    fn embedding_docs(&self) -> Vec<String>;

    /// A method returning the context of the tool.
    fn context(&self) -> Self::Context;

    /// A method to initialize the tool from the context, and a state.
    fn init(state: Self::State, context: Self::Context) -> Result<Self, Self::InitError>;
}

trait ToolMetadata<T>: Fn() -> T + WasmCompatSend + WasmCompatSync {}

impl<F, T> ToolMetadata<T> for F where F: Fn() -> T + WasmCompatSend + WasmCompatSync {}

type ToolMetadataFn<T> = Arc<dyn ToolMetadata<T>>;

trait ToolCallClosure:
    for<'a> Fn(String, &'a ToolCallExtensions) -> WasmBoxedFuture<'a, Result<String, ToolError>>
    + WasmCompatSend
    + WasmCompatSync
{
}

impl<F> ToolCallClosure for F where
    F: for<'a> Fn(String, &'a ToolCallExtensions) -> WasmBoxedFuture<'a, Result<String, ToolError>>
        + WasmCompatSend
        + WasmCompatSync
{
}

type ToolCallFn = Arc<dyn ToolCallClosure>;

trait ToolCallStructuredClosure:
    for<'a> Fn(String, &'a ToolCallExtensions) -> WasmBoxedFuture<'a, ToolExecutionResult>
    + WasmCompatSend
    + WasmCompatSync
{
}

impl<F> ToolCallStructuredClosure for F where
    F: for<'a> Fn(String, &'a ToolCallExtensions) -> WasmBoxedFuture<'a, ToolExecutionResult>
        + WasmCompatSend
        + WasmCompatSync
{
}

type ToolCallStructuredFn = Arc<dyn ToolCallStructuredClosure>;

fn serialize_tool_output(output: impl Serialize) -> serde_json::Result<String> {
    match serde_json::to_value(output)? {
        serde_json::Value::String(text) => Ok(text),
        value => Ok(value.to_string()),
    }
}

/// Deserialize JSON tool arguments, normalizing a bare `null` (which LLMs
/// frequently send for tools whose arguments are all optional) to `{}`.
fn parse_tool_args<A>(args: &str) -> serde_json::Result<A>
where
    A: for<'de> Deserialize<'de>,
{
    match serde_json::from_str(args) {
        Ok(parsed) => Ok(parsed),
        Err(err) if args.trim() == "null" => serde_json::from_str("{}").map_err(|_| err),
        Err(err) => Err(err),
    }
}

/// Map a [`ToolError`] surfaced by a string-returning dynamic tool path into a
/// structured [`ToolExecutionResult`], classifying a JSON error as invalid
/// arguments.
fn tool_error_to_execution_result(err: ToolError) -> ToolExecutionResult {
    let message = err.to_string();
    let failure = match err {
        ToolError::JsonError(_) => ToolFailure::invalid_args(message.clone()),
        ToolError::ToolCallError(_) => ToolFailure::other(message.clone()),
    };
    ToolExecutionResult::failed(message, failure)
}

/// Nameless erased runtime executor for a tool.
///
/// Tool identity is stored by [`ToolDyn`] and by [`ToolSet`] registration keys;
/// runtime implementations cannot recompute or change it.
pub(crate) trait ToolRuntime: WasmCompatSend + WasmCompatSync {
    /// Calls the tool with JSON-encoded arguments and returns model-facing text.
    fn call<'a>(&'a self, args: String) -> WasmBoxedFuture<'a, Result<String, ToolError>>;

    /// Dynamic dispatch variant of tool execution with per-call runtime extensions.
    fn call_with_extensions<'a>(
        &'a self,
        args: String,
        _extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        self.call(args)
    }

    /// Execute the tool with per-call extensions, returning a structured
    /// [`ToolExecutionResult`] (model output + [`ToolOutcome`] + result
    /// extensions).
    fn call_structured<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, ToolExecutionResult> {
        Box::pin(async move {
            match self.call_with_extensions(args, extensions).await {
                Ok(model_output) => ToolExecutionResult::success(model_output),
                Err(err) => tool_error_to_execution_result(err),
            }
        })
    }
}

/// Runtime assembled from [`ToolDynBuilder`] executor closures.
///
/// When only one executor is provided, the other path is derived from it: a
/// string executor gets the default structured classification, and a structured
/// executor maps a [`ToolOutcome::Success`] to `Ok(model_output)` and every
/// other outcome to a [`ToolError::ToolCallError`] carrying the model-facing
/// message.
enum ClosureRuntime {
    String(ToolCallFn),
    Structured(ToolCallStructuredFn),
    Both {
        call: ToolCallFn,
        structured: ToolCallStructuredFn,
    },
}

impl ToolRuntime for ClosureRuntime {
    fn call<'a>(&'a self, args: String) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        ToolRuntime::call_with_extensions(self, args, &ToolCallExtensions::EMPTY)
    }

    fn call_with_extensions<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        match self {
            Self::String(call) | Self::Both { call, .. } => call(args, extensions),
            Self::Structured(structured) => {
                let result = structured(args, extensions);
                Box::pin(async move {
                    let result = result.await;
                    match result.outcome() {
                        ToolOutcome::Success => Ok(result.model_output().to_string()),
                        _ => Err(ToolError::ToolCallError(
                            result.model_output().to_string().into(),
                        )),
                    }
                })
            }
        }
    }

    fn call_structured<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, ToolExecutionResult> {
        match self {
            Self::Structured(structured) | Self::Both { structured, .. } => {
                structured(args, extensions)
            }
            Self::String(call) => {
                let result = call(args, extensions);
                Box::pin(async move {
                    match result.await {
                        Ok(model_output) => ToolExecutionResult::success(model_output),
                        Err(err) => tool_error_to_execution_result(err),
                    }
                })
            }
        }
    }
}

#[derive(Clone)]
pub(crate) struct ToolEntry {
    description: ToolMetadataFn<String>,
    parameters: ToolMetadataFn<serde_json::Value>,
    runtime: Arc<dyn ToolRuntime>,
}

impl ToolEntry {
    fn new(
        description: impl Fn() -> String + WasmCompatSend + WasmCompatSync + 'static,
        parameters: impl Fn() -> serde_json::Value + WasmCompatSend + WasmCompatSync + 'static,
        runtime: Arc<dyn ToolRuntime>,
    ) -> Self {
        Self {
            description: Arc::new(description),
            parameters: Arc::new(parameters),
            runtime,
        }
    }

    fn description(&self) -> String {
        (self.description)()
    }

    fn parameters(&self) -> serde_json::Value {
        (self.parameters)()
    }

    fn call<'a>(&'a self, args: String) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        self.runtime.call(args)
    }

    fn call_with_extensions<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        self.runtime.call_with_extensions(args, extensions)
    }

    fn call_structured<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, ToolExecutionResult> {
        self.runtime.call_structured(args, extensions)
    }

    fn definition_with_name(&self, name: impl Into<String>) -> ToolDefinition {
        ToolDefinition {
            name: name.into(),
            description: self.description(),
            parameters: self.parameters(),
        }
    }
}

/// A complete named dynamic LLM tool.
///
/// `ToolDyn` stores its canonical name as data until registration. When a tool
/// is inserted into a [`ToolSet`], the name is consumed into the map key and the
/// stored runtime entry is nameless.
///
/// `ToolDyn` is a concrete value, not an object-safe trait to implement:
///
/// ```compile_fail
/// # use rig_core::tool::ToolDyn;
/// struct Manual;
/// impl ToolDyn for Manual {}
/// ```
#[derive(Clone)]
pub struct ToolDyn {
    name: String,
    entry: ToolEntry,
}

impl ToolDyn {
    /// Start building a concrete dynamic tool.
    pub fn builder() -> ToolDynBuilder {
        ToolDynBuilder::default()
    }

    pub(crate) fn from_runtime(
        name: impl Into<String>,
        description: impl Fn() -> String + WasmCompatSend + WasmCompatSync + 'static,
        parameters: impl Fn() -> serde_json::Value + WasmCompatSend + WasmCompatSync + 'static,
        runtime: Arc<dyn ToolRuntime>,
    ) -> Self {
        Self {
            name: name.into(),
            entry: ToolEntry::new(description, parameters, runtime),
        }
    }

    fn from_typed<T>(tool: T) -> Self
    where
        T: Tool + 'static,
    {
        let tool = Arc::new(tool);
        let description_tool = Arc::clone(&tool);
        let parameters_tool = Arc::clone(&tool);
        let runtime: Arc<dyn ToolRuntime> = tool;
        Self::from_runtime(
            T::NAME,
            move || description_tool.description(),
            move || parameters_tool.parameters(),
            runtime,
        )
    }

    fn into_parts(self) -> (String, ToolEntry) {
        (self.name, self.entry)
    }

    /// The canonical tool name stored in this value. At registration it is
    /// consumed into the [`ToolSet`] map key.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Replace the stored canonical name, returning the renamed tool.
    ///
    /// The name is plain data on this value; it is consumed into the [`ToolSet`]
    /// map key at registration and cannot change afterwards. Use this to
    /// register one implementation under an instance-specific name, or — since
    /// `ToolDyn` is `Clone` and shares its runtime — under several names:
    ///
    /// `ToolDyn::from(tool).with_name("alias")`, `tool_dyn.clone().with_name("other")`.
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.name = name.into();
        self
    }

    /// Model-facing description of what the tool does.
    pub fn description(&self) -> String {
        self.entry.description()
    }

    /// JSON Schema for the tool arguments.
    pub fn parameters(&self) -> serde_json::Value {
        self.entry.parameters()
    }

    /// Calls the tool with JSON-encoded arguments and returns model-facing text.
    pub fn call<'a>(&'a self, args: String) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        self.entry.call(args)
    }

    /// Calls the tool with JSON-encoded arguments and runtime extensions.
    pub fn call_with_extensions<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        self.entry.call_with_extensions(args, extensions)
    }

    /// Execute the tool, returning a structured [`ToolExecutionResult`].
    pub fn call_structured<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, ToolExecutionResult> {
        self.entry.call_structured(args, extensions)
    }

    fn definition_with_name(&self, name: impl Into<String>) -> ToolDefinition {
        self.entry.definition_with_name(name)
    }
}

impl<T> From<T> for ToolDyn
where
    T: Tool + 'static,
{
    fn from(tool: T) -> Self {
        Self::from_typed(tool)
    }
}

/// Converts typed or already-dynamic tools into a complete [`ToolDyn`] value.
pub trait IntoToolDyn {
    /// Convert into a concrete named dynamic tool.
    fn into_tool_dyn(self) -> ToolDyn;
}

impl<T> IntoToolDyn for T
where
    T: Tool + 'static,
{
    fn into_tool_dyn(self) -> ToolDyn {
        ToolDyn::from_typed(self)
    }
}

impl IntoToolDyn for ToolDyn {
    fn into_tool_dyn(self) -> ToolDyn {
        self
    }
}

/// Source that can produce a provider-facing [`ToolDefinition`].
///
/// Typed tools use `T::NAME`; concrete dynamic tools use their stored name.
pub trait ToolDefinitionSource {
    /// Build a provider-facing tool definition from this source.
    fn to_tool_definition(&self) -> ToolDefinition;
}

impl<T> ToolDefinitionSource for &T
where
    T: Tool,
{
    fn to_tool_definition(&self) -> ToolDefinition {
        ToolDefinition {
            name: T::NAME.to_string(),
            description: self.description(),
            parameters: self.parameters(),
        }
    }
}

impl ToolDefinitionSource for &ToolDyn {
    fn to_tool_definition(&self) -> ToolDefinition {
        self.definition_with_name(self.name.clone())
    }
}

/// Generate a provider-facing [`ToolDefinition`] from a typed or dynamic tool.
pub fn tool_definition(tool: impl ToolDefinitionSource) -> ToolDefinition {
    tool.to_tool_definition()
}

/// Builder for constructing a complete concrete [`ToolDyn`] value.
#[derive(Default)]
pub struct ToolDynBuilder {
    name: Option<String>,
    description: Option<ToolMetadataFn<String>>,
    parameters: Option<ToolMetadataFn<serde_json::Value>>,
    call: Option<ToolCallFn>,
    call_structured: Option<ToolCallStructuredFn>,
}

impl ToolDynBuilder {
    /// Set the canonical tool name stored in the dynamic tool value.
    pub fn name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }

    /// Set a fixed model-facing description.
    pub fn description(mut self, description: impl Into<String>) -> Self {
        let description = description.into();
        self.description = Some(Arc::new(move || description.clone()));
        self
    }

    /// Set a lazily generated model-facing description.
    pub fn description_fn(
        mut self,
        description: impl Fn() -> String + WasmCompatSend + WasmCompatSync + 'static,
    ) -> Self {
        self.description = Some(Arc::new(description));
        self
    }

    /// Set a fixed JSON Schema for the tool arguments.
    pub fn parameters(mut self, parameters: serde_json::Value) -> Self {
        self.parameters = Some(Arc::new(move || parameters.clone()));
        self
    }

    /// Set a lazily generated JSON Schema for the tool arguments.
    pub fn parameters_fn(
        mut self,
        parameters: impl Fn() -> serde_json::Value + WasmCompatSend + WasmCompatSync + 'static,
    ) -> Self {
        self.parameters = Some(Arc::new(parameters));
        self
    }

    /// Set a simple string-returning executor.
    pub fn call<F, Fut>(self, call: F) -> Self
    where
        F: Fn(String) -> Fut + WasmCompatSend + WasmCompatSync + 'static,
        Fut: Future<Output = Result<String, ToolError>> + WasmCompatSend + 'static,
    {
        self.call_with_extensions(move |args, _extensions| Box::pin(call(args)))
    }

    /// Set a string-returning executor that receives per-call extensions.
    pub fn call_with_extensions<F>(mut self, call: F) -> Self
    where
        F: for<'a> Fn(
                String,
                &'a ToolCallExtensions,
            ) -> WasmBoxedFuture<'a, Result<String, ToolError>>
            + WasmCompatSend
            + WasmCompatSync
            + 'static,
    {
        self.call = Some(Arc::new(call));
        self
    }

    /// Set a structured executor that returns a full [`ToolExecutionResult`],
    /// for outcomes the string executors cannot express —
    /// [`denied`](ToolExecutionResult::denied), or failures with a precise
    /// [`ToolFailureKind`] such as a real timeout.
    ///
    /// If no string executor is set, the string [`ToolDyn::call`] /
    /// [`ToolDyn::call_with_extensions`] paths are derived from this one: a
    /// [`ToolOutcome::Success`] yields `Ok(model_output)` and any other outcome
    /// yields a [`ToolError::ToolCallError`] carrying the model-facing message.
    /// If both executors are set, each drives its own path directly.
    pub fn call_structured<F>(mut self, call: F) -> Self
    where
        F: for<'a> Fn(String, &'a ToolCallExtensions) -> WasmBoxedFuture<'a, ToolExecutionResult>
            + WasmCompatSend
            + WasmCompatSync
            + 'static,
    {
        self.call_structured = Some(Arc::new(call));
        self
    }

    /// Build the dynamic tool, failing if any required metadata or executor is missing.
    pub fn build(self) -> Result<ToolDyn, ToolDynBuilderError> {
        let runtime: Arc<dyn ToolRuntime> = match (self.call, self.call_structured) {
            (Some(call), Some(structured)) => Arc::new(ClosureRuntime::Both { call, structured }),
            (Some(call), None) => Arc::new(ClosureRuntime::String(call)),
            (None, Some(structured)) => Arc::new(ClosureRuntime::Structured(structured)),
            (None, None) => return Err(ToolDynBuilderError::MissingRuntime),
        };

        Ok(ToolDyn {
            name: self.name.ok_or(ToolDynBuilderError::MissingName)?,
            entry: ToolEntry {
                description: self
                    .description
                    .ok_or(ToolDynBuilderError::MissingDescription)?,
                parameters: self
                    .parameters
                    .ok_or(ToolDynBuilderError::MissingParameters)?,
                runtime,
            },
        })
    }
}

/// Error returned when a [`ToolDynBuilder`] is missing required fields.
#[derive(Debug, thiserror::Error)]
pub enum ToolDynBuilderError {
    /// The builder did not receive a canonical tool name.
    #[error("dynamic tool is missing a name")]
    MissingName,
    /// The builder did not receive a model-facing description.
    #[error("dynamic tool is missing a description")]
    MissingDescription,
    /// The builder did not receive a JSON Schema for tool arguments.
    #[error("dynamic tool is missing parameters")]
    MissingParameters,
    /// The builder received neither a string executor ([`call`](ToolDynBuilder::call) /
    /// [`call_with_extensions`](ToolDynBuilder::call_with_extensions)) nor a
    /// structured executor ([`call_structured`](ToolDynBuilder::call_structured)).
    #[error("dynamic tool is missing an executor")]
    MissingRuntime,
}

impl<T> ToolRuntime for T
where
    T: Tool,
{
    fn call<'a>(&'a self, args: String) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        ToolRuntime::call_with_extensions(self, args, &ToolCallExtensions::EMPTY)
    }

    fn call_with_extensions<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, Result<String, ToolError>> {
        Box::pin(async move {
            match parse_tool_args::<T::Args>(&args) {
                Ok(args) => <Self as Tool>::call_with_extensions(self, args, extensions)
                    .await
                    .map_err(|e| ToolError::ToolCallError(Box::new(e)))
                    .and_then(|output| serialize_tool_output(output).map_err(ToolError::JsonError)),
                Err(e) => Err(ToolError::JsonError(e)),
            }
        })
    }

    fn call_structured<'a>(
        &'a self,
        args: String,
        extensions: &'a ToolCallExtensions,
    ) -> WasmBoxedFuture<'a, ToolExecutionResult> {
        Box::pin(async move {
            let parsed = match parse_tool_args::<T::Args>(&args) {
                Ok(parsed) => parsed,
                Err(err) => {
                    return ToolExecutionResult::failed(
                        format!("failed to parse tool arguments: {err}"),
                        ToolFailure::invalid_args(err.to_string()),
                    );
                }
            };
            match <Self as Tool>::call_structured(self, parsed, extensions).await {
                Ok(tool_return) => tool_return.into_execution_result(),
                Err(err) => {
                    let failure = self.classify_error(&err);
                    ToolExecutionResult::failed(err.to_string(), failure)
                }
            }
        })
    }
}

#[cfg(feature = "rmcp")]
#[cfg_attr(docsrs, doc(cfg(feature = "rmcp")))]
pub mod rmcp;

#[derive(Clone)]
pub(crate) struct ToolEmbeddingEntry {
    tool: ToolEntry,
    context: Arc<dyn ToolMetadata<serde_json::Result<serde_json::Value>>>,
    embedding_docs: Arc<dyn ToolMetadata<Vec<String>>>,
}

impl ToolEmbeddingEntry {
    fn definition_with_name(&self, name: impl Into<String>) -> ToolDefinition {
        self.tool.definition_with_name(name)
    }

    pub(crate) fn context(&self) -> serde_json::Result<serde_json::Value> {
        (self.context)()
    }

    pub(crate) fn embedding_docs(&self) -> Vec<String> {
        (self.embedding_docs)()
    }

    pub(crate) async fn call_with_extensions(
        &self,
        args: String,
        extensions: &ToolCallExtensions,
    ) -> Result<String, ToolError> {
        self.tool.call_with_extensions(args, extensions).await
    }

    pub(crate) async fn call_structured(
        &self,
        args: String,
        extensions: &ToolCallExtensions,
    ) -> ToolExecutionResult {
        self.tool.call_structured(args, extensions).await
    }
}

/// A complete named dynamic tool that can also be represented in a vector store.
#[derive(Clone)]
pub struct ToolEmbeddingDyn {
    name: String,
    entry: ToolEmbeddingEntry,
}

impl ToolEmbeddingDyn {
    fn from_typed<T>(tool: T) -> Self
    where
        T: ToolEmbedding + 'static,
    {
        let tool = Arc::new(tool);
        let description_tool = Arc::clone(&tool);
        let parameters_tool = Arc::clone(&tool);
        let context_tool = Arc::clone(&tool);
        let docs_tool = Arc::clone(&tool);
        let runtime: Arc<dyn ToolRuntime> = tool;
        let entry = ToolEmbeddingEntry {
            tool: ToolEntry::new(
                move || description_tool.description(),
                move || parameters_tool.parameters(),
                runtime,
            ),
            context: Arc::new(move || serde_json::to_value(context_tool.context())),
            embedding_docs: Arc::new(move || docs_tool.embedding_docs()),
        };

        Self {
            name: T::NAME.to_string(),
            entry,
        }
    }

    pub(crate) fn into_parts(self) -> (String, ToolEmbeddingEntry) {
        (self.name, self.entry)
    }

    /// The canonical tool name stored in this value. At registration it is
    /// consumed into the [`ToolSet`] map key.
    pub fn name(&self) -> &str {
        &self.name
    }

    pub(crate) fn context(&self) -> serde_json::Result<serde_json::Value> {
        self.entry.context()
    }

    pub(crate) fn embedding_docs(&self) -> Vec<String> {
        self.entry.embedding_docs()
    }
}

/// Converts typed embeddable tools or already-dynamic embeddable tools into a
/// complete [`ToolEmbeddingDyn`] value.
pub trait IntoToolEmbeddingDyn {
    /// Convert into a complete embeddable dynamic tool value.
    fn into_tool_embedding_dyn(self) -> ToolEmbeddingDyn;
}

impl<T> IntoToolEmbeddingDyn for T
where
    T: ToolEmbedding + 'static,
{
    fn into_tool_embedding_dyn(self) -> ToolEmbeddingDyn {
        ToolEmbeddingDyn::from_typed(self)
    }
}

impl IntoToolEmbeddingDyn for ToolEmbeddingDyn {
    fn into_tool_embedding_dyn(self) -> ToolEmbeddingDyn {
        self
    }
}

#[derive(Clone)]
pub(crate) enum ToolType {
    Simple(ToolEntry),
    Embedding(ToolEmbeddingEntry),
}

impl ToolType {
    pub fn definition_with_name(&self, name: impl Into<String>) -> ToolDefinition {
        match self {
            ToolType::Simple(tool) => tool.definition_with_name(name),
            ToolType::Embedding(tool) => tool.definition_with_name(name),
        }
    }

    pub async fn call_with_extensions(
        &self,
        args: String,
        extensions: &ToolCallExtensions,
    ) -> Result<String, ToolError> {
        match self {
            ToolType::Simple(tool) => tool.call_with_extensions(args, extensions).await,
            ToolType::Embedding(tool) => tool.call_with_extensions(args, extensions).await,
        }
    }

    /// Execute the tool, returning the structured [`ToolExecutionResult`].
    pub async fn call_structured(
        &self,
        args: String,
        extensions: &ToolCallExtensions,
    ) -> ToolExecutionResult {
        match self {
            ToolType::Simple(tool) => tool.call_structured(args, extensions).await,
            ToolType::Embedding(tool) => tool.call_structured(args, extensions).await,
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum ToolSetError {
    /// Error returned by the tool
    #[error("ToolCallError: {0}")]
    ToolCallError(#[from] ToolError),

    /// Could not find a tool
    #[error("ToolNotFoundError: {0}")]
    ToolNotFoundError(String),

    /// JSON serialization or deserialization failed while preparing tool data.
    #[error("JsonError: {0}")]
    JsonError(#[from] serde_json::Error),

    /// Tool call was interrupted. Primarily useful for agent multi-step/turn prompting.
    #[error("Tool call interrupted")]
    Interrupted,
}

/// A struct that holds a set of tools.
///
/// Tools are stored in an [`IndexMap`] keyed by name, so iteration
/// (definitions, documents, schemas) follows registration order and the tool
/// list sent to providers is deterministic across processes. Re-registering an
/// existing name replaces the implementation but keeps its original position.
#[derive(Default)]
pub struct ToolSet {
    pub(crate) tools: IndexMap<String, ToolType>,
}

impl ToolSet {
    /// Create a new ToolSet from a list of typed or dynamic tools.
    pub fn from_tools(tools: Vec<impl IntoToolDyn>) -> Self {
        let mut toolset = Self::default();
        tools.into_iter().for_each(|tool| {
            toolset.add_tool(tool);
        });
        toolset
    }

    /// Create a new `ToolSet` from complete dynamically-dispatched tools.
    pub fn from_tools_boxed(tools: Vec<ToolDyn>) -> Self {
        Self::from_tools(tools)
    }

    /// Create a toolset builder
    pub fn builder() -> ToolSetBuilder {
        ToolSetBuilder::default()
    }

    /// Check if the toolset contains a tool with the given name
    pub fn contains(&self, toolname: &str) -> bool {
        self.tools.contains_key(toolname)
    }

    /// Add a tool to the toolset, returning the registered key used for it.
    pub fn add_tool(&mut self, tool: impl IntoToolDyn) -> String {
        let (name, entry) = tool.into_tool_dyn().into_parts();
        self.insert_with_name(name, ToolType::Simple(entry))
    }

    /// Adds a complete dynamic tool to the toolset. Useful when dynamic dispatch is required.
    /// Returns the registered key used for the tool.
    pub fn add_tool_boxed(&mut self, tool: ToolDyn) -> String {
        self.add_tool(tool)
    }

    /// Add an embeddable tool to the toolset, returning the registered key used for it.
    pub fn add_embedding_tool(&mut self, tool: impl IntoToolEmbeddingDyn) -> String {
        let (name, entry) = tool.into_tool_embedding_dyn().into_parts();
        self.insert_with_name(name, ToolType::Embedding(entry))
    }

    pub(crate) fn insert(&mut self, name: String, tool: ToolType) -> String {
        self.insert_with_name(name, tool)
    }

    fn insert_with_name(&mut self, name: String, tool: ToolType) -> String {
        // `IndexMap::insert` replaces the value while keeping the existing
        // slot position, and returns the previous value when the name was
        // already registered.
        if self.tools.insert(name.clone(), tool).is_some() {
            tracing::warn!(
                tool_name = %name,
                "a tool named {name:?} was already registered; replacing it with the new registration"
            );
        }
        name
    }

    /// Remove a tool by name. Missing tools are ignored.
    pub fn delete_tool(&mut self, tool_name: &str) {
        // `shift_remove` preserves the order of the remaining tools;
        // `swap_remove` would not.
        self.tools.shift_remove(tool_name);
    }

    /// Merge another toolset into this one. Tools keep `toolset`'s
    /// registration order; names that already exist are replaced in place.
    pub fn add_tools(&mut self, toolset: ToolSet) {
        for (name, tool) in toolset.tools {
            self.insert_with_name(name, tool);
        }
    }

    pub(crate) fn get(&self, toolname: &str) -> Option<&ToolType> {
        self.tools.get(toolname)
    }

    /// Tool names in registration order.
    pub(crate) fn ordered_names(&self) -> impl Iterator<Item = &String> {
        self.tools.keys()
    }

    /// Registered tool names and tools in registration order.
    fn ordered_entries(&self) -> impl Iterator<Item = (&String, &ToolType)> {
        self.tools.iter()
    }

    /// Return definitions for all tools currently registered in the set, in
    /// registration order.
    pub fn get_tool_definitions(&self) -> Result<Vec<ToolDefinition>, ToolSetError> {
        Ok(self
            .ordered_entries()
            .map(|(name, tool)| tool.definition_with_name(name.clone()))
            .collect::<Vec<_>>())
    }

    /// Call a tool with the given name and arguments
    pub async fn call(&self, toolname: &str, args: String) -> Result<String, ToolSetError> {
        self.call_with_extensions(toolname, args, &ToolCallExtensions::EMPTY)
            .await
    }

    /// Call a tool with the given name, arguments, and per-call runtime extensions.
    ///
    /// The extensions are threaded through to [`Tool::call_with_extensions`],
    /// allowing tools to access caller-provided values (auth tokens, session
    /// IDs, etc.).
    pub async fn call_with_extensions(
        &self,
        toolname: &str,
        args: String,
        extensions: &ToolCallExtensions,
    ) -> Result<String, ToolSetError> {
        if let Some(tool) = self.tools.get(toolname) {
            tracing::debug!(target: "rig",
                "Calling tool {toolname} with args:\n{}",
                args
            );
            Ok(tool.call_with_extensions(args, extensions).await?)
        } else {
            Err(ToolSetError::ToolNotFoundError(toolname.to_string()))
        }
    }

    /// Call a tool by name, returning the structured [`ToolExecutionResult`].
    ///
    /// The structured counterpart of [`call`](Self::call): a failure is carried
    /// as [`ToolOutcome::Error`] inside the result rather than a `Result::Err`,
    /// and an unknown tool name resolves to a
    /// [`NotFound`](ToolFailureKind::NotFound) outcome. This is the path the
    /// agent loop drives so hooks and telemetry observe the structured outcome.
    pub async fn call_structured(
        &self,
        toolname: &str,
        args: String,
        extensions: &ToolCallExtensions,
    ) -> ToolExecutionResult {
        match self.tools.get(toolname) {
            Some(tool) => {
                tracing::debug!(target: "rig", "Calling tool {toolname} with args:\n{args}");
                tool.call_structured(args, extensions).await
            }
            None => ToolExecutionResult::failed(
                format!("tool `{toolname}` not found"),
                ToolFailure::not_found(format!("no tool named `{toolname}` is registered")),
            ),
        }
    }

    /// Get the documents of all the tools in the toolset
    pub async fn documents(&self) -> Result<Vec<completion::Document>, ToolSetError> {
        let mut docs = Vec::new();
        for (name, tool) in self.ordered_entries() {
            let definition = tool.definition_with_name(name.clone());
            docs.push(completion::Document {
                id: name.clone(),
                text: format!(
                    "\
                    Tool: {}\n\
                    Definition: \n\
                    {}\
                ",
                    name,
                    serde_json::to_string_pretty(&definition)?
                ),
                additional_props: HashMap::new(),
            });
        }
        Ok(docs)
    }

    /// Convert tools in self to objects of type ToolSchema.
    /// This is necessary because when adding tools to the EmbeddingBuilder because all
    /// documents added to the builder must all be of the same type.
    pub fn schemas(&self) -> Result<Vec<ToolSchema>, EmbedError> {
        self.ordered_entries()
            .filter_map(|(name, tool_type)| {
                if let ToolType::Embedding(tool) = tool_type {
                    Some(ToolSchema::from_registered_tool(name.clone(), tool))
                } else {
                    None
                }
            })
            .collect::<Result<Vec<_>, _>>()
    }
}

#[derive(Default)]
/// Builder for constructing a [`ToolSet`] with static and dynamic tools.
pub struct ToolSetBuilder {
    tools: Vec<(String, ToolType)>,
}

impl ToolSetBuilder {
    /// Add a regular tool that is always available when the set is used.
    pub fn static_tool(mut self, tool: impl IntoToolDyn) -> Self {
        let (name, entry) = tool.into_tool_dyn().into_parts();
        self.tools.push((name, ToolType::Simple(entry)));
        self
    }

    /// Add a tool that can be represented as embeddings for dynamic retrieval.
    pub fn dynamic_tool(mut self, tool: impl IntoToolEmbeddingDyn) -> Self {
        let (name, entry) = tool.into_tool_embedding_dyn().into_parts();
        self.tools.push((name, ToolType::Embedding(entry)));
        self
    }

    /// Build the tool set, keyed by each tool's stored canonical name.
    pub fn build(self) -> ToolSet {
        let mut toolset = ToolSet::default();
        for (name, tool) in self.tools {
            toolset.insert(name, tool);
        }
        toolset
    }
}

#[cfg(test)]
mod tests {
    use crate::message::{DocumentSourceKind, ToolResultContent};
    use crate::test_utils::{
        MockExampleTool, MockImageOutputTool, MockObjectOutputTool, MockStringOutputTool,
        MockToolError, mock_math_toolset,
    };
    use serde_json::json;

    use super::*;

    fn get_test_toolset() -> ToolSet {
        mock_math_toolset()
    }

    #[test]
    fn test_get_tool_definitions() {
        let toolset = get_test_toolset();
        let tools = toolset.get_tool_definitions().unwrap();
        assert_eq!(tools.len(), 2);
        assert_eq!(
            tools
                .iter()
                .map(|tool| tool.name.as_str())
                .collect::<Vec<_>>(),
            vec!["add", "subtract"],
            "provider definitions must use registered tool names in order"
        );
        assert!(tools.iter().all(|tool| !tool.description.is_empty()));
        assert!(tools.iter().all(|tool| tool.parameters.is_object()));
    }

    #[test]
    fn test_tool_deletion() {
        let mut toolset = get_test_toolset();
        assert_eq!(toolset.tools.len(), 2);
        toolset.delete_tool("add");
        assert!(!toolset.contains("add"));
        assert_eq!(toolset.tools.len(), 1);
        assert_eq!(
            toolset.ordered_names().cloned().collect::<Vec<_>>(),
            vec!["subtract".to_string()]
        );
    }

    #[test]
    fn deleting_a_middle_tool_preserves_order_of_survivors() {
        // Guards the `shift_remove` (not `swap_remove`) choice in `delete_tool`.
        // `swap_remove` would move the last tool into the deleted slot, so this
        // only catches a regression with 3+ tools and a non-last deletion: here
        // a `swap_remove("beta")` would yield [alpha, delta, gamma].
        let mut toolset = ToolSet::default();
        for name in ["alpha", "beta", "gamma", "delta"] {
            toolset.add_tool(named_tool(name, "test tool"));
        }

        toolset.delete_tool("beta");

        assert_eq!(
            toolset.ordered_names().cloned().collect::<Vec<_>>(),
            vec![
                "alpha".to_string(),
                "gamma".to_string(),
                "delta".to_string()
            ],
            "survivors must keep their registration order after a middle deletion"
        );
    }

    /// A concrete dynamic tool whose name and metadata are chosen at construction,
    /// for ordering and duplicate-registration tests.
    fn named_tool(name: &str, description: &str) -> ToolDyn {
        let description_for_call = description.to_string();
        ToolDyn::builder()
            .name(name)
            .description(description)
            .parameters(json!({ "type": "object", "properties": {} }))
            .call(move |_args| {
                let output = format!("called {description_for_call}");
                async move { Ok(output) }
            })
            .build()
            .unwrap()
    }

    #[test]
    fn tool_definition_uses_flattened_dyn_metadata() {
        let tool = named_tool("alpha", "runtime description");
        let definition = tool_definition(&tool);

        assert_eq!(definition.name, "alpha");
        assert_eq!(definition.description, "runtime description");
        assert_eq!(definition.parameters["type"], "object");
    }

    /// A structured-only dynamic tool that always returns the given result.
    fn structured_tool(name: &str, result: ToolExecutionResult) -> ToolDyn {
        ToolDyn::builder()
            .name(name)
            .description("structured-only tool")
            .parameters(json!({ "type": "object", "properties": {} }))
            .call_structured(move |_args, _extensions| {
                let result = result.clone();
                Box::pin(async move { result })
            })
            .build()
            .unwrap()
    }

    #[tokio::test]
    async fn structured_only_dynamic_tool_emits_denied_through_toolset() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(structured_tool(
            "guard",
            ToolExecutionResult::denied("cannot comply"),
        ));

        let result = toolset
            .call_structured("guard", "{}".to_string(), &ToolCallExtensions::EMPTY)
            .await;
        assert!(
            matches!(result.outcome(), ToolOutcome::Denied),
            "denied outcome must survive the registered structured path"
        );
        assert_eq!(result.model_output(), "cannot comply");

        // The string path is derived from the structured executor: a non-success
        // outcome surfaces as a ToolCallError carrying the model-facing message.
        let err = toolset
            .call("guard", "{}".to_string())
            .await
            .expect_err("non-success structured outcome must map to Err on the string path");
        assert!(err.to_string().contains("cannot comply"));
    }

    #[tokio::test]
    async fn structured_only_dynamic_tool_reports_precise_failure_kind() {
        let tool = structured_tool(
            "slow",
            ToolExecutionResult::failed("timed out after 5s", ToolFailure::timeout("deadline")),
        );

        let result = tool
            .call_structured("{}".to_string(), &ToolCallExtensions::EMPTY)
            .await;
        match result.outcome() {
            ToolOutcome::Error(failure) => assert_eq!(failure.kind, ToolFailureKind::Timeout),
            other => panic!("expected a timeout error outcome, got {other:?}"),
        }
        assert_eq!(result.model_output(), "timed out after 5s");
    }

    #[tokio::test]
    async fn structured_only_dynamic_tool_derives_success_string_path() {
        let tool = structured_tool("ok", ToolExecutionResult::success("all good"));

        let output = tool.call("{}".to_string()).await.unwrap();
        assert_eq!(output, "all good");
    }

    #[tokio::test]
    async fn dynamic_tool_with_both_executors_uses_each_path_directly() {
        let tool = ToolDyn::builder()
            .name("both")
            .description("dual executor tool")
            .parameters(json!({ "type": "object", "properties": {} }))
            .call(|_args| async { Ok("string path".to_string()) })
            .call_structured(|_args, _extensions| {
                Box::pin(async { ToolExecutionResult::success("structured path") })
            })
            .build()
            .unwrap();

        assert_eq!(tool.call("{}".to_string()).await.unwrap(), "string path");
        let result = tool
            .call_structured("{}".to_string(), &ToolCallExtensions::EMPTY)
            .await;
        assert_eq!(result.model_output(), "structured path");
    }

    #[test]
    fn builder_requires_at_least_one_executor() {
        let no_executor = ToolDyn::builder()
            .name("bare")
            .description("no executor")
            .parameters(json!({ "type": "object", "properties": {} }))
            .build();
        assert!(matches!(
            no_executor,
            Err(ToolDynBuilderError::MissingRuntime)
        ));

        let structured_only = ToolDyn::builder()
            .name("bare")
            .description("structured executor only")
            .parameters(json!({ "type": "object", "properties": {} }))
            .call_structured(|_args, _extensions| {
                Box::pin(async { ToolExecutionResult::success("ok") })
            })
            .build();
        assert!(structured_only.is_ok());
    }

    #[test]
    fn tool_dyn_exposes_stored_name() {
        assert_eq!(named_tool("alpha", "test tool").name(), "alpha");
        assert_eq!(ToolDyn::from(MockExampleTool).name(), MockExampleTool::NAME);
    }

    #[tokio::test]
    async fn with_name_renames_before_registration() {
        let tool = named_tool("original", "adds numbers").with_name("plus");
        assert_eq!(tool.name(), "plus");

        let alias = tool.clone().with_name("alias");

        let mut toolset = ToolSet::default();
        toolset.add_tool(tool);
        toolset.add_tool(alias);

        let names = toolset
            .get_tool_definitions()
            .unwrap()
            .into_iter()
            .map(|def| def.name)
            .collect::<Vec<_>>();
        assert_eq!(
            names,
            vec!["plus".to_string(), "alias".to_string()],
            "definitions must advertise the renamed keys, not the original name"
        );

        let docs = toolset.documents().await.unwrap();
        assert_eq!(
            docs.iter().map(|doc| doc.id.as_str()).collect::<Vec<_>>(),
            vec!["plus", "alias"]
        );

        // Both names dispatch to the same shared runtime.
        for name in ["plus", "alias"] {
            let output = toolset.call(name, "{}".to_string()).await.unwrap();
            assert_eq!(output, "called adds numbers");
        }
        assert!(!toolset.contains("original"));
    }

    #[tokio::test]
    async fn tool_definitions_follow_registration_order() {
        // Enough names that any non-order-preserving storage would almost
        // surely surface a regression: its iteration order would differ from
        // insertion order.
        let names: Vec<String> = (0..32).map(|i| format!("tool_{i:02}")).collect();
        let mut toolset = ToolSet::default();
        for name in &names {
            toolset.add_tool(named_tool(name, "test tool"));
        }

        let defs = toolset.get_tool_definitions().unwrap();
        let def_names: Vec<String> = defs.into_iter().map(|def| def.name).collect();
        assert_eq!(def_names, names);

        let docs = toolset.documents().await.unwrap();
        let doc_ids: Vec<String> = docs.into_iter().map(|doc| doc.id).collect();
        assert_eq!(doc_ids, names);
    }

    #[tokio::test]
    async fn registered_name_is_definition_source_of_truth() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(named_tool("registered", "registered dynamic tool"));

        let defs = toolset.get_tool_definitions().unwrap();
        assert_eq!(defs[0].name, "registered");

        let docs = toolset.documents().await.unwrap();
        assert_eq!(docs[0].id, "registered");
        assert!(docs[0].text.contains("registered"));
    }

    #[test]
    fn dynamic_tool_schemas_use_registered_name() {
        #[derive(Debug, thiserror::Error)]
        #[error("init error")]
        struct InitError;

        struct StaticDynamicTool;

        impl Tool for StaticDynamicTool {
            const NAME: &'static str = "unused";
            type Error = MockToolError;
            type Args = serde_json::Value;
            type Output = String;

            fn description(&self) -> String {
                "dynamic tool".to_string()
            }

            fn parameters(&self) -> serde_json::Value {
                json!({ "type": "object", "properties": {} })
            }

            async fn call(&self, _args: Self::Args) -> Result<Self::Output, Self::Error> {
                Ok("ok".to_string())
            }
        }

        impl ToolEmbedding for StaticDynamicTool {
            type InitError = InitError;
            type Context = ();
            type State = ();

            fn embedding_docs(&self) -> Vec<String> {
                vec!["dynamic tool docs".to_string()]
            }

            fn context(&self) -> Self::Context {}

            fn init(_state: Self::State, _context: Self::Context) -> Result<Self, Self::InitError> {
                Ok(Self)
            }
        }

        let toolset = ToolSet::builder().dynamic_tool(StaticDynamicTool).build();

        let schemas = toolset.schemas().unwrap();
        assert_eq!(schemas.len(), 1);
        assert_eq!(schemas[0].name, "unused");
        assert_eq!(schemas[0].embedding_docs, vec!["dynamic tool docs"]);
    }

    #[tokio::test]
    async fn duplicate_registration_replaces_in_place() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(named_tool("alpha", "first alpha"));
        toolset.add_tool(named_tool("beta", "beta"));
        toolset.add_tool(named_tool("alpha", "second alpha"));

        let defs = toolset.get_tool_definitions().unwrap();
        assert_eq!(
            defs.iter().map(|def| def.name.as_str()).collect::<Vec<_>>(),
            vec!["alpha", "beta"],
            "the duplicate should be deduped and keep its original position"
        );
        assert_eq!(
            defs[0].description, "second alpha",
            "the last registration should win"
        );

        let output = toolset.call("alpha", "{}".to_string()).await.unwrap();
        assert_eq!(output, "called second alpha");
    }

    #[tokio::test]
    async fn add_tools_merges_in_order_and_replaces_existing() {
        let mut base = ToolSet::default();
        base.add_tool(named_tool("alpha", "base alpha"));
        base.add_tool(named_tool("beta", "base beta"));

        let mut incoming = ToolSet::default();
        incoming.add_tool(named_tool("gamma", "incoming gamma"));
        incoming.add_tool(named_tool("alpha", "incoming alpha"));

        base.add_tools(incoming);

        let defs = base.get_tool_definitions().unwrap();
        assert_eq!(
            defs.iter().map(|def| def.name.as_str()).collect::<Vec<_>>(),
            vec!["alpha", "beta", "gamma"],
            "merged tools should follow registration order with replaced names keeping position"
        );
        assert_eq!(defs[0].description, "incoming alpha");
    }

    #[tokio::test]
    async fn string_tool_outputs_are_preserved_verbatim() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(MockStringOutputTool);

        let output = toolset
            .call("string_output", "{}".to_string())
            .await
            .expect("tool should succeed");

        assert_eq!(output, "Hello\nWorld");
    }

    #[tokio::test]
    async fn structured_string_tool_outputs_remain_parseable() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(MockImageOutputTool);

        let output = toolset
            .call("image_output", "{}".to_string())
            .await
            .expect("tool should succeed");
        let content = ToolResultContent::from_tool_output(output);

        assert_eq!(content.len(), 1);
        match content.first() {
            ToolResultContent::Image(image) => {
                assert!(matches!(image.data, DocumentSourceKind::Base64(_)));
                assert_eq!(image.media_type, Some(crate::message::ImageMediaType::PNG));
            }
            other => panic!("expected image tool result content, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn object_tool_outputs_still_serialize_as_json() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(MockObjectOutputTool);

        let output = toolset
            .call("object_output", "{}".to_string())
            .await
            .expect("tool should succeed");

        assert!(output.starts_with('{'));
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&output).unwrap(),
            json!({
                "status": "ok",
                "count": 42
            })
        );
    }

    #[tokio::test]
    async fn null_args_are_preserved_for_unit_args() {
        let mut toolset = ToolSet::default();
        toolset.add_tool(MockExampleTool);

        let output = toolset
            .call("example_tool", "null".to_string())
            .await
            .expect("unit args should accept null without object fallback");

        assert_eq!(output, "Example answer");
    }

    // Struct-typed args with all-optional fields — serde rejects `null` for these
    // even though the fields are optional. The normalization in `ToolDyn::call`
    // falls back from `null` to `{}` so callers can omit the
    // wrapping `Option<Args>` workaround.
    #[tokio::test]
    async fn null_args_are_normalized_to_empty_object() {
        use crate::test_utils::MockToolError;

        #[derive(serde::Deserialize, serde::Serialize)]
        struct NoRequiredArgs {
            label: Option<String>,
        }

        struct NoArgTool;

        impl Tool for NoArgTool {
            const NAME: &'static str = "no_arg_tool";
            type Error = MockToolError;
            type Args = NoRequiredArgs;
            type Output = String;

            fn description(&self) -> String {
                "Tool with no required arguments".to_string()
            }

            fn parameters(&self) -> serde_json::Value {
                json!({"type": "object", "properties": {}})
            }

            async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
                Ok(args.label.unwrap_or_else(|| "default".to_string()))
            }
        }

        let mut toolset = ToolSet::default();
        toolset.add_tool(NoArgTool);

        // `null` is what LLMs send when no arguments are provided; without the
        // normalization this would return `ToolError::JsonError`.
        let output = toolset
            .call("no_arg_tool", "null".to_string())
            .await
            .expect("null args should succeed after normalisation");

        assert_eq!(output, "default");
    }
}
