#![cfg_attr(docsrs, feature(doc_cfg))]
#![cfg_attr(
    test,
    allow(
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::panic,
        clippy::unwrap_used
    )
)]
//! Agent-to-Agent (A2A) protocol client integration for the Rig agent
//! framework.
//!
//! See the [crate README](https://crates.io/crates/rig-a2a) for an overview.
//!
//! [`A2AClient`] fetches a remote agent's `AgentCard` and exposes it two ways:
//!
//! - as a **tool** on a local Rig agent, via [`A2AClient::tool`] or
//!   [`A2AAgentBuilderExt::a2a_tool`] — one remote agent becomes one tool
//!   taking a single `prompt`, the same shape
//!   [`Agent::into_tool`](rig_agent::agent::Agent::into_tool) gives a
//!   sub-agent;
//! - as a **completion model**, via [`A2AClient::model`] or
//!   [`A2AClient::agent`] — the remote agent backs a Rig [`Agent`], so
//!   `prompt`, `chat`, streaming, hooks, and conversation memory all work
//!   against it. See [`model`] for what the A2A protocol cannot carry.
//!
//! Both surfaces share one conversation store, so a [`ConversationId`] used
//! against the tool and against the model refers to the same remote
//! conversation.
//!
//! # Conversation threading
//!
//! A2A identifiers are generated by the server and echoed back by clients. Rig
//! never shows them to the model: the host records the ids issued for each
//! [`ConversationId`] and re-attaches them. Note the asymmetry — the tool and
//! model surfaces thread automatically from a conversation key, while the
//! direct [`A2AClient::message`] API stays explicit and takes ids you pass it.
//!
//! This crate currently supports native targets. Its upstream A2A client uses
//! Tokio networking, which is not available on `wasm32-unknown-unknown`.
//!
//! [`Agent`]: rig_agent::agent::Agent

pub mod error;
pub use error::A2AError;

pub(crate) mod parts;

pub mod builder_ext;
pub mod client;
pub mod hook;
pub mod model;
pub mod thread;
pub mod tool;

pub use builder_ext::A2AAgentBuilderExt;
pub use client::{
    A2AClient, A2AClientBuilder, A2ARequest, DEFAULT_HTTP_TIMEOUT, SendMessageResponse,
};
pub use hook::A2AThreadHook;
pub use model::{A2AModel, THREAD_PARAMS_KEY};
pub use thread::{A2AThreadInfo, ConversationId};

use rig_agent::tool::ToolContext;

/// Default well-known path where an A2A `AgentCard` is published.
pub const WELL_KNOWN_AGENT_CARD_PATH: &str = "/.well-known/agent-card.json";

/// A [`ToolContext`] carrying just this conversation id.
///
/// Calls made with this context thread into one remote A2A conversation. When
/// Rig's conversation memory is also in use, pass the same string to
/// [`conversation`](rig_agent::agent::AgentBuilder::conversation) so the local
/// history and the remote conversation stay aligned — the two are independent
/// and Rig does not reconcile them.
///
/// ```no_run
/// use rig_agent::completion::Prompt;
///
/// # async fn run(agent: rig_agent::agent::Agent) -> anyhow::Result<()> {
/// let reply = agent
///     .prompt("What did I ask you first?")
///     .conversation("user-42") // Rig-side memory
///     .tool_context(rig_a2a::conversation_context("user-42")) // remote A2A thread
///     .await?;
/// # let _ = reply;
/// # Ok(()) }
/// ```
pub fn conversation_context(id: impl Into<String>) -> ToolContext {
    let mut context = ToolContext::new();
    context.insert(ConversationId::new(id));
    context
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conversation_context_carries_the_id() {
        let context = conversation_context("user-42");
        assert_eq!(
            context.get::<ConversationId>(),
            Some(&ConversationId::new("user-42"))
        );
    }
}
