#![cfg_attr(docsrs, feature(doc_cfg))]
#![cfg_attr(
    test,
    allow(
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::panic,
        clippy::unwrap_used
    )
)]
//! Agent-to-Agent (A2A) protocol client integration for the Rig agent
//! framework.
//!
//! See the [crate README](https://crates.io/crates/rig-a2a) for an overview.
//!
//! [`A2AClient`] fetches a remote agent's `AgentCard` and exposes it as a Rig
//! completion model or [`Agent`](rig_agent::agent::Agent). The agent supports
//! `prompt`, `chat`, streaming, hooks, and conversation memory, and Rig's
//! [`Agent::into_tool`](rig_agent::agent::Agent::into_tool) can compose it as a
//! sub-agent tool without an A2A-specific tool API. See [`model`] for what the
//! A2A protocol cannot carry.
//!
//! # Conversation threading
//!
//! A2A identifiers are generated by the server and echoed back by clients. Rig
//! never shows them to the model: the host records the ids issued for each
//! [`ConversationId`] and re-attaches them. Use [`A2AConversationExt`] to set
//! the same conversation on Rig memory and an A2A-backed model. When converting
//! an A2A-backed agent into a tool, call
//! [`A2AConversationExt::a2a_conversation`] on its builder first if calls must
//! share a remote conversation. The direct [`A2AClient::message`] API stays
//! explicit and takes ids you pass it.
//!
//! This crate currently supports native targets. Its upstream A2A client uses
//! Tokio networking, which is not available on `wasm32-unknown-unknown`.
//!
//! [`Agent`]: rig_agent::agent::Agent

pub mod error;
pub use error::A2AError;

pub(crate) mod card;
pub(crate) mod parts;

pub mod client;
pub mod conversation;
pub mod model;
pub mod thread;

pub use client::{
    A2AClient, A2AClientBuilder, A2ARequest, DEFAULT_HTTP_TIMEOUT, SendMessageResponse,
};
pub use conversation::A2AConversationExt;
pub use model::{A2AModel, THREAD_PARAMS_KEY};
pub use thread::ConversationId;

/// Default well-known path where an A2A `AgentCard` is published.
pub const WELL_KNOWN_AGENT_CARD_PATH: &str = "/.well-known/agent-card.json";
