use serde::Serialize;
use serde_json::Value;
use std::collections::HashMap;

use crate::{OneOrMany, embeddings::Embedding};

use super::{IndexStrategy, VectorStoreError, in_memory_store::InMemoryVectorStore};

/// Builder for creating an [`InMemoryVectorStore`] with custom configuration.
///
/// Document payloads are serialized to JSON as they are added; the first
/// serialization failure is surfaced by [`InMemoryVectorStoreBuilder::build`].
#[derive(Default)]
pub struct InMemoryVectorStoreBuilder {
    /// Embeddings of the documents, keyed by document id.
    embeddings: HashMap<String, (Value, OneOrMany<Embedding>)>,

    /// Index strategy for the vector store.
    index_strategy: IndexStrategy,

    /// First payload serialization error encountered, surfaced by `build()`.
    error: Option<VectorStoreError>,
}

impl InMemoryVectorStoreBuilder {
    /// Create a new builder with default settings.
    ///
    /// The default index strategy is [`IndexStrategy::BruteForce`].
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the index strategy for the vector store.
    ///
    /// # Examples
    ///
    /// ```
    /// use rig_core::vector_store::{builder::InMemoryVectorStoreBuilder, IndexStrategy};
    ///
    /// let store = InMemoryVectorStoreBuilder::new()
    ///     .index_strategy(IndexStrategy::LSH {
    ///         num_tables: 5,
    ///         num_hyperplanes: 10,
    ///     })
    ///     .build()
    ///     .unwrap();
    /// ```
    pub fn index_strategy(mut self, index_strategy: IndexStrategy) -> Self {
        self.index_strategy = index_strategy;
        self
    }

    fn insert<D: Serialize>(&mut self, id: String, doc: D, embeddings: OneOrMany<Embedding>) {
        match serde_json::to_value(&doc) {
            Ok(payload) => {
                self.embeddings.insert(id, (payload, embeddings));
            }
            Err(e) => {
                if self.error.is_none() {
                    self.error = Some(VectorStoreError::JsonError(e));
                }
            }
        }
    }

    /// Add documents with auto-generated IDs.
    /// IDs will have the form `"doc{n}"` where `n` is the index.
    pub fn documents<D: Serialize>(
        mut self,
        documents: impl IntoIterator<Item = (D, OneOrMany<Embedding>)>,
    ) -> Self {
        let current_index = self.embeddings.len();
        for (i, (doc, embeddings)) in documents.into_iter().enumerate() {
            self.insert(format!("doc{}", i + current_index), doc, embeddings);
        }
        self
    }

    /// Add documents with explicit IDs.
    pub fn documents_with_ids<D: Serialize>(
        mut self,
        documents: impl IntoIterator<Item = (impl ToString, D, OneOrMany<Embedding>)>,
    ) -> Self {
        for (id, doc, embeddings) in documents {
            self.insert(id.to_string(), doc, embeddings);
        }
        self
    }

    /// Add documents with IDs generated by a function.
    pub fn documents_with_id_f<D: Serialize>(
        mut self,
        documents: impl IntoIterator<Item = (D, OneOrMany<Embedding>)>,
        f: fn(&D) -> String,
    ) -> Self {
        for (doc, embeddings) in documents {
            self.insert(f(&doc), doc, embeddings);
        }
        self
    }

    /// Build the [`InMemoryVectorStore`] with the configured settings.
    ///
    /// Returns the first payload serialization error encountered, if any.
    pub fn build(self) -> Result<InMemoryVectorStore, VectorStoreError> {
        if let Some(error) = self.error {
            return Err(error);
        }

        Ok(InMemoryVectorStore::from_builder(
            self.embeddings,
            self.index_strategy,
        ))
    }
}
