#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  scripts/sync_agent_instruction_files.sh
  scripts/sync_agent_instruction_files.sh --check

Generates agent-specific instruction adapters from AGENTS.md.
--check validates that generated files are in sync without writing changes.
EOF
}

MODE="write"
if [[ "${1:-}" == "--check" ]]; then
    MODE="check"
    shift
fi

if [[ "$#" -ne 0 ]]; then
    usage
    exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_FILE="${ROOT_DIR}/AGENTS.md"

if [[ ! -f "${AGENTS_FILE}" ]]; then
    echo "error: missing canonical source: ${AGENTS_FILE}" >&2
    exit 1
fi

MODULE_IDS=(
    "rig-core-patterns"
    "rig-provider-implementation"
    "rig-vector-store-implementation"
    "rig-wasm-compat"
    "rig-prompt-hooks"
    "rig-quality-gates"
)

GENERATED_FILES=(
    # Claude Code — Skills (Agent Skills standard)
    ".claude/skills/rig-agent-scaffold/SKILL.md"
    ".claude/skills/rig-provider/SKILL.md"
    ".claude/skills/rig-vector-store/SKILL.md"
    ".claude/skills/rig-review/SKILL.md"
    ".claude/skills/rig-wasm-check/SKILL.md"
    # Claude Code — Legacy commands (kept for backward compatibility)
    ".claude/commands/rig-agent-scaffold.md"
    ".claude/commands/rig-provider-checklist.md"
    ".claude/commands/rig-review-gates.md"
    # GitHub Copilot
    ".github/copilot-instructions.md"
    ".github/instructions/rig.instructions.md"
    ".github/prompts/rig-agent.prompt.md"
    ".github/prompts/rig-provider.prompt.md"
    # Cursor
    ".cursor/rules/rig-core.mdc"
    ".cursor/rules/rig-provider.mdc"
    ".cursor/rules/rig-quality.mdc"
    # Windsurf
    ".windsurf/rules/rig-core.md"
    ".windsurf/rules/rig-provider.md"
    ".windsurf/rules/rig-quality.md"
    # Cline
    ".clinerules/01-rig-core.md"
    ".clinerules/02-rig-provider.md"
    ".clinerules/03-rig-quality.md"
    # Continue
    ".continue/rules/rig-core.md"
    ".continue/rules/rig-provider.md"
    ".continue/rules/rig-quality.md"
    # Roo Code
    ".roo/rules/rig-core.md"
    ".roo/rules/rig-provider.md"
    ".roo/rules/rig-quality.md"
)

GENERATED_HEADER='<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->'

extract_module() {
    local module_id="$1"
    local output_file="$2"
    local start_marker="<!-- RIG_SKILL_MODULE: ${module_id} START -->"
    local end_marker="<!-- RIG_SKILL_MODULE: ${module_id} END -->"

    if ! awk -v start="${start_marker}" -v end="${end_marker}" '
        $0 == start { in_block = 1; next }
        $0 == end { in_block = 0; found = 1; exit }
        in_block { print }
        END {
            if (!found) {
                exit 22
            }
        }
    ' "${AGENTS_FILE}" > "${output_file}"; then
        echo "error: failed to extract module '${module_id}' from ${AGENTS_FILE}" >&2
        exit 1
    fi

    if [[ ! -s "${output_file}" ]]; then
        echo "error: extracted module '${module_id}' is empty" >&2
        exit 1
    fi
}

prepare_modules() {
    local module_dir="$1"
    mkdir -p "${module_dir}"

    local module_id
    for module_id in "${MODULE_IDS[@]}"; do
        extract_module "${module_id}" "${module_dir}/${module_id}.md"
    done
}

render_adapters() {
    local out_dir="$1"
    local module_dir="$2"
    local core_file="${module_dir}/rig-core-patterns.md"
    local provider_file="${module_dir}/rig-provider-implementation.md"
    local vector_file="${module_dir}/rig-vector-store-implementation.md"
    local wasm_file="${module_dir}/rig-wasm-compat.md"
    local prompt_hooks_file="${module_dir}/rig-prompt-hooks.md"
    local quality_file="${module_dir}/rig-quality-gates.md"

    mkdir -p \
        "${out_dir}/.claude/skills/rig-agent-scaffold" \
        "${out_dir}/.claude/skills/rig-provider" \
        "${out_dir}/.claude/skills/rig-vector-store" \
        "${out_dir}/.claude/skills/rig-review" \
        "${out_dir}/.claude/skills/rig-wasm-check" \
        "${out_dir}/.claude/commands" \
        "${out_dir}/.github/instructions" \
        "${out_dir}/.github/prompts" \
        "${out_dir}/.cursor/rules" \
        "${out_dir}/.windsurf/rules" \
        "${out_dir}/.clinerules" \
        "${out_dir}/.continue/rules" \
        "${out_dir}/.roo/rules"

    # ── Claude Skills (Agent Skills standard) ─────────────────────────

    {
        cat <<'HEADER'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: rig-agent-scaffold
description: >
  Scaffold a Rig agent implementation. Use when creating agents, chatbots,
  RAG pipelines, or tool-calling workflows with Rig's builder pattern.
argument-hint: "[agent-description]"
allowed-tools:
  - Read
  - Glob
  - Grep
  - Edit
  - Write
  - Bash
---

# Rig Agent Scaffold

Create or refactor a Rig agent implementation.

Execution requirements:
1. Preserve trait-based abstractions and builder-pattern ergonomics.
2. Use `WasmCompatSend` / `WasmCompatSync` bounds where applicable.
3. Handle all fallible paths without `.unwrap()` / `.expect()` unless impossible.
4. Add tests or compileable examples for user-facing functionality.
5. Run `cargo fmt`, `cargo clippy --all-targets --all-features`, and `cargo test`.

## rig-core-patterns

HEADER
        cat "${core_file}"
        cat <<'SEP'

## rig-wasm-compat

SEP
        cat "${wasm_file}"
        cat <<'SEP'

## rig-prompt-hooks

SEP
        cat "${prompt_hooks_file}"
        cat <<'SEP'

## rig-quality-gates

SEP
        cat "${quality_file}"
    } > "${out_dir}/.claude/skills/rig-agent-scaffold/SKILL.md"

    {
        cat <<'HEADER'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: rig-provider
description: >
  Implement or audit a Rig model provider. Use when adding support for a new
  LLM API or reviewing an existing provider against the canonical checklist.
  Follows the OpenAI reference implementation pattern.
argument-hint: "[provider-name]"
allowed-tools:
  - Read
  - Glob
  - Grep
  - Edit
  - Write
  - Bash
---

# Rig Provider Checklist

Implement or audit a Rig provider integration.

Provider checklist:
1. Follow the required provider extension, capabilities, builder, aliases, and model constants pattern.
2. Keep request/response fields aligned with the upstream provider API.
3. Implement streaming and non-streaming paths where supported.
4. Add telemetry spans and map errors to Rig error types.
5. Validate no forbidden shortcuts (`String` error types, TODO stubs, blanket unwraps).

## rig-provider-implementation

HEADER
        cat "${provider_file}"
        cat <<'SEP'

## rig-wasm-compat

SEP
        cat "${wasm_file}"
        cat <<'SEP'

## rig-prompt-hooks

SEP
        cat "${prompt_hooks_file}"
        cat <<'SEP'

## rig-quality-gates

SEP
        cat "${quality_file}"
    } > "${out_dir}/.claude/skills/rig-provider/SKILL.md"

    {
        cat <<'HEADER'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: rig-vector-store
description: >
  Implement a Rig vector store companion crate. Use when adding a new vector
  database backend (MongoDB, LanceDB, Qdrant, etc.) or reviewing an existing
  vector store integration.
argument-hint: "[store-backend]"
allowed-tools:
  - Read
  - Glob
  - Grep
  - Edit
  - Write
  - Bash
---

# Rig Vector Store Implementation

Implement or audit a Rig vector store companion crate.

Requirements:
1. Implement `VectorStoreIndex` trait with both `top_n` and `top_n_ids`.
2. Define an appropriate `Filter` type for your backend.
3. Use `WasmCompatSend` / `WasmCompatSync` bounds.
4. Return proper `VectorStoreError` variants.
5. Create the store as a separate companion crate (e.g., `rig-mongodb`).

## rig-vector-store-implementation

HEADER
        cat "${vector_file}"
        cat <<'SEP'

## rig-wasm-compat

SEP
        cat "${wasm_file}"
        cat <<'SEP'

## rig-quality-gates

SEP
        cat "${quality_file}"
    } > "${out_dir}/.claude/skills/rig-vector-store/SKILL.md"

    {
        cat <<'HEADER'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: rig-review
description: >
  Review Rig changes against mandatory quality gates before opening a PR.
  Use before submitting code to verify error handling, WASM compatibility,
  coding style, and required checks pass.
allowed-tools:
  - Read
  - Glob
  - Grep
  - Bash
---

# Rig Pre-PR Review

Perform a Rig-focused pre-PR review.

Required output format:
1. List blocking issues first with file and line references.
2. List medium/low-risk issues second.
3. Confirm required checks and test evidence.
4. Explicitly state whether public API changed.
5. If no issues are found, say so and note residual risk.

## rig-prompt-hooks

HEADER
        cat "${prompt_hooks_file}"
        cat <<'SEP'

## rig-quality-gates

SEP
        cat "${quality_file}"
    } > "${out_dir}/.claude/skills/rig-review/SKILL.md"

    {
        cat <<'HEADER'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: rig-wasm-check
description: >
  Audit Rig code for WebAssembly compatibility. Use when verifying that trait
  bounds use WasmCompatSend/WasmCompatSync, futures use WasmBoxedFuture, and
  error types have proper conditional compilation.
allowed-tools:
  - Read
  - Glob
  - Grep
---

# Rig WASM Compatibility Check

Audit code for WebAssembly target compatibility.

Check these patterns:
1. All trait bounds use `WasmCompatSend` / `WasmCompatSync` instead of raw `Send` / `Sync`.
2. Boxed futures use `WasmBoxedFuture` instead of `Pin<Box<dyn Future + Send>>`.
3. Error types use `#[cfg(target_family = "wasm")]` for platform-specific bounds.
4. No direct `Send`/`Sync` bounds that would break WASM compilation.

## rig-wasm-compat

HEADER
        cat "${wasm_file}"
    } > "${out_dir}/.claude/skills/rig-wasm-check/SKILL.md"

    # ── Claude Commands (legacy, kept for backward compatibility) ─────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
description: Scaffold a Rig agent implementation that follows Rig architecture and quality gates.
---

Create or refactor a Rig agent implementation.

Canonical source:
- `AGENTS.md`
- [rig-core-patterns](../../AGENTS.md#rig-core-patterns)
- [rig-wasm-compat](../../AGENTS.md#rig-wasm-compat)
- [rig-prompt-hooks](../../AGENTS.md#rig-prompt-hooks)
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

Execution requirements:
1. Preserve trait-based abstractions and builder-pattern ergonomics.
2. Use `WasmCompatSend` / `WasmCompatSync` bounds where applicable.
3. Handle all fallible paths without `.unwrap()` / `.expect()` unless impossible.
4. Add tests or compileable examples for user-facing functionality.
5. Run `cargo fmt`, `cargo clippy --all-targets --all-features`, and `cargo test`.

Reference excerpts:

## rig-core-patterns

EOF
        cat "${core_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
        cat <<'EOF'

## rig-prompt-hooks

EOF
        cat "${prompt_hooks_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.claude/commands/rig-agent-scaffold.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
description: Implement or review a Rig provider integration against the canonical provider checklist.
---

Use this command when implementing a new model provider or auditing provider code.

Canonical source:
- `AGENTS.md`
- [rig-provider-implementation](../../AGENTS.md#rig-provider-implementation)
- [rig-wasm-compat](../../AGENTS.md#rig-wasm-compat)
- [rig-prompt-hooks](../../AGENTS.md#rig-prompt-hooks)
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

Provider checklist:
1. Follow the required provider extension, capabilities, builder, aliases, and model constants pattern.
2. Keep request/response fields aligned with the upstream provider API.
3. Implement streaming and non-streaming paths where supported.
4. Add telemetry spans and map errors to Rig error types.
5. Validate no forbidden shortcuts (`String` error types, TODO stubs, blanket unwraps).

Reference excerpts:

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
        cat <<'EOF'

## rig-prompt-hooks

EOF
        cat "${prompt_hooks_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.claude/commands/rig-provider-checklist.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
description: Review Rig changes against mandatory quality gates before opening a PR.
---

Perform a Rig-focused pre-PR review.

Canonical source:
- `AGENTS.md`
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

Required output format:
1. List blocking issues first with file and line references.
2. List medium/low-risk issues second.
3. Confirm required checks and test evidence.
4. Explicitly state whether public API changed.
5. If no issues are found, say so and note residual risk.

Reference excerpts:

## rig-prompt-hooks

EOF
        cat "${prompt_hooks_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.claude/commands/rig-review-gates.md"

    # ── GitHub Copilot ────────────────────────────────────────────────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
# Rig Copilot Repository Instructions

These instructions are generated from `AGENTS.md` and are the canonical rules for AI-assisted edits in this repository.

Canonical sections:
- [rig-core-patterns](../AGENTS.md#rig-core-patterns)
- [rig-provider-implementation](../AGENTS.md#rig-provider-implementation)
- [rig-vector-store-implementation](../AGENTS.md#rig-vector-store-implementation)
- [rig-wasm-compat](../AGENTS.md#rig-wasm-compat)
- [rig-prompt-hooks](../AGENTS.md#rig-prompt-hooks)
- [rig-quality-gates](../AGENTS.md#rig-quality-gates)

## rig-core-patterns

EOF
        cat "${core_file}"
        cat <<'EOF'

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-vector-store-implementation

EOF
        cat "${vector_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
        cat <<'EOF'

## rig-prompt-hooks

EOF
        cat "${prompt_hooks_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.github/copilot-instructions.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
applyTo: "**/*.rs"
---

# Rig Rust Implementation Rules

Apply these rules when editing Rust source files in this repository.

Canonical sections:
- [rig-core-patterns](../../AGENTS.md#rig-core-patterns)
- [rig-wasm-compat](../../AGENTS.md#rig-wasm-compat)
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

## rig-core-patterns

EOF
        cat "${core_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.github/instructions/rig.instructions.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
mode: agent
description: Scaffold a production-ready Rig agent implementation.
tools:
  [
    "changes",
    "codebase",
    "editFiles",
    "fetch",
    "findTestFiles",
    "githubRepo",
    "new",
    "openSimpleBrowser",
    "problems",
    "runCommands",
    "runNotebooks",
    "search",
    "searchResults",
    "terminalLastCommand",
    "terminalSelection",
    "usages",
  ]
---

Create a Rig agent implementation with tests/examples and production-quality error handling.

Use this workflow:
1. Summarize user goal and affected crates.
2. Implement with Rig builder pattern and trait-based abstractions.
3. Keep WASM compatibility intact with `WasmCompatSend` / `WasmCompatSync`.
4. Add or update tests/examples.
5. Validate with `cargo fmt`, `cargo clippy --all-targets --all-features`, and `cargo test`.

Canonical references:
- [rig-core-patterns](../../AGENTS.md#rig-core-patterns)
- [rig-wasm-compat](../../AGENTS.md#rig-wasm-compat)
- [rig-prompt-hooks](../../AGENTS.md#rig-prompt-hooks)
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

## rig-core-patterns

EOF
        cat "${core_file}"
        cat <<'EOF'

## rig-prompt-hooks

EOF
        cat "${prompt_hooks_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.github/prompts/rig-agent.prompt.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
mode: agent
description: Implement a Rig model provider integration from the canonical checklist.
tools:
  [
    "changes",
    "codebase",
    "editFiles",
    "fetch",
    "findTestFiles",
    "githubRepo",
    "new",
    "openSimpleBrowser",
    "problems",
    "runCommands",
    "runNotebooks",
    "search",
    "searchResults",
    "terminalLastCommand",
    "terminalSelection",
    "usages",
  ]
---

Implement or review a Rig provider integration.

Use this workflow:
1. Match upstream provider API exactly.
2. Implement provider capabilities, completion/embedding traits, conversions, and telemetry.
3. Support streaming and non-streaming where available.
4. Ensure `WasmCompatSend` / `WasmCompatSync` compatibility.
5. Add tests/examples and run required checks.

Canonical references:
- [rig-provider-implementation](../../AGENTS.md#rig-provider-implementation)
- [rig-wasm-compat](../../AGENTS.md#rig-wasm-compat)
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
        cat <<'EOF'

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.github/prompts/rig-provider.prompt.md"

    # ── Cursor ────────────────────────────────────────────────────────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
description: Rig core architecture rules for Cursor.
globs:
  - "**/*.rs"
alwaysApply: false
---

Use these Rig architectural constraints when editing Rust code.

Canonical section:
- [rig-core-patterns](../../AGENTS.md#rig-core-patterns)

## rig-core-patterns

EOF
        cat "${core_file}"
    } > "${out_dir}/.cursor/rules/rig-core.mdc"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
description: Rig provider and vector-store integration checklist for Cursor.
globs:
  - "**/*.rs"
alwaysApply: false
---

Use this checklist for provider and vector-store implementations.

Canonical sections:
- [rig-provider-implementation](../../AGENTS.md#rig-provider-implementation)
- [rig-vector-store-implementation](../../AGENTS.md#rig-vector-store-implementation)
- [rig-wasm-compat](../../AGENTS.md#rig-wasm-compat)

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-vector-store-implementation

EOF
        cat "${vector_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
    } > "${out_dir}/.cursor/rules/rig-provider.mdc"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
description: Rig coding standards and PR quality gates for Cursor.
globs:
  - "**/*.rs"
  - "**/*.md"
alwaysApply: false
---

Use these quality gates for all Rig contributions.

Canonical section:
- [rig-quality-gates](../../AGENTS.md#rig-quality-gates)

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.cursor/rules/rig-quality.mdc"

    # ── Windsurf ──────────────────────────────────────────────────────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->

# Rig Core Architecture

Apply these Rig architectural constraints when editing Rust code.

## rig-core-patterns

EOF
        cat "${core_file}"
    } > "${out_dir}/.windsurf/rules/rig-core.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->

# Rig Provider & Vector Store Implementation

Use this checklist for provider and vector-store implementations.

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-vector-store-implementation

EOF
        cat "${vector_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
    } > "${out_dir}/.windsurf/rules/rig-provider.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->

# Rig Quality Gates

Use these quality gates for all Rig contributions.

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.windsurf/rules/rig-quality.md"

    # ── Cline ─────────────────────────────────────────────────────────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
paths:
  - "**/*.rs"
---

# Rig Core Architecture

Apply these Rig architectural constraints when editing Rust code.

## rig-core-patterns

EOF
        cat "${core_file}"
    } > "${out_dir}/.clinerules/01-rig-core.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
paths:
  - "**/*.rs"
---

# Rig Provider & Vector Store Implementation

Use this checklist for provider and vector-store implementations.

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-vector-store-implementation

EOF
        cat "${vector_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
    } > "${out_dir}/.clinerules/02-rig-provider.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
paths:
  - "**/*.rs"
  - "**/*.md"
---

# Rig Quality Gates

Use these quality gates for all Rig contributions.

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.clinerules/03-rig-quality.md"

    # ── Continue ──────────────────────────────────────────────────────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: Rig Core Architecture
globs: "**/*.rs"
alwaysApply: false
---

Apply these Rig architectural constraints when editing Rust code.

## rig-core-patterns

EOF
        cat "${core_file}"
    } > "${out_dir}/.continue/rules/rig-core.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: Rig Provider Implementation
globs: "**/*.rs"
alwaysApply: false
---

Use this checklist for provider and vector-store implementations.

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-vector-store-implementation

EOF
        cat "${vector_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
    } > "${out_dir}/.continue/rules/rig-provider.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->
---
name: Rig Quality Gates
globs:
  - "**/*.rs"
  - "**/*.md"
alwaysApply: false
---

Use these quality gates for all Rig contributions.

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.continue/rules/rig-quality.md"

    # ── Roo Code ──────────────────────────────────────────────────────

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->

# Rig Core Architecture

Apply these Rig architectural constraints when editing Rust code.

## rig-core-patterns

EOF
        cat "${core_file}"
    } > "${out_dir}/.roo/rules/rig-core.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->

# Rig Provider & Vector Store Implementation

Use this checklist for provider and vector-store implementations.

## rig-provider-implementation

EOF
        cat "${provider_file}"
        cat <<'EOF'

## rig-vector-store-implementation

EOF
        cat "${vector_file}"
        cat <<'EOF'

## rig-wasm-compat

EOF
        cat "${wasm_file}"
    } > "${out_dir}/.roo/rules/rig-provider.md"

    {
        cat <<'EOF'
<!-- This file is generated by scripts/sync_agent_instruction_files.sh. -->
<!-- Do not edit this file directly; update AGENTS.md and re-run the sync script. -->

# Rig Quality Gates

Use these quality gates for all Rig contributions.

## rig-quality-gates

EOF
        cat "${quality_file}"
    } > "${out_dir}/.roo/rules/rig-quality.md"
}

sync_claude_alias() {
    local claude_file="${ROOT_DIR}/CLAUDE.md"
    if [[ -L "${claude_file}" ]]; then
        ln -sfn "AGENTS.md" "${claude_file}"
        return
    fi

    if ln -s "AGENTS.md" "${claude_file}" >/dev/null 2>&1; then
        return
    fi

    cp "${AGENTS_FILE}" "${claude_file}"
}

sync_gemini_alias() {
    local gemini_file="${ROOT_DIR}/GEMINI.md"
    if [[ -L "${gemini_file}" ]]; then
        ln -sfn "AGENTS.md" "${gemini_file}"
        return
    fi

    if ln -s "AGENTS.md" "${gemini_file}" >/dev/null 2>&1; then
        return
    fi

    cp "${AGENTS_FILE}" "${gemini_file}"
}

check_alias() {
    local alias_file="$1"
    local label="$2"

    if [[ -L "${alias_file}" ]]; then
        if [[ "$(readlink "${alias_file}")" != "AGENTS.md" ]]; then
            echo "error: ${label} symlink must target AGENTS.md" >&2
            return 1
        fi
        return 0
    fi

    if [[ -f "${alias_file}" ]] && cmp -s "${AGENTS_FILE}" "${alias_file}"; then
        return 0
    fi

    echo "error: ${label} must be a symlink to AGENTS.md or an exact copy" >&2
    return 1
}

if [[ "${MODE}" == "write" ]]; then
    module_tmp_dir="$(mktemp -d)"
    trap 'rm -rf "${module_tmp_dir}"' EXIT
    prepare_modules "${module_tmp_dir}"
    render_adapters "${ROOT_DIR}" "${module_tmp_dir}"
    sync_claude_alias
    sync_gemini_alias
    echo "Generated ${#GENERATED_FILES[@]} adapter files from AGENTS.md"
    exit 0
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT
prepare_modules "${tmp_dir}/modules"
render_adapters "${tmp_dir}/generated" "${tmp_dir}/modules"

check_failed=0
for rel_path in "${GENERATED_FILES[@]}"; do
    expected="${tmp_dir}/generated/${rel_path}"
    actual="${ROOT_DIR}/${rel_path}"

    if [[ ! -f "${actual}" ]]; then
        echo "error: missing generated file: ${actual}" >&2
        check_failed=1
        continue
    fi

    if ! cmp -s "${actual}" "${expected}"; then
        echo "error: generated file out of sync: ${actual}" >&2
        diff -u "${actual}" "${expected}" || true
        check_failed=1
    fi
done

if ! check_alias "${ROOT_DIR}/CLAUDE.md" "CLAUDE.md"; then
    check_failed=1
fi

if ! check_alias "${ROOT_DIR}/GEMINI.md" "GEMINI.md"; then
    check_failed=1
fi

if [[ "${check_failed}" -ne 0 ]]; then
    echo "Run scripts/sync_agent_instruction_files.sh to refresh generated files." >&2
    exit 1
fi

echo "Agent instruction adapters are in sync."
