"""Small, offline regression tests for lockfile isolation (no real Cargo builds)."""
import importlib.util
import json
import os
from pathlib import Path
import signal
import subprocess
import sys
import tempfile
import time
import unittest
from unittest import mock

sys.dont_write_bytecode = True
SCRIPT = Path(__file__).with_name("check-dependency-floors.py")
spec = importlib.util.spec_from_file_location("floors", SCRIPT)
floors = importlib.util.module_from_spec(spec)
spec.loader.exec_module(floors)


class IsolationTests(unittest.TestCase):
    def test_build_metadata_does_not_hide_declared_floor(self):
        self.assertTrue(floors.satisfies("1.1.2+spec-1.1.0", "^1.1.2"))
        self.assertTrue(floors.satisfies("1.1.2+spec-1.1.0", "=1.1.2"))
        self.assertFalse(floors.satisfies("1.1.2-rc.1+build", "^1.1.2"))

    def test_success_failure_and_exception_preserve_later_caller_edit(self):
        for result in (0, 7, KeyboardInterrupt()):
            with self.subTest(result=result), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp) / "source"
                root.mkdir()
                (root / "Cargo.lock").write_text("original")
                (root / "uncommitted.rs").write_text("working bytes")
                (root / "ignored-generated.rs").write_text("generated bytes")
                (root / "target").mkdir()
                metadata = {"packages": [], "target_directory": str(root / "target")}

                def check():
                    self.assertNotEqual(floors.ROOT, root)
                    self.assertEqual((floors.ROOT / "uncommitted.rs").read_text(), "working bytes")
                    self.assertEqual((floors.ROOT / "ignored-generated.rs").read_text(), "generated bytes")
                    floors.LOCK.write_text("lowered")
                    (root / "Cargo.lock").write_text("developer's later edit")
                    if isinstance(result, BaseException):
                        raise result
                    return result

                with mock.patch.object(floors, "ROOT", root), mock.patch.object(floors, "LOCK", root / "Cargo.lock"), \
                     mock.patch.object(floors.subprocess, "check_output", return_value=json.dumps(metadata).encode()), \
                     mock.patch.object(floors, "check_floors", side_effect=check), mock.patch.object(sys, "argv", [str(SCRIPT)]):
                    if isinstance(result, BaseException):
                        with self.assertRaises(KeyboardInterrupt):
                            floors.main()
                    else:
                        self.assertEqual(floors.main(), result)
                self.assertEqual((root / "Cargo.lock").read_text(), "developer's later edit")
                self.assertEqual(list(Path(tmp).iterdir()), [root])

    @unittest.skipUnless(os.name == "posix", "process-group signals are Unix-specific")
    def test_sigterm_and_sigkill_never_modify_caller_lockfile(self):
        for sig in (signal.SIGTERM, signal.SIGKILL):
            with self.subTest(signal=sig), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp) / "source"
                (root / "scripts").mkdir(parents=True)
                (root / "scripts/check-dependency-floors.py").write_bytes(SCRIPT.read_bytes())
                (root / "Cargo.lock").write_text("caller lock")
                target = root / "target"
                target.mkdir()
                tools = Path(tmp) / "tools"
                tools.mkdir()
                cargo = tools / "cargo"
                cargo.write_text(f'''#!{sys.executable}
import json, os, pathlib, sys, time
if '--no-deps' in sys.argv:
    print(json.dumps({{"packages": [], "target_directory": {str(target)!r}}}))
elif 'metadata' in sys.argv:
    print(json.dumps({{"packages": [], "workspace_members": [], "resolve": {{"nodes": []}}}}))
else:
    pathlib.Path('Cargo.lock').write_text('lowered in isolated copy')
    pathlib.Path({str(target / 'ready')!r}).write_text(str(pathlib.Path.cwd()))
    time.sleep(30)
''')
                cargo.chmod(0o755)
                env = dict(os.environ, PATH=str(tools) + os.pathsep + os.environ["PATH"])
                with (Path(tmp) / "log").open("wb") as log:
                    child = subprocess.Popen([sys.executable, str(root / "scripts/check-dependency-floors.py")], env=env,
                                             stdout=log, stderr=log, start_new_session=True)
                    try:
                        deadline = time.monotonic() + 10
                        while not (target / "ready").exists() and child.poll() is None and time.monotonic() < deadline:
                            time.sleep(0.02)
                        self.assertTrue((target / "ready").exists(), (Path(tmp) / "log").read_text())
                        self.assertNotEqual(Path((target / "ready").read_text()), root)
                        (root / "Cargo.lock").write_text("later caller edit")
                        os.killpg(child.pid, sig)
                        child.wait(timeout=5)
                        self.assertEqual((root / "Cargo.lock").read_text(), "later caller edit")
                    finally:
                        if child.poll() is None:
                            os.killpg(child.pid, signal.SIGKILL)
                            child.wait()

    def test_external_patch_and_absolute_internal_path_are_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "source"
            root.mkdir()
            internal = root / "inside"
            internal.mkdir()
            for path in ("../outside", str(internal)):
                (root / "Cargo.toml").write_text('[patch.crates-io]\nfoo = { path = ' + json.dumps(path) + ' }\n')
                with self.assertRaisesRegex(RuntimeError, "cannot be relocated"):
                    floors.guard_source_paths(root, {"packages": []})

    @unittest.skipUnless(os.name == "posix", "symlink creation on Unix")
    def test_symlink_cannot_write_back_through_copy(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp) / "source"
            root.mkdir()
            (root / "Cargo.lock").symlink_to(Path(tmp) / "external.lock")
            with self.assertRaisesRegex(RuntimeError, "unsupported symlink"):
                floors.isolated_workspace(root, root / "target")
            self.assertEqual(list(Path(tmp).iterdir()), [root])


if __name__ == "__main__":
    unittest.main()
