//! Reading rig-core's public type surface out of rustdoc's JSON output.
//!
//! # Why rustdoc JSON, and not the sources
//!
//! The question this answers — "which provider types are generic over the HTTP
//! transport?" — cannot be answered by reading the source text, and the guard
//! this replaces tried to:
//!
//! - Several of those types are **generated by macros** (`impl_model_lister!`,
//!   the dual-dialect provider macros). They appear in no `pub struct` line, so
//!   a text scan invented a hardcoded list of them and silently missed the next
//!   one. rustdoc sees the expanded crate, so they are ordinary items here.
//! - The transport parameter is **not always named `H`** (`voyageai` and
//!   `azure` call it `T`), and the ones that must *not* be re-defaulted are
//!   exactly those that already carry a default (`ClientBuilder<H = Missing>`).
//!   A text scan matching `<H>` gets both of those wrong; rustdoc reports the
//!   parameter list with its defaults.
//! - Feature-gated types come and go with `--features`, so the gates are
//!   *derived* by building the surface once per feature rather than restated in
//!   the generator.
//!
//! # Why this can run on the pinned stable toolchain
//!
//! The JSON output is nightly-gated, so this sets `RUSTC_BOOTSTRAP=1` rather
//! than requiring a nightly install. That is normally a smell, and it is
//! deliberate here: the toolchain is pinned by `rust-toolchain.toml`, the
//! output is a build artifact consumed by this tool and never shipped, and the
//! alternative — a nightly toolchain in CI — makes the check fail on days when
//! nightly's format changes and nobody touched this repo. [`FORMAT_VERSION`]
//! pins the shape we parse, so a toolchain bump that changes it fails loudly
//! and immediately instead of silently generating a wrong tree.

use crate::reachable::{public_paths, shortest};
use serde_json::Value;
use std::collections::BTreeMap;
use std::path::Path;
use std::process::Command;

/// The rustdoc JSON format this parser was written against.
///
/// Bumping `rust-toolchain.toml` may bump this. If it does, re-read the parsing
/// below against the new format before changing the number — the fields used
/// are few, but they are load-bearing.
pub const FORMAT_VERSION: u64 = 57;

/// One transport-generic provider type.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct TransportGenericType {
    /// The provider module the alias belongs in: `openai`, `anthropic`, …
    pub provider: String,
    /// The type's own name: `CompletionModel`, `Client`, …
    pub name: String,
    /// Its full path in rig-core, which the alias points at.
    pub path: String,
    /// The name of its transport parameter, as declared (`H` or `T`).
    pub parameter: String,
}

/// Build rig-core's rustdoc JSON with `features` enabled, and return the
/// transport-generic provider types it contains.
pub fn transport_generic_types(
    workspace: &Path,
    features: &[&str],
) -> Result<Vec<TransportGenericType>, String> {
    let json = build(workspace, features)?;
    parse(&json)
}

fn build(workspace: &Path, features: &[&str]) -> Result<Value, String> {
    // A separate target directory keeps these doc builds from invalidating the
    // ordinary `cargo check` cache the developer is also using.
    let target_dir = workspace.join("target/xtask-rustdoc");
    let mut command = Command::new("cargo");
    command
        .current_dir(workspace)
        .env("RUSTC_BOOTSTRAP", "1")
        .env("CARGO_TARGET_DIR", &target_dir)
        .args([
            "rustdoc",
            "--quiet",
            "-p",
            "rig-core",
            "--no-default-features",
            "-Zunstable-options",
            "--output-format",
            "json",
        ]);
    if !features.is_empty() {
        command.args(["--features", &features.join(",")]);
    }

    let output = command
        .output()
        .map_err(|error| format!("could not run cargo rustdoc: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "cargo rustdoc failed for features {features:?}:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    let path = target_dir.join("doc/rig_core.json");
    let bytes = std::fs::read(&path)
        .map_err(|error| format!("could not read {}: {error}", path.display()))?;
    serde_json::from_slice(&bytes).map_err(|error| format!("could not parse rustdoc JSON: {error}"))
}

fn parse(json: &Value) -> Result<Vec<TransportGenericType>, String> {
    let format_version = json
        .get("format_version")
        .and_then(Value::as_u64)
        .unwrap_or_default();
    if format_version != FORMAT_VERSION {
        return Err(format!(
            "rustdoc JSON format version {format_version}, expected {FORMAT_VERSION}. The pinned \
             toolchain changed: re-read xtask/src/rustdoc.rs against the new format, then update \
             FORMAT_VERSION."
        ));
    }

    let index = json
        .get("index")
        .and_then(Value::as_object)
        .ok_or("rustdoc JSON has no `index`")?;
    let paths = json
        .get("paths")
        .and_then(Value::as_object)
        .ok_or("rustdoc JSON has no `paths`")?;

    // The path an alias may *write* is not always the path rustdoc reports the
    // item at; see `reachable.rs`.
    let reachable = public_paths(json);

    let mut found = BTreeMap::new();
    for (id, item) in index {
        // An item with no definition path is not part of this crate's surface.
        if !paths.contains_key(id) {
            continue;
        }
        let Some(public) = shortest(&reachable, id) else {
            continue;
        };
        let segments: Vec<&str> = public.iter().map(String::as_str).collect();
        let [crate_name, providers, provider, ..] = segments.as_slice() else {
            continue;
        };
        // `providers::<provider>::…`, and never the shared internals: those are
        // implementation detail the alias tree deliberately does not mirror.
        if *crate_name != "rig_core" || *providers != "providers" || segments.contains(&"internal")
        {
            continue;
        }

        let Some(parameters) = generic_parameters(item) else {
            continue;
        };
        // Exactly one type parameter, and no default. Both halves matter:
        //
        // - More than one means a *generic base* (`GenericCompletionModel<Ext,
        //   H>`), which the per-provider aliases are instantiations of; the
        //   tree aliases those instantiations, not the base.
        // - A default means the type has already stated its own intent —
        //   `ClientBuilder<H = Missing>` starts with an empty transport slot on
        //   purpose, and re-defaulting it to the bundled transport would break
        //   `builder().http_client(..)`.
        let [parameter] = parameters.as_slice() else {
            continue;
        };
        let Some(name) = type_parameter_without_default(parameter) else {
            continue;
        };

        let Some(type_name) = segments.last() else {
            continue;
        };
        found.insert(
            ((*provider).to_string(), (*type_name).to_string()),
            TransportGenericType {
                provider: (*provider).to_string(),
                name: (*type_name).to_string(),
                path: segments.join("::"),
                parameter: name,
            },
        );
    }

    Ok(found.into_values().collect())
}

/// The generic parameter list of a struct, enum or type alias; `None` for any
/// other item kind.
fn generic_parameters(item: &Value) -> Option<&Vec<Value>> {
    let inner = item.get("inner")?;
    for kind in ["struct", "enum", "type_alias"] {
        if let Some(body) = inner.get(kind) {
            return body
                .get("generics")
                .and_then(|generics| generics.get("params"))
                .and_then(Value::as_array);
        }
    }
    None
}

/// The parameter's name, if it is a type parameter carrying no default.
fn type_parameter_without_default(parameter: &Value) -> Option<String> {
    let kind = parameter.get("kind")?.get("type")?;
    if !kind.get("default").is_none_or(Value::is_null) {
        return None;
    }
    // A synthetic parameter is one rustdoc invented for an `impl Trait`
    // argument; it is never a transport slot a caller can name.
    if kind.get("is_synthetic").and_then(Value::as_bool) == Some(true) {
        return None;
    }
    parameter.get("name")?.as_str().map(str::to_string)
}
