[package]
edition = "2024"
name = "rig-wasm"
publish = false
version = "0.0.0"

[lib]
name = "rig"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
rig-core = { workspace = true, features = ["worker"] }
wasm-bindgen-futures = "0.4.50"
serde_json.workspace = true
serde-wasm-bindgen = "0.6.5"
anyhow.workspace = true
slab = "0.4.10"
send_wrapper = "0.6.0"
console_error_panic_hook = "0.1.7"
